// Generated by DDD Module Generator on 2025-07-04

import { defineStore } from 'pinia'
import { computed, ref } from 'vue'
import { ConnectionApiService } from '../../infrastructure/api/services/ConnectionApiService'
import type { ListFilters } from '../../../shared/types'
import type { ColumnInfoDto, ProcedureInfoDto, ProcedurePreviewDto, TableInfoDto, TestConnectionDto, TestConnectionResponseDto, TestQueryDto, TestQueryResponseDto } from '../../application/dtos/ConnectionDtos'

export const useConnectionStore = defineStore('connection', () => {
  // State
  const items = ref<any[]>([])
  const currentItem = ref<any>(null)
  const loading = ref(false)
  const error = ref<string | null>(null)

  // Pagination
  const page = ref(1)
  const itemsPerPage = ref(20)
  const total = ref(0)
  const totalPages = ref(0)

  // Filters
  const filters = ref<ListFilters>({})

  // Selection
  const selectedItems = ref<any[]>([])

  // Schema exploration state
  const tables = ref<TableInfoDto[]>([])
  const procedures = ref<ProcedureInfoDto[]>([])
  const columns = ref<ColumnInfoDto[]>([])
  const schemaLoading = ref(false)

  // Computed
  const currentPage = computed(() => page.value)
  const perPage = computed(() => itemsPerPage.value)

  // API Service
  const apiService = new ConnectionApiService()

  // Actions
  const fetchList = async () => {
    loading.value = true
    error.value = null

    try {
      const response = await apiService.getList({
        page: page.value,
        limit: itemsPerPage.value,
        ...filters.value,
      })

      // Use raw data from API instead of mapping to domain entities
      items.value = response.data
      total.value = response.pagination.total
      totalPages.value = Math.ceil(response.pagination.total / itemsPerPage.value)
    }
    catch (err) {
      error.value = err instanceof Error ? err.message : 'Failed to fetch connections'
    }
    finally {
      loading.value = false
    }
  }

  // Fetch all connections without pagination (for dropdowns)
  const fetchAll = async () => {
    loading.value = true
    error.value = null

    try {
      const response = await apiService.getList({
        limit: 1000, // Get a large number to get all connections
        page: 1,
      })

      // Return only the data array for use in dropdowns
      return response.data || []
    }
    catch (err) {
      error.value = err instanceof Error ? err.message : 'Failed to fetch all connections'

      return []
    }
    finally {
      loading.value = false
    }
  }

  const fetchById = async (id: string) => {
    loading.value = true
    error.value = null

    try {
      const response = await apiService.getById(id)

      currentItem.value = response
    }
    catch (err) {
      error.value = err instanceof Error ? err.message : 'Failed to fetch connection'
    }
    finally {
      loading.value = false
    }
  }

  const createItem = async (data: any) => {
    loading.value = true
    error.value = null

    try {
      const response = await apiService.create(data)

      await fetchList()

      return response.data
    }
    catch (err) {
      error.value = err instanceof Error ? err.message : 'Failed to create connection'
      throw err
    }
    finally {
      loading.value = false
    }
  }

  const updateItem = async (id: string, data: any) => {
    loading.value = true
    error.value = null

    try {
      const response = await apiService.update(id, data)

      await fetchList()

      return response.data
    }
    catch (err) {
      error.value = err instanceof Error ? err.message : 'Failed to update connection'
      throw err
    }
    finally {
      loading.value = false
    }
  }

  const deleteItem = async (id: string) => {
    loading.value = true
    error.value = null

    try {
      await apiService.delete(id)
      await fetchList()
    }
    catch (err) {
      error.value = err instanceof Error ? err.message : 'Failed to delete connection'
      throw err
    }
    finally {
      loading.value = false
    }
  }

  const setPage = (newPage: number) => {
    page.value = newPage
  }

  const clearError = () => {
    error.value = null
  }

  const exportItems = (type: string) => {
    // TODO: Implement export functionality
    console.log('Exporting connections as', type)
  }

  // Test connection before save (nuevo método)
  const testConnectionBeforeSave = async (data: TestConnectionDto): Promise<TestConnectionResponseDto> => {
    try {
      return await apiService.testConnectionBeforeSave(data)
    }
    catch (error: any) {
      let errorMsg = error.message || 'Connection test failed'
      if (error.errors && error.errors.error)
        errorMsg = error.errors.error

      return { success: false, message: errorMsg }
    }
  }

  // Test existing connection
  const testConnection = async (id: string): Promise<TestConnectionResponseDto> => {
    try {
      const result = await apiService.testConnection(id)

      return { success: true, message: 'Connection test successful', data: result }
    }
    catch (error: any) {
      let errorMsg = error.message || 'Connection test failed'
      if (error.errors && error.errors.error)
        errorMsg = error.errors.error

      return { success: false, message: errorMsg }
    }
  }

  // Schema exploration methods
  const fetchTablesAndViews = async (connectionId: string) => {
    schemaLoading.value = true
    error.value = null

    try {
      const response = await apiService.getTablesAndViews(connectionId)

      tables.value = response.data || []

      return response
    }
    catch (err) {
      error.value = err instanceof Error ? err.message : 'Failed to fetch tables and views'
      throw err
    }
    finally {
      schemaLoading.value = false
    }
  }

  const fetchProcedures = async (connectionId: string) => {
    schemaLoading.value = true
    error.value = null

    try {
      const response = await apiService.getProcedures(connectionId)

      procedures.value = response.data || []

      return response
    }
    catch (err) {
      error.value = err instanceof Error ? err.message : 'Failed to fetch procedures'
      throw err
    }
    finally {
      schemaLoading.value = false
    }
  }

  const fetchColumns = async (connectionId: string, params: { table?: string; procedure?: string }) => {
    schemaLoading.value = true
    error.value = null

    try {
      const response = await apiService.getColumns(connectionId, params)

      columns.value = response.data || []

      return response
    }
    catch (err) {
      error.value = err instanceof Error ? err.message : 'Failed to fetch columns'
      throw err
    }
    finally {
      schemaLoading.value = false
    }
  }

  const getProcedurePreview = async (connectionId: string, data: ProcedurePreviewDto) => {
    schemaLoading.value = true
    error.value = null

    try {
      return await apiService.getProcedurePreview(connectionId, data)
    }
    catch (err) {
      error.value = err instanceof Error ? err.message : 'Failed to get procedure preview'
      throw err
    }
    finally {
      schemaLoading.value = false
    }
  }

  const testQuery = async (connectionId: string, data: TestQueryDto): Promise<TestQueryResponseDto> => {
    schemaLoading.value = true
    error.value = null

    try {
      return await apiService.testQuery(connectionId, data)
    }
    catch (err) {
      error.value = err instanceof Error ? err.message : 'Failed to test query'
      throw err
    }
    finally {
      schemaLoading.value = false
    }
  }

  // Health check
  const healthCheck = async () => {
    try {
      return await apiService.healthCheck()
    }
    catch (err) {
      error.value = err instanceof Error ? err.message : 'Health check failed'
      throw err
    }
  }

  return {
    // State
    items,
    currentItem,
    loading,
    error,

    // Pagination
    page,
    itemsPerPage,
    total,
    totalPages,
    currentPage,
    perPage,

    // Filters
    filters,

    // Selection
    selectedItems,

    // Schema exploration state
    tables,
    procedures,
    columns,
    schemaLoading,

    // Actions
    fetchList,
    fetchAll,
    fetchById,
    createItem,
    updateItem,
    deleteItem,
    setPage,
    clearError,
    exportItems,
    testConnectionBeforeSave,
    testConnection,
    fetchTablesAndViews,
    fetchProcedures,
    fetchColumns,
    getProcedurePreview,
    testQuery,
    healthCheck,
  }
})
