<!-- Generated by DDD Module Generator on 2025-07-04 -->
<script setup lang="ts">
interface Props {
  dataSource: any
}

const props = defineProps<Props>()
</script>

<template>
  <div class="data-source-detail">
    <VList>
      <VListItem>
        <VListItemTitle>{ t('Connection Id') }</VListItemTitle>
        <VListItemSubtitle>{{ dataSource.connection_id }}</VListItemSubtitle>
      </VListItem>
      <VListItem>
        <VListItemTitle>{ t('Name') }</VListItemTitle>
        <VListItemSubtitle>{{ dataSource.name }}</VListItemSubtitle>
      </VListItem>
      <VListItem>
        <VListItemTitle>{ t('Type') }</VListItemTitle>
        <VListItemSubtitle>{{ dataSource.type }}</VListItemSubtitle>
      </VListItem>
      <VListItem>
        <VListItemTitle>{ t('Custom SQL') }</VListItemTitle>
        <VListItemSubtitle>{{ dataSource.custom_sql }}</VListItemSubtitle>
      </VListItem>
      <VListItem>
        <VListItemTitle>{ t('Available Fields') }</VListItemTitle>
        <VListItemSubtitle>{{ dataSource.available_fields }}</VListItemSubtitle>
      </VListItem>
    </VList>
  </div>
</template>
