<!-- Generated by DDD Module Generator on 2025-07-04 -->
<script setup lang="ts">
import { useForm } from 'vee-validate'
import { toTypedSchema } from '@vee-validate/zod'
import * as z from 'zod'
import { computed, onMounted, ref, watch } from 'vue'
import { VStepperTitle } from 'vuetify/components'
import { useDataSourceStore } from '../../stores/dataSourceStore'
import { useConnectionStore } from '../../../../Connection/presentation/stores/connectionStore'

interface Props {
  mode: 'create' | 'edit'
  initialData?: any
  title?: string
  loading?: boolean
}

interface Emits {
  (e: 'submit', data: any): void
  (e: 'cancel'): void
  (e: 'close'): void
}

const props = withDefaults(defineProps<Props>(), {
  title: 'DataSource Form',
  loading: false,
})

const emit = defineEmits<Emits>()
const dataSourceStore = useDataSourceStore()
const connectionStore = useConnectionStore()
const { closeDialog } = useAppManager()

// Stepper state
const currentStep = ref(1)

const steps = [
  {
    title: 'Conectar',
    icon: 'mdi-database',
    rules: [],
  },
  {
    title: 'Modelar',
    icon: 'mdi-cog',
    rules: [],
  },
  {
    title: 'Filtrar & Probar',
    icon: 'mdi-filter',
    rules: [],
  },
]

// Preview state
const previewLoading = ref(false)
const previewData = ref([])
const previewHeaders = ref([])
const testLoading = ref(false)
const testResult = ref(null)

// Field types for available fields
const fieldTypes = [
  { title: 'Texto', value: 'text' },
  { title: 'Número', value: 'number' },
  { title: 'Moneda', value: 'currency' },
  { title: 'Fecha', value: 'date' },
  { title: 'Fecha y Hora', value: 'datetime' },
  { title: 'Booleano', value: 'boolean' },
  { title: 'Enmascarado', value: 'masked' },
]

// Filter types
const filterTypes = [
  { title: 'Selector', value: 'select' },
  { title: 'Selector Múltiple', value: 'multiselect' },
  { title: 'Rango de Fechas', value: 'date_range' },
  { title: 'Texto', value: 'text' },
  { title: 'Número', value: 'number' },
]

// Reactive objects for complex fields
const availableFields = ref<Record<string, { label: string; type: string }>>({})
const filterDefinitions = ref<Record<string, { label: string; type: string; options: string }>>({})

// Connection options
const connectionOptions = computed(() => {
  return connectionStore.items.map(connection => ({
    id: connection.id,
    name: connection.name || connection.connection_name || `Connection ${connection.id}`,
  }))
})

// Available field options for filters
const availableFieldOptions = computed(() => {
  return Object.keys(availableFields.value).map(key => ({
    title: availableFields.value[key].label || key,
    value: key,
  }))
})

// Form validation schema
const schema = toTypedSchema(z.object({
  connection_id: z.string().min(1, 'Conexión es requerida'),
  name: z.string().min(1, 'Nombre es requerido'),
  type: z.enum(['custom_sql', 'visual_builder', 'hybrid']),
  custom_sql: z.string().min(1, 'SQL personalizado es requerido'),
  available_fields: z.record(z.object({
    label: z.string(),
    type: z.string(),
  })),
  filter_definitions: z.record(z.object({
    label: z.string(),
    type: z.string(),
    options: z.string().optional(),
  })),
}))

const { handleSubmit, errors, values, setFieldValue } = useForm({
  validationSchema: schema,
  initialValues: props.initialData || {
    connection_id: '',
    name: '',
    type: 'custom_sql',
    custom_sql: '',
    available_fields: {},
    filter_definitions: {},
  },
})

// Load connections on mount
onMounted(async () => {
  if (connectionStore.items.length === 0)
    await connectionStore.fetchList()
})

// Watch for changes in complex fields and update form values
watch(availableFields, newFields => {
  setFieldValue('available_fields', newFields)
}, { deep: true })

watch(filterDefinitions, newFilters => {
  setFieldValue('filter_definitions', newFilters)
}, { deep: true })

// Initialize complex fields from initial data
watch(() => props.initialData, newData => {
  if (newData) {
    availableFields.value = newData.available_fields || {}
    filterDefinitions.value = newData.filter_definitions || {}
  }
}, { immediate: true })

// Stepper navigation
const canProceedToNextStep = computed(() => {
  switch (currentStep.value) {
  case 1:
    return values.connection_id && values.name && values.type
  case 2:
    return Object.keys(availableFields.value).length > 0
  case 3:
    return true
  default:
    return false
  }
})

const nextStep = () => {
  if (currentStep.value < 3) {
    currentStep.value++
  }
}

const previousStep = () => {
  if (currentStep.value > 1) {
    currentStep.value--
  }
}

const goToStep = (step: number) => {
  currentStep.value = step
}

// Field type icons
const getFieldTypeIcon = (type: string) => {
  const icons = {
    text: 'mdi-format-text',
    number: 'mdi-numeric',
    currency: 'mdi-currency-usd',
    date: 'mdi-calendar',
    datetime: 'mdi-calendar-clock',
    boolean: 'mdi-checkbox-marked-circle',
    masked: 'mdi-eye-off',
  }

  return icons[type] || 'mdi-help-circle'
}

// Drag and drop handlers
const onDragStart = (event: DragEvent, key: string) => {
  if (event.dataTransfer)
    event.dataTransfer.setData('text/plain', key)
}

// Test filters
const testFilters = async () => {
  testLoading.value = true
  testResult.value = null

  try {
    // Simulate API call
    await new Promise(resolve => setTimeout(resolve, 1000))
    testResult.value = {
      success: true,
      message: 'Filtros configurados correctamente. El reporte está listo para usar.',
    }
  }
  catch (error) {
    testResult.value = {
      success: false,
      message: 'Error al probar filtros. Verifica la configuración.',
    }
  }
  finally {
    testLoading.value = false
  }
}

// Open new connection dialog
const openNewConnectionDialog = () => {
  // TODO: Implement new connection dialog
  console.log('Open new connection dialog')
}

// Load example data function
const loadExampleData = () => {
  // Set basic form data
  setFieldValue('name', 'Ingresos JAPAMA')
  setFieldValue('type', 'custom_sql')
  setFieldValue('custom_sql', 'SELECT fk_payment_source as FOLIO, fecha_pago as FECHA, cuenta as CUENTA, usuario as USUARIO, tipo_contrato as CONTRATO, entidad as ENTIDAD, localidad as LOCALIDAD, sistema as SISTEMA, sector as SECTOR, ruta as RUTA, concepto as CONCEPTO, base as BASE, iva as IVA, total as TOTAL, UPPER(cajero) as CAJERO, caja as CAJA, descripcion as DESCRIPCION, metodo_pago as METODO_PAGO, banco as BANCO, referencia as REFERENCIA, periodo as PERIODO, anio_origen, CASE WHEN metodo_pago IN (\'T. de Crédito\', \'T. de Débito\') THEN CASE WHEN referencia LIKE \'%-%\' THEN CONCAT(\'****\', SUBSTRING(SUBSTRING_INDEX(referencia, \'-\', -1), -4)) ELSE CONCAT(\'****\', SUBSTRING(referencia, -4)) END ELSE \'\' END as NUMERO_TARJETA, CASE WHEN metodo_pago = \'Transferencia\' THEN referencia ELSE \'\' END as TRANSFERENCIA, CASE WHEN metodo_pago = \'Cheque\' THEN referencia ELSE \'\' END as CHEQUE FROM llx_cashbox_closure_income WHERE 1=1')

  // Set available fields
  availableFields.value = {
    FOLIO: { label: 'Folio', type: 'text' },
    FECHA: { label: 'Fecha', type: 'datetime' },
    CUENTA: { label: 'Cuenta', type: 'text' },
    USUARIO: { label: 'Usuario', type: 'text' },
    CONTRATO: { label: 'Contrato', type: 'text' },
    ENTIDAD: { label: 'Entidad', type: 'text' },
    LOCALIDAD: { label: 'Localidad', type: 'text' },
    SISTEMA: { label: 'Sistema', type: 'text' },
    SECTOR: { label: 'Sector', type: 'text' },
    RUTA: { label: 'Ruta', type: 'text' },
    CONCEPTO: { label: 'Concepto', type: 'text' },
    BASE: { label: 'Base', type: 'currency' },
    IVA: { label: 'IVA', type: 'currency' },
    TOTAL: { label: 'Total', type: 'currency' },
    CAJERO: { label: 'Cajero', type: 'text' },
    CAJA: { label: 'Caja', type: 'text' },
    DESCRIPCION: { label: 'Descripción', type: 'text' },
    METODO_PAGO: { label: 'Método Pago', type: 'text' },
    BANCO: { label: 'Banco', type: 'text' },
    REFERENCIA: { label: 'Referencia', type: 'text' },
    NUMERO_TARJETA: { label: 'Número Tarjeta', type: 'masked' },
    TRANSFERENCIA: { label: 'Transferencia', type: 'text' },
    CHEQUE: { label: 'Cheque', type: 'text' },
    PERIODO: { label: 'Periodo', type: 'text' },
  }

  // Set filter definitions
  filterDefinitions.value = {
    anio_origen: { label: 'Ejercicio', type: 'select', options: 'dynamic' },
    caja: { label: 'Caja', type: 'multiselect', options: 'dynamic' },
    periodo: { label: 'Periodo', type: 'multiselect', options: 'dynamic' },
    localidad: { label: 'Localidad', type: 'multiselect', options: 'dynamic' },
    sector: { label: 'Sector', type: 'multiselect', options: 'dynamic' },
    ruta: { label: 'Ruta', type: 'multiselect', options: 'dynamic' },
    cajero: { label: 'Cajero', type: 'multiselect', options: 'dynamic' },
    concepto: { label: 'Concepto', type: 'multiselect', options: 'dynamic' },
    metodo_pago: { label: 'Método Pago', type: 'multiselect', options: 'dynamic' },
    fecha_pago: { label: 'Rango de Fechas', type: 'date_range' },
  }
}

// Available fields methods
const addAvailableField = () => {
  const newKey = `field_${Object.keys(availableFields.value).length + 1}`

  availableFields.value[newKey] = { label: '', type: 'text' }
}

const updateFieldKey = (oldKey: string, newKey: string) => {
  if (oldKey !== newKey && newKey) {
    const value = availableFields.value[oldKey]

    delete availableFields.value[oldKey]
    availableFields.value[newKey] = value
  }
}

const updateFieldLabel = (key: string, label: string) => {
  if (availableFields.value[key])
    availableFields.value[key].label = label
}

const updateFieldType = (key: string, type: string) => {
  if (availableFields.value[key])
    availableFields.value[key].type = type
}

const removeAvailableField = (key: string) => {
  delete availableFields.value[key]
}

// Filter definitions methods
const addFilterDefinition = () => {
  const newKey = `filter_${Object.keys(filterDefinitions.value).length + 1}`

  filterDefinitions.value[newKey] = { label: '', type: 'select', options: 'dynamic' }
}

const updateFilterKey = (oldKey: string, newKey: string) => {
  if (oldKey !== newKey && newKey) {
    const value = filterDefinitions.value[oldKey]

    delete filterDefinitions.value[oldKey]
    filterDefinitions.value[newKey] = value
  }
}

const updateFilterLabel = (key: string, label: string) => {
  if (filterDefinitions.value[key])
    filterDefinitions.value[key].label = label
}

const updateFilterType = (key: string, type: string) => {
  if (filterDefinitions.value[key])
    filterDefinitions.value[key].type = type
}

const updateFilterOptions = (key: string, options: string) => {
  if (filterDefinitions.value[key])
    filterDefinitions.value[key].options = options
}

const removeFilterDefinition = (key: string) => {
  delete filterDefinitions.value[key]
}

const onSubmit = handleSubmit(async formValues => {
  try {
    // Prepare the data with the complex fields
    const submitData = {
      ...formValues,
      available_fields: availableFields.value,
      filter_definitions: filterDefinitions.value,
    }

    if (props.mode === 'create')
      await dataSourceStore.createItem(submitData)
    else if (props.mode === 'edit')
      await dataSourceStore.updateItem(submitData.id, submitData)

    close('submit', submitData)
  }
  catch (error) {
    console.error(error)
  }
})

function close(result: 'close' | 'submit' | 'cancel' = 'close') {
  closeDialog(result)
}
</script>

<template>
  <VForm @submit.prevent="handleSubmit">
    <DialogCloseBtn @click="close('cancel')" />
    <VCard>
      <VCardTitle>
        <div class="d-flex align-center justify-space-between">
          <span>{{ title }}</span>
          <VBtn
            v-if="mode === 'create'"
            size="small"
            variant="outlined"
            color="info"
            class="ml-2"
            @click="loadExampleData"
          >
            Load Example
          </VBtn>
        </div>
      </VCardTitle>

      <!-- Stepper Header -->
      <VCardText class="pb-0">
        <VStepper
          v-model="currentStep"
          class="elevation-0"
        >
          <VStepperHeader>
            <template
              v-for="(step, index) in steps"
              :key="index"
            >
              <VStepperItem
                :value="index + 1"
                :complete="currentStep > index + 1"
                :rules="step.rules"
                @click="goToStep(index + 1)"
              >
                <VStepperTitle>
                  <VIcon
                    :icon="step.icon"
                    class="me-2"
                  />
                  {{ step.title }}
                </VStepperTitle>
              </VStepperItem>

              <VDivider v-if="index < steps.length - 1" />
            </template>
          </VStepperHeader>
        </VStepper>
      </VCardText>

      <VCardText>
        <!-- Step 1: Conectar -->
        <div v-if="currentStep === 1">
          <VRow>
            <VCol cols="12">
              <VAlert
                type="info"
                variant="tonal"
                class="mb-4"
              >
                <VIcon
                  icon="mdi-information"
                  class="me-2"
                />
                Selecciona de dónde obtendrás la información. Si no sabes qué elegir, usa Custom SQL y pega tu consulta.
              </VAlert>
            </VCol>

            <!-- Connection Selector -->
            <VCol
              cols="12"
              md="8"
            >
              <VSelect
                :model-value="values.connection_id"
                label="Conexión"
                :error-messages="errors.connection_id"
                :items="connectionOptions"
                item-title="name"
                item-value="id"
                placeholder="Selecciona una conexión"
                required
                :loading="connectionStore.loading"
                prepend-inner-icon="mdi-database"
                @update:model-value="val => setFieldValue('connection_id', val)"
              >
                <template #append>
                  <VBtn
                    icon="mdi-plus"
                    size="small"
                    variant="text"
                    class="ml-2"
                    @click="openNewConnectionDialog"
                  />
                </template>
              </VSelect>
            </VCol>

            <!-- Report Name -->
            <VCol
              cols="12"
              md="4"
            >
              <VTextField
                :model-value="values.name"
                label="Nombre del Reporte"
                :error-messages="errors.name"
                placeholder="Ej: Ingresos JAPAMA"
                required
                :counter="50"
                prepend-inner-icon="mdi-file-document"
                @update:model-value="val => setFieldValue('name', val)"
              />
            </VCol>

            <!-- Data Source Type -->
            <VCol cols="12">
              <VCard
                variant="outlined"
                class="pa-4"
              >
                <VCardTitle class="text-h6 mb-4">
                  Tipo de Origen
                </VCardTitle>
                <VBtnToggle
                  :model-value="values.type"
                  mandatory
                  class="w-100"
                  @update:model-value="val => setFieldValue('type', val)"
                >
                  <VBtn
                    value="custom_sql"
                    variant="outlined"
                    class="flex-grow-1"
                  >
                    <VIcon
                      icon="mdi-code-braces"
                      class="me-2"
                    />
                    Custom SQL
                  </VBtn>
                  <VBtn
                    value="visual_builder"
                    variant="outlined"
                    class="flex-grow-1"
                  >
                    <VIcon
                      icon="mdi-table"
                      class="me-2"
                    />
                    Tabla/Vista
                  </VBtn>
                  <VBtn
                    value="hybrid"
                    variant="outlined"
                    class="flex-grow-1"
                  >
                    <VIcon
                      icon="mdi-function"
                      class="me-2"
                    />
                    Stored Procedure
                  </VBtn>
                </VBtnToggle>
              </VCard>
            </VCol>

            <!-- SQL Editor -->
            <VCol
              v-if="values.type === 'custom_sql'"
              cols="12"
            >
              <VTextarea
                :model-value="values.custom_sql"
                label="Consulta SQL"
                :error-messages="errors.custom_sql"
                placeholder="Escribe tu consulta SQL aquí..."
                rows="8"
                auto-grow
                required
                prepend-inner-icon="mdi-code-braces"
                @update:model-value="val => setFieldValue('custom_sql', val)"
              />
            </VCol>
          </VRow>
        </div>

        <!-- Step 2: Modelar -->
        <div v-if="currentStep === 2">
          <VRow>
            <VCol cols="12">
              <VAlert
                type="info"
                variant="tonal"
                class="mb-4"
              >
                <VIcon
                  icon="mdi-information"
                  class="me-2"
                />
                Arrastra los campos que quieres ver en tu reporte. Puedes cambiar su nombre y tipo de dato.
              </VAlert>
            </VCol>

            <!-- Data Preview -->
            <VCol
              cols="12"
              md="8"
            >
              <VCard variant="outlined">
                <VCardTitle class="text-h6">
                  <VIcon
                    icon="mdi-table"
                    class="me-2"
                  />
                  Vista Previa de Datos
                </VCardTitle>
                <VCardText>
                  <VDataTable
                    :headers="previewHeaders"
                    :items="previewData"
                    :loading="previewLoading"
                    class="elevation-0"
                    density="compact"
                  />
                </VCardText>
              </VCard>
            </VCol>

            <!-- Available Fields Panel -->
            <VCol
              cols="12"
              md="4"
            >
              <VCard variant="outlined">
                <VCardTitle class="text-h6">
                  <VIcon
                    icon="mdi-drag"
                    class="me-2"
                  />
                  Campos Disponibles
                </VCardTitle>
                <VCardText>
                  <div class="mb-4">
                    <VChip
                      v-for="(field, key) in availableFields"
                      :key="key"
                      class="ma-1"
                      draggable
                      @dragstart="onDragStart($event, key)"
                    >
                      <VIcon
                        :icon="getFieldTypeIcon(field.type)"
                        class="me-1"
                      />
                      {{ field.label || key }}
                    </VChip>
                  </div>

                  <VBtn
                    icon="mdi-plus"
                    variant="outlined"
                    class="w-100"
                    @click="addAvailableField"
                  >
                    Agregar Campo
                  </VBtn>
                </VCardText>
              </VCard>
            </VCol>

            <!-- Field Editor -->
            <VCol cols="12">
              <VCard variant="outlined">
                <VCardTitle class="text-h6">
                  <VIcon
                    icon="mdi-cog"
                    class="me-2"
                  />
                  Configurar Campos
                </VCardTitle>
                <VCardText>
                  <div
                    v-for="(field, key) in availableFields"
                    :key="key"
                    class="mb-4 pa-4 border rounded"
                  >
                    <VRow>
                      <VCol
                        cols="12"
                        md="4"
                      >
                        <VTextField
                          :model-value="key"
                          label="Nombre del Campo"
                          placeholder="e.g., FOLIO"
                          @update:model-value="updateFieldKey(key, $event)"
                        />
                      </VCol>
                      <VCol
                        cols="12"
                        md="4"
                      >
                        <VTextField
                          :model-value="field.label"
                          label="Etiqueta"
                          placeholder="e.g., Folio"
                          @update:model-value="updateFieldLabel(key, $event)"
                        />
                      </VCol>
                      <VCol
                        cols="12"
                        md="3"
                      >
                        <VSelect
                          :model-value="field.type"
                          label="Tipo"
                          :items="fieldTypes"
                          @update:model-value="updateFieldType(key, $event)"
                        />
                      </VCol>
                      <VCol
                        cols="12"
                        md="1"
                      >
                        <VBtn
                          icon="mdi-delete"
                          color="error"
                          variant="text"
                          size="small"
                          @click="removeAvailableField(key)"
                        />
                      </VCol>
                    </VRow>
                  </div>
                </VCardText>
              </VCard>
            </VCol>
          </VRow>
        </div>

        <!-- Step 3: Filtrar & Probar -->
        <div v-if="currentStep === 3">
          <VRow>
            <VCol cols="12">
              <VAlert
                type="info"
                variant="tonal"
                class="mb-4"
              >
                <VIcon
                  icon="mdi-information"
                  class="me-2"
                />
                Configura los filtros que aparecerán en tu reporte. Puedes probar los resultados en tiempo real.
              </VAlert>
            </VCol>

            <!-- Filter Builder -->
            <VCol
              cols="12"
              md="8"
            >
              <VCard variant="outlined">
                <VCardTitle class="text-h6">
                  <VIcon
                    icon="mdi-filter"
                    class="me-2"
                  />
                  Constructor de Filtros
                </VCardTitle>
                <VCardText>
                  <div
                    v-for="(filter, key) in filterDefinitions"
                    :key="key"
                    class="mb-4 pa-4 border rounded"
                  >
                    <VRow>
                      <VCol
                        cols="12"
                        md="3"
                      >
                        <VSelect
                          :model-value="key"
                          label="Campo"
                          :items="availableFieldOptions"
                          placeholder="Selecciona campo"
                          @update:model-value="updateFilterKey(key, $event)"
                        />
                      </VCol>
                      <VCol
                        cols="12"
                        md="3"
                      >
                        <VTextField
                          :model-value="filter.label"
                          label="Etiqueta"
                          placeholder="e.g., Ejercicio"
                          @update:model-value="updateFilterLabel(key, $event)"
                        />
                      </VCol>
                      <VCol
                        cols="12"
                        md="3"
                      >
                        <VSelect
                          :model-value="filter.type"
                          label="Tipo"
                          :items="filterTypes"
                          @update:model-value="updateFilterType(key, $event)"
                        />
                      </VCol>
                      <VCol
                        cols="12"
                        md="2"
                      >
                        <VTextField
                          :model-value="filter.options"
                          label="Opciones"
                          placeholder="e.g., dynamic"
                          @update:model-value="updateFilterOptions(key, $event)"
                        />
                      </VCol>
                      <VCol
                        cols="12"
                        md="1"
                      >
                        <VBtn
                          icon="mdi-delete"
                          color="error"
                          variant="text"
                          size="small"
                          @click="removeFilterDefinition(key)"
                        />
                      </VCol>
                    </VRow>
                  </div>

                  <VBtn
                    icon="mdi-plus"
                    variant="outlined"
                    class="w-100"
                    @click="addFilterDefinition"
                  >
                    Agregar Filtro
                  </VBtn>
                </VCardText>
              </VCard>
            </VCol>

            <!-- Test Panel -->
            <VCol
              cols="12"
              md="4"
            >
              <VCard variant="outlined">
                <VCardTitle class="text-h6">
                  <VIcon
                    icon="mdi-test-tube"
                    class="me-2"
                  />
                  Probar Filtros
                </VCardTitle>
                <VCardText>
                  <VBtn
                    icon="mdi-play"
                    color="primary"
                    :loading="testLoading"
                    class="w-100 mb-4"
                    @click="testFilters"
                  >
                    Previsualizar Resultados
                  </VBtn>

                  <VAlert
                    v-if="testResult"
                    :type="testResult.success ? 'success' : 'error'"
                    variant="tonal"
                  >
                    {{ testResult.message }}
                  </VAlert>
                </VCardText>
              </VCard>
            </VCol>
          </VRow>
        </div>
      </VCardText>

      <VCardActions>
        <VBtn
          v-if="currentStep > 1"
          color="secondary"
          variant="tonal"
          @click="previousStep"
        >
          <VIcon
            icon="mdi-arrow-left"
            class="me-2"
          />
          Anterior
        </VBtn>

        <VSpacer />

        <VBtn
          v-if="currentStep < 3"
          color="primary"
          :disabled="!canProceedToNextStep"
          @click="nextStep"
        >
          Siguiente
          <VIcon
            icon="mdi-arrow-right"
            class="ms-2"
          />
        </VBtn>

        <VBtn
          v-if="currentStep === 3"
          type="submit"
          color="primary"
          :loading="loading"
        >
          <VIcon
            icon="mdi-check"
            class="me-2"
          />
          {{ mode === 'create' ? 'Crear' : 'Actualizar' }}
        </VBtn>

        <VBtn
          color="secondary"
          variant="tonal"
          @click="close('cancel')"
        >
          Cancelar
        </VBtn>
      </VCardActions>
    </VCard>
  </VForm>
</template>
