// Generated by DDD Module Generator on 2025-09-10

import { useRouter } from 'vue-router'
import { useI18n } from 'vue-i18n'

// Import module routes and menu
import TransportModuleRoutes from './config/routes'
import TransportModuleMenu from './config/menu'

export class TransportModuleInstaller {
  private router: any
  private i18n: any

  constructor() {
    this.setupDependencies()
  }

  private setupDependencies() {
    // Get router from the current app context
    try {
      this.router = useRouter()
    }
    catch (error) {
      console.warn('Router not available in current context, will register routes later')
      this.router = null
    }

    // Get i18n from the current app context
    try {
      this.i18n = useI18n()
    }
    catch (error) {
      console.warn('i18n not available in current context')
      this.i18n = null
    }
  }

  async install() {
    try {
      // Register routes
      this.registerRoutes()

      // Add menu items
      this.addMenuItems()

      // Add translations
      await this.addTranslations()

      // Add CASL abilities
      this.addCaslAbilities()

      return true
    }
    catch (error) {
      console.error('❌ Error installing TransportModule:', error)

      return false
    }
  }

  private registerRoutes() {
    if (!this.router) {
      console.warn('Router not available, routes will be registered when router is available')

      return
    }

    TransportModuleRoutes.forEach(route => {
      this.router.addRoute(route)
    })
  }

  private addMenuItems() {
    // Add menu items to the main navigation
    if (window.mainMenu)
      window.mainMenu.push(...TransportModuleMenu)
  }

  private async addTranslations() {
    try {
      // Dynamic imports for translation files
      const [enTranslations, esTranslations] = await Promise.all([
        import('./locales/en.json'),
        import('./locales/es.json'),
      ])

      if (this.i18n && this.i18n.global) {
        this.i18n.global.mergeLocaleMessage('en', enTranslations.default)
        this.i18n.global.mergeLocaleMessage('es', esTranslations.default)
      }
    }
    catch (error) {
      console.error('Error loading transport translations:', error)

      // Fallback: minimal translations if files can't be loaded
      const fallbackTranslations = {
        en: {
          navigation: { transport: 'Transport' },
        },
        es: {
          navigation: { transport: 'Transporte' },
        },
      }

      if (this.i18n && this.i18n.global) {
        this.i18n.global.mergeLocaleMessage('en', fallbackTranslations.en)
        this.i18n.global.mergeLocaleMessage('es', fallbackTranslations.es)
      }
    }
  }

  private addCaslAbilities() {
    // Add CASL abilities for module permissions
    const abilities = [
      // Transport general
      { action: 'read', subject: 'transport' },

      // Vehicles
      { action: 'read', subject: 'vehicles' },
      { action: 'create', subject: 'vehicles' },
      { action: 'update', subject: 'vehicles' },
      { action: 'delete', subject: 'vehicles' },
      { action: 'export', subject: 'vehicles' },

      // Drivers
      { action: 'read', subject: 'drivers' },
      { action: 'create', subject: 'drivers' },
      { action: 'update', subject: 'drivers' },
      { action: 'delete', subject: 'drivers' },
      { action: 'export', subject: 'drivers' },

      // Concessions
      { action: 'read', subject: 'concessions' },
      { action: 'create', subject: 'concessions' },
      { action: 'update', subject: 'concessions' },
      { action: 'delete', subject: 'concessions' },
      { action: 'export', subject: 'concessions' },
      { action: 'renew', subject: 'concessions' },

      // Concession Holders
      { action: 'read', subject: 'concession-holders' },
      { action: 'create', subject: 'concession-holders' },
      { action: 'update', subject: 'concession-holders' },
      { action: 'delete', subject: 'concession-holders' },
      { action: 'export', subject: 'concession-holders' },

      // Fines
      { action: 'read', subject: 'fines' },
      { action: 'create', subject: 'fines' },
      { action: 'update', subject: 'fines' },
      { action: 'delete', subject: 'fines' },
      { action: 'export', subject: 'fines' },
      { action: 'pay', subject: 'fines' },

      // Documents
      { action: 'read', subject: 'documents' },
      { action: 'create', subject: 'documents' },
      { action: 'update', subject: 'documents' },
      { action: 'delete', subject: 'documents' },
      { action: 'download', subject: 'documents' },
      { action: 'verify', subject: 'documents' },
    ]

    if (window.caslAbilities)
      window.caslAbilities.push(...abilities)
  }

  uninstall() {
    try {
      // Remove routes
      this.removeRoutes()

      // Remove menu items
      this.removeMenuItems()

      // Remove translations
      this.removeTranslations()

      // Remove CASL abilities
      this.removeCaslAbilities()

      return true
    }
    catch (error) {
      console.error('❌ Error uninstalling TransportModule:', error)

      return false
    }
  }

  private removeRoutes() {
    // Remove module routes
    if (this.router) {
      TransportModuleRoutes.forEach(route => {
        const existingRoute = this.router.getRoutes().find(r => r.name === route.name)
        if (existingRoute)
          this.router.removeRoute(route.name)
      })
    }
  }

  private removeMenuItems() {
    // Remove menu items
    if (window.mainMenu) {
      window.mainMenu = window.mainMenu.filter(item =>
        !TransportModuleMenu.some(menuItem => menuItem.to === item.to),
      )
    }
  }

  private removeTranslations() {
    // Remove translations
    if (this.i18n && this.i18n.global) {
      // Implementation depends on i18n setup
    }
  }

  private removeCaslAbilities() {
    // Remove CASL abilities
    if (window.caslAbilities) {
      window.caslAbilities = window.caslAbilities.filter(ability =>
        !TransportModuleMenu.some(menuItem =>
          ability.subject === menuItem.subject,
        ),
      )
    }
  }
}

// Auto-install function
export async function installTransportModule() {
  const installer = new TransportModuleInstaller()

  return await installer.install()
}

// Auto-uninstall function
export function uninstallTransportModule() {
  const installer = new TransportModuleInstaller()

  return installer.uninstall()
}

// Default export for plugin usage
export default {
  install: installTransportModule,
  uninstall: uninstallTransportModule,
  installer: TransportModuleInstaller,
}

// Auto-install on import (optional)
if (typeof window !== 'undefined' && window.autoInstallModules !== false) {
  installTransportModule().catch(error => {
    console.error('Failed to auto-install TransportModule:', error)
  })
}
