// Generated by DDD Module Generator on 2025-07-04

import { CreateConnectionHandler } from '../handlers/CreateConnectionHandler'
import type { CreateConnectionCommand } from '../commands/CreateConnectionCommand'
import type { ConnectionRepository } from '../../domain/contracts/repositories/ConnectionRepository'
import { ConnectionMapper } from '../mappers/ConnectionMapper'

export class CreateConnectionUseCase {
  private handler: CreateConnectionHandler

  constructor(
    connectionRepository: ConnectionRepository,
  ) {
    this.handler = new CreateConnectionHandler(
      connectionRepository,
      ConnectionMapper,
    )
  }

  async execute(request: CreateConnectionCommand) {
    return this.handler.execute(request)
  }
}
