// Generated by DDD Module Generator on 2025-07-04

import { DeleteConnectionHandler } from '../handlers/DeleteConnectionHandler'
import type { DeleteConnectionCommand } from '../commands/DeleteConnectionCommand'
import type { ConnectionRepository } from '../../domain/contracts/repositories/ConnectionRepository'
import { ConnectionMapper } from '../mappers/ConnectionMapper'

export class DeleteConnectionUseCase {
  private handler: DeleteConnectionHandler

  constructor(
    connectionRepository: ConnectionRepository,
  ) {
    this.handler = new DeleteConnectionHandler(
      connectionRepository,
      ConnectionMapper,
    )
  }

  async execute(request: DeleteConnectionCommand) {
    return this.handler.execute(request)
  }
}
