// Generated by DDD Module Generator on 2025-07-04

import { GetListConnectionHandler } from '../handlers/GetListConnectionHandler'
import type { GetListConnectionQuery } from '../querys/GetListConnectionQuery'
import type { ConnectionRepository } from '../../domain/contracts/repositories/ConnectionRepository'
import { ConnectionMapper } from '../mappers/ConnectionMapper'

export class GetListConnectionUseCase {
  private handler: GetListConnectionHandler

  constructor(
    connectionRepository: ConnectionRepository,
  ) {
    this.handler = new GetListConnectionHandler(
      connectionRepository,
      ConnectionMapper,
    )
  }

  async execute(request: GetListConnectionQuery) {
    return this.handler.execute(request)
  }
}
