// Generated by DDD Module Generator on 2025-07-04

import { UpdateConnectionHandler } from '../handlers/UpdateConnectionHandler'
import type { UpdateConnectionCommand } from '../commands/UpdateConnectionCommand'
import type { ConnectionRepository } from '../../domain/contracts/repositories/ConnectionRepository'
import { ConnectionMapper } from '../mappers/ConnectionMapper'

export class UpdateConnectionUseCase {
  private handler: UpdateConnectionHandler

  constructor(
    connectionRepository: ConnectionRepository,
  ) {
    this.handler = new UpdateConnectionHandler(
      connectionRepository,
      ConnectionMapper,
    )
  }

  async execute(request: UpdateConnectionCommand) {
    return this.handler.execute(request)
  }
}
