// Generated by DDD Module Generator on 2025-07-04

import type { DataSource } from '../../../domain/entities/DataSource'
import { DataSourceMapper } from '../../../application/mappers/DataSourceMapper'

export class DataSourceTransformer {
  static fromApi(apiData: any): DataSource | null {
    return DataSourceMapper.toDomain(apiData)
  }

  static toApi(dataSource: DataSource): any {
    return DataSourceMapper.toPersistence(dataSource)
  }

  static manyFromApi(apiDataArray: any[]): DataSource[] {
    return apiDataArray
      .map(apiData => this.fromApi(apiData))
      .filter(Boolean) as DataSource[]
  }
}
