// Generated by DDD Module Generator on 2025-07-04

import * as yup from 'yup'

export const executionCreateValidation = yup.object({
  report_id: yup.mixed().required('report_id is required'),
  export_format: yup.string().oneOf(['table', 'excel', 'pdf', 'csv', 'json']).required('export_format is required'),
  filters: yup.mixed(),
  status: yup.string().oneOf(['pending', 'running', 'completed', 'failed']),
  result_count: yup.number(),
  execution_time: yup.number(),
  error_message: yup.string(),
  download_url: yup.string(),
})

export const executionUpdateValidation = yup.object({
  report_id: yup.mixed(),
  export_format: yup.string().oneOf(['table', 'excel', 'pdf', 'csv', 'json']),
  filters: yup.mixed(),
  status: yup.string().oneOf(['pending', 'running', 'completed', 'failed']),
  result_count: yup.number(),
  execution_time: yup.number(),
  error_message: yup.string(),
  download_url: yup.string(),
})
