// Generated by DDD Module Generator on 2025-07-04

import type { DataSource } from '../entities/DataSource'

export interface Specification<T> {
  isSatisfiedBy(candidate: T): boolean
}

export class DataSourceIsActiveSpecification implements Specification<DataSource> {
  isSatisfiedBy(dataSource: DataSource): boolean {
    return dataSource.status === 'active'
  }
}
