// Generated by DDD Module Generator on 2025-07-04

import { DomainEvent } from '../../../shared/domain/base/DomainEvent'
import type { Connection } from '../entities/Connection'

export class ConnectionDeleted extends DomainEvent {
  public connection: Connection

  constructor(connection: Connection) {
    super(connection.id.toString())
    this.connection = connection
  }
}
