// Generated by DDD Module Generator on 2025-07-04

import type { ExecutionRepository } from '../../../domain/contracts/repositories/ExecutionRepository'
import type { Execution } from '../../../domain/entities/Execution'
import type { ExecutionId } from '../../../domain/valueObjects/ExecutionId'
import { ExecutionMapper } from '../../../application/mappers/ExecutionMapper'

export class ExecutionRepositoryImpl implements ExecutionRepository {
  private models = new Map<string, any>()

  async exists(executionId: ExecutionId): Promise<boolean> {
    return this.models.has(executionId.value)
  }

  async getExecutionById(executionId: ExecutionId): Promise<Execution> {
    const raw = this.models.get(executionId.value)
    if (!raw)
      return null

    return ExecutionMapper.toDomain(raw)
  }

  async save(execution: Execution): Promise<void> {
    const raw = ExecutionMapper.toPersistence(execution)

    this.models.set(execution.id.toString(), raw)
  }

  async delete(executionId: ExecutionId): Promise<void> {
    this.models.delete(executionId.value)
  }

  async getAll(): Promise<Execution[]> {
    const all = Array.from(this.models.values())

    return all.map(raw => ExecutionMapper.toDomain(raw)).filter(Boolean)
  }

  async getAllPaginated(page: number, limit: number): Promise<{
    executions: Execution[]
    totalPages: number
    total: number
  }> {
    const all = await this.getAll()
    const total = all.length
    const totalPages = Math.ceil(total / limit)
    const start = (page - 1) * limit
    const executions = all.slice(start, start + limit)

    return {
      executions,
      totalPages,
      total,
    }
  }
}
