// Generated by DDD Module Generator on 2025-07-04

import { CreateReportHandler } from '../handlers/CreateReportHandler'
import type { CreateReportCommand } from '../commands/CreateReportCommand'
import type { ReportRepository } from '../../domain/contracts/repositories/ReportRepository'
import { ReportMapper } from '../mappers/ReportMapper'

export class CreateReportUseCase {
  private handler: CreateReportHandler

  constructor(
    reportRepository: ReportRepository,
  ) {
    this.handler = new CreateReportHandler(
      reportRepository,
      ReportMapper,
    )
  }

  async execute(request: CreateReportCommand) {
    return this.handler.execute(request)
  }
}
