// Generated by DDD Module Generator on 2025-07-04

import { DeleteReportHandler } from '../handlers/DeleteReportHandler'
import type { DeleteReportCommand } from '../commands/DeleteReportCommand'
import type { ReportRepository } from '../../domain/contracts/repositories/ReportRepository'
import { ReportMapper } from '../mappers/ReportMapper'

export class DeleteReportUseCase {
  private handler: DeleteReportHandler

  constructor(
    reportRepository: ReportRepository,
  ) {
    this.handler = new DeleteReportHandler(
      reportRepository,
      ReportMapper,
    )
  }

  async execute(request: DeleteReportCommand) {
    return this.handler.execute(request)
  }
}
