// Generated by DDD Module Generator on 2025-07-04

import { GetByIdReportHandler } from '../handlers/GetByIdReportHandler'
import type { GetByIdReportQuery } from '../querys/GetByIdReportQuery'
import type { ReportRepository } from '../../domain/contracts/repositories/ReportRepository'
import { ReportMapper } from '../mappers/ReportMapper'

export class GetByIdReportUseCase {
  private handler: GetByIdReportHandler

  constructor(
    reportRepository: ReportRepository,
  ) {
    this.handler = new GetByIdReportHandler(
      reportRepository,
      ReportMapper,
    )
  }

  async execute(request: GetByIdReportQuery) {
    return this.handler.execute(request)
  }
}
