// Generated by DDD Module Generator on 2025-07-04

import { GetListReportHandler } from '../handlers/GetListReportHandler'
import type { GetListReportQuery } from '../querys/GetListReportQuery'
import type { ReportRepository } from '../../domain/contracts/repositories/ReportRepository'
import { ReportMapper } from '../mappers/ReportMapper'

export class GetListReportUseCase {
  private handler: GetListReportHandler

  constructor(
    reportRepository: ReportRepository,
  ) {
    this.handler = new GetListReportHandler(
      reportRepository,
      ReportMapper,
    )
  }

  async execute(request: GetListReportQuery) {
    return this.handler.execute(request)
  }
}
