// Generated by DDD Module Generator on 2025-07-04

import { UpdateReportHandler } from '../handlers/UpdateReportHandler'
import type { UpdateReportCommand } from '../commands/UpdateReportCommand'
import type { ReportRepository } from '../../domain/contracts/repositories/ReportRepository'
import { ReportMapper } from '../mappers/ReportMapper'

export class UpdateReportUseCase {
  private handler: UpdateReportHandler

  constructor(
    reportRepository: ReportRepository,
  ) {
    this.handler = new UpdateReportHandler(
      reportRepository,
      ReportMapper,
    )
  }

  async execute(request: UpdateReportCommand) {
    return this.handler.execute(request)
  }
}
