// Generated by DDD Module Generator on 2025-07-04

import { rawApi } from '@/services/api'
import type { ColumnInfoDto, ProcedureInfoDto, ProcedurePreviewDto, TableInfoDto, TestConnectionDto, TestConnectionResponseDto, TestQueryDto, TestQueryResponseDto } from '../../application/dtos/ConnectionDtos'

export class ConnectionApiService {
  private readonly baseUrl = '/dynamic-reports/connections'

  async create(data: any) {
    return await rawApi(this.baseUrl, { method: 'POST', body: data })
  }

  async update(id: string, data: any) {
    return await rawApi(`${this.baseUrl}/${id}`, { method: 'PUT', body: data })
  }

  async delete(id: string) {
    return await rawApi(`${this.baseUrl}/${id}`, { method: 'DELETE' })
  }

  async getById(id: string) {
    return await rawApi(`${this.baseUrl}/${id}`, { method: 'GET' })
  }

  async getAll() {
    return await rawApi(this.baseUrl, { method: 'GET' })
  }

  async getList(params: any) {
    return await rawApi(this.baseUrl, { method: 'GET', params })
  }

  // Test connection before save (nuevo endpoint)
  async testConnectionBeforeSave(data: TestConnectionDto): Promise<TestConnectionResponseDto> {
    return await rawApi(`${this.baseUrl}/test-before-save`, { method: 'POST', body: data })
  }

  // Test existing connection
  async testConnection(id: string) {
    return await rawApi(`${this.baseUrl}/${id}/test`, { method: 'POST' })
  }

  // Obtener tablas y vistas de una conexión
  async getTablesAndViews(connectionId: string): Promise<{ success: boolean; data: TableInfoDto[] }> {
    return await rawApi(`${this.baseUrl}/${connectionId}/tables`, { method: 'GET' })
  }

  // Obtener procedimientos almacenados de una conexión
  async getProcedures(connectionId: string): Promise<{ success: boolean; data: ProcedureInfoDto[] }> {
    return await rawApi(`${this.baseUrl}/${connectionId}/procedures`, { method: 'GET' })
  }

  // Obtener columnas de una tabla/vista/procedimiento
  async getColumns(connectionId: string, params: { table?: string; procedure?: string }): Promise<{ success: boolean; data: ColumnInfoDto[] }> {
    return await rawApi(`${this.baseUrl}/${connectionId}/columns`, { method: 'GET', params })
  }

  // Obtener preview de columnas de un stored procedure
  async getProcedurePreview(connectionId: string, data: ProcedurePreviewDto): Promise<{ success: boolean; data: any }> {
    return await rawApi(`${this.baseUrl}/${connectionId}/procedure-preview`, {
      method: 'POST',
      body: data,
    })
  }

  // Probar consulta SQL
  async testQuery(connectionId: string, data: TestQueryDto): Promise<TestQueryResponseDto> {
    return await rawApi(`${this.baseUrl}/${connectionId}/test-query`, { method: 'POST', body: data })
  }

  // Health check del módulo
  async healthCheck() {
    return await rawApi('/dynamic-reports/health', { method: 'GET' })
  }
}
