// Generated by DDD Module Generator on 2025-07-04

import type { Execution } from '../entities/Execution'

export interface Specification<T> {
  isSatisfiedBy(candidate: T): boolean
}

export class ExecutionIsActiveSpecification implements Specification<Execution> {
  isSatisfiedBy(execution: Execution): boolean {
    return execution.status === 'active'
  }
}
