// Generated by DDD Module Generator on 2025-07-04

import type { CreateExecutionCommand } from '../commands/CreateExecutionCommand'
import type { ExecutionRepository } from '../../domain/contracts/repositories/ExecutionRepository'
import { Execution } from '../../domain/entities/Execution'
import type { ExecutionMapper } from '../mappers/ExecutionMapper'
import { Result } from '../../../shared/domain/base/Result'
import type { ExecutionResponseDto } from '../dtos/ExecutionDtos'

export class CreateExecutionHandler {
  private executionRepository: ExecutionRepository
  private mapper: ExecutionMapper

  constructor(
    executionRepository: ExecutionRepository,
    mapper: ExecutionMapper,
  ) {
    this.executionRepository = executionRepository
    this.mapper = mapper
  }

  async execute(command: CreateExecutionCommand): Promise<Result<ExecutionResponseDto>> {
    try {
      const executionOrError = Execution.create({
        ...command,
        createdAt: new Date(),
        updatedAt: new Date(),
      })

      if (executionOrError.isFailure)
        return Result.fail<ExecutionResponseDto>(executionOrError.error)

      const execution = executionOrError.getValue()

      await this.executionRepository.save(execution)

      return Result.ok<ExecutionResponseDto>(
        this.mapper.toDto(execution),
      )
    }
    catch (err) {
      return Result.fail<ExecutionResponseDto>(`Unexpected error creating Execution: ${err}`)
    }
  }
}
