// Generated by DDD Module Generator on 2025-07-04

import type { DeleteExecutionCommand } from '../commands/DeleteExecutionCommand'
import type { ExecutionRepository } from '../../domain/contracts/repositories/ExecutionRepository'
import { ExecutionId } from '../../domain/valueObjects/ExecutionId'
import { Result } from '../../../shared/domain/base/Result'
import { ExecutionNotFound } from '../../domain/exceptions/ExecutionNotFound'

export class DeleteExecutionHandler {
  private executionRepository: ExecutionRepository

  constructor(executionRepository: ExecutionRepository) {
    this.executionRepository = executionRepository
  }

  async execute(command: DeleteExecutionCommand): Promise<Result<void>> {
    try {
      const executionId = ExecutionId.create(command.id)
      const exists = await this.executionRepository.exists(executionId)

      if (!exists)
        return Result.fail<void>(new ExecutionNotFound().message)

      await this.executionRepository.delete(executionId)

      return Result.ok<void>()
    }
    catch (err) {
      return Result.fail<void>(`Unexpected error deleting Execution: ${err}`)
    }
  }
}
