// Generated by DDD Module Generator on 2025-07-04

import type { GetExecutionListQuery } from '../queries/GetExecutionListQuery'
import type { ExecutionRepository } from '../../domain/contracts/repositories/ExecutionRepository'
import type { ExecutionMapper } from '../mappers/ExecutionMapper'
import { Result } from '../../../shared/domain/base/Result'
import type { ExecutionResponseDto } from '../dtos/ExecutionDtos'

export class GetExecutionListHandler {
  private executionRepository: ExecutionRepository
  private mapper: ExecutionMapper

  constructor(
    executionRepository: ExecutionRepository,
    mapper: ExecutionMapper,
  ) {
    this.executionRepository = executionRepository
    this.mapper = mapper
  }

  async execute(query: GetExecutionListQuery): Promise<Result<{
    items: ExecutionResponseDto[]
    total: number
    totalPages: number
    page: number
    limit: number
  }>> {
    try {
      const page = query.page || 1
      const limit = query.limit || 20

      const result = await this.executionRepository.getAllPaginated(page, limit)

      return Result.ok({
        items: result.executions.map(execution => this.mapper.toDto(execution)),
        total: result.total,
        totalPages: result.totalPages,
        page,
        limit,
      })
    }
    catch (err) {
      return Result.fail(`Unexpected error getting Execution list: ${err}`)
    }
  }
}
