// Generated by DDD Module Generator on 2025-07-04

import type { GetExecutionByIdQuery } from '../queries/GetExecutionByIdQuery'
import type { ExecutionRepository } from '../../domain/contracts/repositories/ExecutionRepository'
import { ExecutionId } from '../../domain/valueObjects/ExecutionId'
import type { ExecutionMapper } from '../mappers/ExecutionMapper'
import { Result } from '../../../shared/domain/base/Result'
import type { ExecutionResponseDto } from '../dtos/ExecutionDtos'
import { ExecutionNotFound } from '../../domain/exceptions/ExecutionNotFound'

export class GetExecutionByIdHandler {
  private executionRepository: ExecutionRepository
  private mapper: ExecutionMapper

  constructor(
    executionRepository: ExecutionRepository,
    mapper: ExecutionMapper,
  ) {
    this.executionRepository = executionRepository
    this.mapper = mapper
  }

  async execute(query: GetExecutionByIdQuery): Promise<Result<ExecutionResponseDto>> {
    try {
      const executionId = ExecutionId.create(query.id)
      const execution = await this.executionRepository.getExecutionById(executionId)

      if (!execution)
        return Result.fail<ExecutionResponseDto>(new ExecutionNotFound().message)

      return Result.ok<ExecutionResponseDto>(
        this.mapper.toDto(execution),
      )
    }
    catch (err) {
      return Result.fail<ExecutionResponseDto>(`Unexpected error getting Execution: ${err}`)
    }
  }
}
