// Generated by DDD Module Generator on 2025-07-04

import type { UpdateExecutionCommand } from '../commands/UpdateExecutionCommand'
import type { ExecutionRepository } from '../../domain/contracts/repositories/ExecutionRepository'
import { ExecutionId } from '../../domain/valueObjects/ExecutionId'
import type { ExecutionMapper } from '../mappers/ExecutionMapper'
import { Result } from '../../../shared/domain/base/Result'
import type { ExecutionResponseDto } from '../dtos/ExecutionDtos'
import { ExecutionNotFound } from '../../domain/exceptions/ExecutionNotFound'

export class UpdateExecutionHandler {
  private executionRepository: ExecutionRepository
  private mapper: ExecutionMapper

  constructor(
    executionRepository: ExecutionRepository,
    mapper: ExecutionMapper,
  ) {
    this.executionRepository = executionRepository
    this.mapper = mapper
  }

  async execute(command: UpdateExecutionCommand): Promise<Result<ExecutionResponseDto>> {
    try {
      const executionId = ExecutionId.create(command.id)
      const execution = await this.executionRepository.getExecutionById(executionId)

      if (!execution)
        return Result.fail<ExecutionResponseDto>(new ExecutionNotFound().message)

      const { id, ...updateData } = command
      const updateResult = execution.update(updateData)

      if (updateResult.isFailure)
        return Result.fail<ExecutionResponseDto>(updateResult.error)

      await this.executionRepository.save(execution)

      return Result.ok<ExecutionResponseDto>(
        this.mapper.toDto(execution),
      )
    }
    catch (err) {
      return Result.fail<ExecutionResponseDto>(`Unexpected error updating Execution: ${err}`)
    }
  }
}
