// Generated by DDD Module Generator on 2025-07-04

import type { Report } from '../../../domain/entities/Report'
import { ReportMapper } from '../../../application/mappers/ReportMapper'

export class ReportTransformer {
  static fromApi(apiData: any): Report | null {
    return ReportMapper.toDomain(apiData)
  }

  static toApi(report: Report): any {
    return ReportMapper.toPersistence(report)
  }

  static manyFromApi(apiDataArray: any[]): Report[] {
    return apiDataArray
      .map(apiData => this.fromApi(apiData))
      .filter(Boolean) as Report[]
  }
}
