// Generated by DDD Module Generator on 2025-07-04

export interface CreateDataSourceCommand {
  name: string
  type: 'custom_sql' | 'visual_builder' | 'hybrid'
  description?: string
  connection_id: string
  custom_sql?: string
  available_fields: Record<string, any>
  is_active?: boolean
  created_at?: Date
  updated_at?: Date
}
