// Generated by DDD Module Generator on 2025-07-04

export interface UpdateDataSourceCommand {
  id: string
  connection_id: string
  name: string
  type: 'custom_sql' | 'visual_builder' | 'hybrid'
  custom_sql?: string
  available_fields: Record<string, any>
}
