// Generated by DDD Module Generator on 2025-07-04

import { DataSource } from '../../domain/entities/DataSource'
import { DataSourceResponseDto } from '../dtos/DataSourceDtos'
import { UniqueEntityID } from '../../../shared/domain/base/UniqueEntityID'

export class DataSourceMapper {
  public static toDto(dataSource: DataSource): DataSourceResponseDto {
    return {
      id: dataSource.id.toString(),
      connection_id: dataSource.props.connection_id,
      name: dataSource.props.name,
      type: dataSource.props.type,
      custom_sql: dataSource.props.custom_sql,
      available_fields: dataSource.props.available_fields,
      created_at: dataSource.props.created_at,
      updated_at: dataSource.props.updated_at,,
      createdAt: dataSource.props.createdAt,
      updatedAt: dataSource.props.updatedAt
    }
  }

  public static toDomain(raw: any): DataSource {
    const dataSourceOrError = DataSource.create(
      {
        connection_id: raw.connection_id,
        name: raw.name,
        type: raw.type,
        custom_sql: raw.custom_sql,
        available_fields: raw.available_fields,
        created_at: raw.created_at,
        updated_at: raw.updated_at,,
        createdAt: raw.created_at ? new Date(raw.created_at) : new Date(),
        updatedAt: raw.updated_at ? new Date(raw.updated_at) : new Date()
      },
      new UniqueEntityID(raw.id)
    )

    return dataSourceOrError.isSuccess 
      ? dataSourceOrError.getValue() 
      : null
  }

  public static toPersistence(dataSource: DataSource): any {
    return {
      id: dataSource.id.toString(),
      connection_id: dataSource.props.connection_id,
      name: dataSource.props.name,
      type: dataSource.props.type,
      custom_sql: dataSource.props.custom_sql,
      available_fields: dataSource.props.available_fields,
      created_at: dataSource.props.created_at,
      updated_at: dataSource.props.updated_at,,
      created_at: dataSource.props.createdAt,
      updated_at: dataSource.props.updatedAt
    }
  }
}
