// Generated by DDD Module Generator on 2025-07-04

import { Entity } from './Entity'
import type { DomainEvent } from './DomainEvent'
import type { UniqueEntityID } from './UniqueEntityID'

export abstract class AggregateRoot<T> extends Entity<T> {
  private _domainEvents: DomainEvent[] = []

  get id(): UniqueEntityID {
    return this._id
  }

  get domainEvents(): DomainEvent[] {
    return this._domainEvents
  }

  protected addDomainEvent(domainEvent: DomainEvent): void {
    this._domainEvents.push(domainEvent)
    this.markModified()
  }

  public clearEvents(): void {
    this._domainEvents = []
  }

  private markModified(): void {
    // Mark aggregate as modified
  }
}
