// Generated by DDD Module Generator on 2025-07-04

export interface IDomainEvent {
  dateTimeOccurred: Date
  getAggregateId(): string
}

export abstract class DomainEvent implements IDomainEvent {
  public dateTimeOccurred: Date
  public aggregateId: string

  constructor(aggregateId: string) {
    this.dateTimeOccurred = new Date()
    this.aggregateId = aggregateId
  }

  getAggregateId(): string {
    return this.aggregateId
  }
}
