// Generated by DDD Module Generator on 2025-07-04

export class DataSourceNotFound extends Error {
  constructor(message: string = 'DataSource not found') {
    super(message)
    this.name = 'DataSourceNotFound'
  }
}
