// Generated by DDD Module Generator on 2025-07-04

export class DataSourceValidationError extends Error {
  constructor(message: string = 'DataSource validation failed') {
    super(message)
    this.name = 'DataSourceValidationError'
  }
}
