// Generated by DDD Module Generator on 2025-07-04

export class DataSourceAlreadyExists extends Error {
  constructor(message: string = 'DataSource already exists') {
    super(message)
    this.name = 'DataSourceAlreadyExists'
  }
}
