<!-- Generated by DDD Module Generator on 2025-07-04 -->
<script setup lang="ts">
import { computed, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import { useExecutionStore } from '../stores/executionStore'
import ExecutionForm from '../components/organisms/ExecutionForm.vue'

const route = useRoute()
const store = useExecutionStore()
const currentItem = computed(() => store.currentItem)

onMounted(async () => {
  await store.fetchById(route.params.id as string)
})
</script>

<template>
  <ExecutionForm
    mode="edit"
    :initial-data="currentItem"
  />
</template>
