<!-- Generated by DDD Module Generator on 2025-07-04 -->
<script setup lang="ts">
import debounce from 'lodash/debounce'
import { useI18n } from 'vue-i18n'
import { useExecutionStore } from '../stores/executionStore'

// Componentes internos
import ExecutionTable from '../components/organisms/ExecutionTable.vue'
import ExecutionAdd from './ExecutionAdd.vue'
import ExecutionDelete from './ExecutionDelete.vue'
import ExecutionEdit from './ExecutionEdit.vue'

// Composable para manejar diálogos
const { openDialog, navigateTo } = useAppManager()
const { t } = useI18n()

// Store
const executionStore = useExecutionStore()

// Headers para la tabla
const headers = [
  { title: t('execution.name'), key: 'name' },
  { title: t('execution.description'), key: 'description' },
  { title: t('execution.status'), key: 'status' },
  { title: t('actions'), key: 'actions', sortable: false },
]

// Opciones del menú de exportación
const menuOptions = [
  {
    text: `${t('export_to')} ${t('excel')}`,
    icon: 'tabler-file-spreadsheet',
    action: () => exportItems('excel'),
  },
  {
    text: `${t('export_to')} ${t('pdf')}`,
    icon: 'tabler-file-type-pdf',
    action: () => exportItems('pdf'),
  },
]

// Métodos
const debouncedFetchList = debounce(() => {
  executionStore.fetchList()
}, 500)

function applyFilters() {
  debouncedFetchList()
}

function onPageChange(newPage: number) {
  executionStore.page = newPage
  executionStore.fetchList()
}

function onItemsPerPageChange(newItemsPerPage: number) {
  executionStore.itemsPerPage = newItemsPerPage
  executionStore.fetchList()
}

function deleteSelected() {
  openDialog(ExecutionDelete, {}, { width: '900px', persistent: true }).then(result => {
    if (result === 'submit')
      executionStore.fetchList()
  })
}

function openAddDialog() {
  openDialog(ExecutionAdd, { title: t('add Execution') }, { width: '900px', persistent: true }).then(result => {
    if (result === 'submit')
      executionStore.fetchList()
  })
}

function openEditDialog(item: any) {
  openDialog(ExecutionEdit, { item, title: t('edit Execution') }, { width: '800px', persistent: true }).then(result => {
    if (result === 'submit')
      executionStore.fetchList()
  })
}

function openViewDialog(item: any) {
  navigateTo(`/executions/${item.id}`)
}

function openDeleteDialog(item: any) {
  openDialog(ExecutionDelete, { item, title: t('delete Execution') }, { width: '900px', persistent: true }).then(result => {
    if (result === 'submit')
      executionStore.fetchList()
  })
}

function exportItems(type: string) {
  executionStore.exportItems(type)
}

// onMounted
onMounted(() => {
  executionStore.fetchList()
})
</script>

<template>
  <VCard>
    <VCardTitle>
      <h4 class="text-h4 mb-1">
        execution.title
      </h4>
      <p class="text-body-1 mb-4">
        execution.description
      </p>
    </VCardTitle>

    <VCardText>
      <div class="d-flex align-center flex-wrap gap-4 justify-end">
        <!-- Campo de búsqueda -->
        <VTextField
          v-model="executionStore.filters.search"
          label="execution.search_execution"
          variant="outlined"
          dense
          class="filter-field"
          @input="applyFilters"
        />

        <!-- Botón para exportar -->
        <GlobalMenu
          label="export"
          :options="menuOptions"
          color="secondary"
          variant="tonal"
          icon="tabler-chevron-down"
        />

        <!-- Botón para agregar -->
        <VBtn
          prepend-icon="tabler-plus"
          color="primary"
          @click="openAddDialog"
        >
          { ('execution.add execution') }
        </VBtn>

        <!-- Botones para acciones con seleccionados -->
        <VBtn
          v-if="executionStore.selectedItems.length > 1"
          color="error"
          @click="deleteSelected"
        >
          { ('delete selected') }
        </VBtn>
      </div>
    </VCardText>

    <VDivider />

    <!-- Tabla de elementos -->
    <ExecutionTable
      :headers="headers"
      :items="executionStore.list"
      :total="executionStore.total"
      :page="executionStore.page"
      :items-per-page="executionStore.itemsPerPage"
      :loading="executionStore.isLoading"
      :selection="executionStore.selectedItems"
      @update:selection="val => executionStore.selectedItems = val"
      @update:page="onPageChange"
      @update:items-per-page="onItemsPerPageChange"
      @view="openViewDialog"
      @edit="openEditDialog"
      @delete="openDeleteDialog"
    />
  </VCard>
</template>

<style scoped>
.filter-field {
  flex: 1;
  max-inline-size: 300px;
}
</style>
