// Generated by DDD Module Generator

import { rawApi } from '@/services/api'

export class ConcessionApiService {
  private readonly baseUrl = '/transport/concessions'

  async create(data: any) {
    return await rawApi(this.baseUrl, { method: 'POST', body: data })
  }

  async update(id: string, data: any) {
    return await rawApi(`${this.baseUrl}/${id}`, { method: 'PUT', body: data })
  }

  async delete(id: string) {
    return await rawApi(`${this.baseUrl}/${id}`, { method: 'DELETE' })
  }

  async getById(id: string) {
    return await rawApi(`${this.baseUrl}/${id}`, { method: 'GET' })
  }

  async getAll() {
    return await rawApi(this.baseUrl, { method: 'GET' })
  }

  async getList(params: any) {
    return await rawApi(this.baseUrl, { method: 'GET', params })
  }

  // Concession specific methods
  async renewConcession(id: string, data: any) {
    return await rawApi(`${this.baseUrl}/${id}/renew`, { method: 'POST', body: data })
  }

  async getConcessionStats() {
    return await rawApi(`${this.baseUrl}/stats`, { method: 'GET' })
  }

  async getExpiringConcessions(params: any) {
    return await rawApi(`${this.baseUrl}/expiring`, { method: 'GET', params })
  }

  async exportConcessions(params: any) {
    return await rawApi(`${this.baseUrl}/export`, { method: 'GET', params })
  }

  async getValidValues() {
    return await rawApi(`${this.baseUrl}/valid-values`, { method: 'GET' })
  }

  // Additional methods needed by repository
  async findByConcessionNumber(concessionNumber: string) {
    return await rawApi(`${this.baseUrl}/by-number/${concessionNumber}`, { method: 'GET' })
  }

  async findByHolderId(holderId: string, params?: any) {
    return await rawApi(`${this.baseUrl}/holder/${holderId}`, { method: 'GET', params })
  }

  async findExpiringConcessions(days?: number) {
    const params = days ? { days } : {}

    return await rawApi(`${this.baseUrl}/expiring`, { method: 'GET', params })
  }

  async findByServiceArea(serviceArea: string) {
    return await rawApi(`${this.baseUrl}/by-service-area`, { method: 'GET', params: { service_area: serviceArea } })
  }

  async getStatistics() {
    return await rawApi(`${this.baseUrl}/statistics`, { method: 'GET' })
  }

  async isConcessionNumberAvailable(concessionNumber: string, excludeId?: string) {
    const params = excludeId ? { exclude_id: excludeId } : {}
    const response = await rawApi(`${this.baseUrl}/check-number/${concessionNumber}`, { method: 'GET', params })

    return response.available
  }

  async export(filter?: any, format?: string) {
    const params = { ...filter, format }

    return await rawApi(`${this.baseUrl}/export`, { method: 'GET', params })
  }

  // Verification
  async verifyConcession(id: string, data: { verification_notes?: string }) {
    // Backend expects: POST /api/transport/concessions/{id}/verify
    // rawApi will prepend base URL if configured
    return await rawApi(`${this.baseUrl}/${id}/verify`, { method: 'POST', body: { verification_notes: data?.verification_notes || '' } })
  }

  // Suspension
  async suspendConcession(id: string, data: { suspension_reason: string; suspension_notes?: string; suspension_duration_days?: number }) {
    return await rawApi(`${this.baseUrl}/${id}/suspend`, {
      method: 'POST',
      body: {
        suspension_reason: data.suspension_reason,
        suspension_notes: data?.suspension_notes,
        suspension_duration_days: data?.suspension_duration_days,
      },
    })
  }
}
