// Generated by DDD Module Generator

import { rawApi } from '@/services/api'

export class ConcessionApiService {
  private readonly baseUrl = '/transport/concessions'

  async create(data: any) {
    return await rawApi(this.baseUrl, { method: 'POST', body: data })
  }

  async update(id: string, data: any) {
    return await rawApi(`${this.baseUrl}/${id}`, { method: 'PUT', body: data })
  }

  async delete(id: string) {
    return await rawApi(`${this.baseUrl}/${id}`, { method: 'DELETE' })
  }

  async getById(id: string) {
    return await rawApi(`${this.baseUrl}/${id}`, { method: 'GET' })
  }

  async getAll() {
    return await rawApi(this.baseUrl, { method: 'GET' })
  }

  async getList(params: any) {
    return await rawApi(this.baseUrl, { method: 'GET', params })
  }

  // Concession specific methods
  async renewConcession(id: string, data: any) {
    return await rawApi(`${this.baseUrl}/${id}/renew`, { method: 'POST', body: data })
  }

  async getConcessionStats() {
    return await rawApi(`${this.baseUrl}/stats`, { method: 'GET' })
  }

  async getExpiringConcessions(params: any) {
    return await rawApi(`${this.baseUrl}/expiring`, { method: 'GET', params })
  }

  async exportConcessions(params: any) {
    return await rawApi(`${this.baseUrl}/export`, { method: 'GET', params })
  }
}
