// Generated by DDD Module Generator on 2025-07-04

import { defineStore } from 'pinia'
import { computed, ref } from 'vue'
import { ReportApiService } from '../../infrastructure/api/services/ReportApiService'
import { ReportDataTransformer } from '../../infrastructure/transformers/ReportDataTransformer'
import type { ListFilters } from '../../../shared/types'

export const useReportStore = defineStore('report', () => {
  // State
  const items = ref<any[]>([])
  const currentItem = ref<any>(null)
  const loading = ref(false)
  const error = ref<string | null>(null)

  // Report execution state
  const reportData = ref<any[]>([])
  const reportTotalRecords = ref(0)
  const reportLoading = ref(false)
  const reportError = ref<string | null>(null)

  // Pagination
  const page = ref(1)
  const itemsPerPage = ref(20)
  const total = ref(0)
  const totalPages = ref(0)

  // Filters
  const filters = ref<ListFilters>({})

  // Selection
  const selectedItems = ref<any[]>([])

  // Computed
  const currentPage = computed(() => page.value)
  const perPage = computed(() => itemsPerPage.value)

  // API Service
  const apiService = new ReportApiService()

  // Actions
  const fetchList = async () => {
    loading.value = true
    error.value = null

    try {
      const response = await apiService.getList({
        page: page.value,
        limit: itemsPerPage.value,
        ...filters.value,
      })

      items.value = response.data
      total.value = response.pagination.total
      totalPages.value = response.pagination.total_pages
    }
    catch (err) {
      error.value = err instanceof Error ? err.message : 'Failed to fetch reports'
    }
    finally {
      loading.value = false
    }
  }

  const fetchById = async (id: string) => {
    loading.value = true
    error.value = null

    try {
      const response = await apiService.getById(id)
      const backendData = response.metadata

      if (backendData) {
        const transformedData = ReportDataTransformer.fromBackendToWizard(backendData)

        const saveData = {
          wizardData: transformedData,
          currentStep: 0,
          isEditing: true,
          reportId: id,
          timestamp: new Date().toISOString(),
        }

        localStorage.setItem('reportWizardProgress', JSON.stringify(saveData))
        currentItem.value = null // opcional: limpiar currentItem
      }
      else {
        currentItem.value = null
      }
    }
    catch (err) {
      error.value = err instanceof Error ? err.message : 'Failed to fetch report'
    }
    finally {
      loading.value = false
    }
  }

  const executeReport = async (payload: any) => {
    reportLoading.value = true
    reportError.value = null

    try {
      const response = await apiService.executeReport(payload)

      // Solo los datos
      reportData.value = response.data || []

      // Total real del backend
      reportTotalRecords.value = response.meta?.total_records ?? response.data?.length ?? 0

      // Actualiza paginación local con la del backend
      if (response.pagination) {
        page.value = response.pagination.page || 1
        itemsPerPage.value = response.pagination.per_page || 50
        totalPages.value = response.pagination.total_pages || 1
        total.value = response.pagination.total || reportTotalRecords.value
      }

      return response
    }
    catch (err) {
      reportError.value = err instanceof Error ? err.message : 'Error al cargar los datos del reporte'
      throw err
    }
    finally {
      reportLoading.value = false
    }
  }

  const createItem = async (data: any) => {
    loading.value = true
    error.value = null

    try {
      const response = await apiService.create(data)

      await fetchList()

      return response.data
    }
    catch (err) {
      error.value = err instanceof Error ? err.message : 'Failed to create report'
      throw err
    }
    finally {
      loading.value = false
    }
  }

  const updateItem = async (id: string, data: any) => {
    loading.value = true
    error.value = null

    try {
      const response = await apiService.update(id, data)

      await fetchList()

      return response.data
    }
    catch (err) {
      error.value = err instanceof Error ? err.message : 'Failed to update report'
      throw err
    }
    finally {
      loading.value = false
    }
  }

  const deleteItem = async (id: string) => {
    loading.value = true
    error.value = null

    try {
      await apiService.delete(id)
      await fetchList()
    }
    catch (err) {
      error.value = err instanceof Error ? err.message : 'Failed to delete report'
      throw err
    }
    finally {
      loading.value = false
    }
  }

  const setPage = (newPage: number) => {
    page.value = newPage
  }

  const clearError = () => {
    error.value = null
  }

  const exportItems = (type: string) => {
    // TODO: Implement export functionality
    console.log('Exporting reports as', type)
  }

  return {
    // State
    items,
    currentItem,
    loading,
    error,

    // Report execution state
    reportData,
    reportTotalRecords,
    reportLoading,
    reportError,

    // Pagination
    page,
    itemsPerPage,
    total,
    totalPages,
    currentPage,
    perPage,

    // Filters
    filters,

    // Selection
    selectedItems,

    // Actions
    fetchList,
    fetchById,
    executeReport,
    createItem,
    updateItem,
    deleteItem,
    setPage,
    clearError,
    exportItems,
  }
})
