// Generated by DDD Module Generator on 2025-09-11

import type { Fine } from '../../../domain/entities/Fine'
import { FineMapper } from '../../../application/mappers/FineMapper'

export class FineTransformer {
  static fromApi(apiData: any): Fine | null {
    return FineMapper.toDomain(apiData)
  }

  static toApi(fine: Fine): any {
    return FineMapper.toPersistence(fine)
  }

  static manyFromApi(apiDataArray: any[]): Fine[] {
    return apiDataArray
      .map(apiData => this.fromApi(apiData))
      .filter(Boolean) as Fine[]
  }
}
