// Generated by DDD Module Generator on 2025-07-04

import { AggregateRoot } from '../../../shared/domain/base/AggregateRoot'
import type { UniqueEntityID } from '../../../shared/domain/base/UniqueEntityID'
import { Result } from '../../../shared/domain/base/Result'
import { Guard } from '../../../shared/domain/base/Guard'
import { ReportId } from '../valueObjects/ReportId'
import { ReportCreated } from '../events/ReportCreated'
import { ReportUpdated } from '../events/ReportUpdated'
import { ReportDeleted } from '../events/ReportDeleted'

export interface ReportProps {
  id?: string
  data_source_id: string
  name: string
  description?: string
  selected_fields: Record<string, any>
  export_formats: Record<string, any>
  default_filters?: Record<string, any>
  is_public?: boolean
  created_at?: Date
  updated_at?: Date

  // Menu configuration
  menu_config?: {
    show_in_menu: boolean
    menu_title?: string
    menu_icon?: string
    menu_category?: string
    menu_order?: number
    menu_permissions?: {
      action: string
      subject: string
    }
    menu_badge?: {
      content: string
      class: string
    }
  }
}

export class Report extends AggregateRoot<ReportProps> {
  private constructor(props: ReportProps, id?: UniqueEntityID) {
    super(props, id)
  }

  get reportId(): ReportId {
    return ReportId.create(this.id)
  }

  public static create(props: ReportProps, id?: UniqueEntityID): Result<Report> {
    const guardResult = Guard.againstNullOrUndefinedBulk([
      { argument: props.data_source_id, argumentName: 'data_source_id' },
      { argument: props.name, argumentName: 'name' },
      { argument: props.selected_fields, argumentName: 'selected_fields' },
      { argument: props.export_formats, argumentName: 'export_formats' },
    ])

    if (!guardResult.succeeded)
      return Result.fail<Report>(guardResult.message)

    const report = new Report({
      ...props,
      createdAt: props.createdAt || new Date(),
      updatedAt: props.updatedAt || new Date(),
    }, id)

    const isNew = !id
    if (isNew)
      report.addDomainEvent(new ReportCreated(report))

    return Result.ok<Report>(report)
  }

  public update(props: Partial<ReportProps>): Result<void> {
    const guardResult = Guard.againstNullOrUndefined(props, 'props')

    if (!guardResult.succeeded)
      return Result.fail<void>(guardResult.message)

    this.props.updatedAt = new Date()
    Object.assign(this.props, props)

    this.addDomainEvent(new ReportUpdated(this))

    return Result.ok<void>()
  }

  public delete(): Result<void> {
    this.addDomainEvent(new ReportDeleted(this))

    return Result.ok<void>()
  }

  // Getters
  get id(): string {
    return this.props.id
  }

  get data_source_id(): string {
    return this.props.data_source_id
  }

  get name(): string {
    return this.props.name
  }

  get description(): string {
    return this.props.description
  }

  get selected_fields(): Record<string, any> {
    return this.props.selected_fields
  }

  get export_formats(): Record<string, any> {
    return this.props.export_formats
  }

  get default_filters(): Record<string, any> {
    return this.props.default_filters
  }

  get is_public(): boolean {
    return this.props.is_public
  }

  get created_at(): Date {
    return this.props.created_at
  }

  get updated_at(): Date {
    return this.props.updated_at
  }

  // Menu configuration getters
  get menu_config(): any {
    return this.props.menu_config
  }

  get show_in_menu(): boolean {
    return this.props.menu_config?.show_in_menu || false
  }

  get menu_title(): string {
    return this.props.menu_config?.menu_title || this.props.name
  }

  get menu_icon(): string {
    return this.props.menu_config?.menu_icon || 'tabler-chart-bar'
  }

  get menu_category(): string {
    return this.props.menu_config?.menu_category || 'Reports'
  }

  get menu_order(): number {
    return this.props.menu_config?.menu_order || 0
  }

  get menu_permissions(): any {
    return this.props.menu_config?.menu_permissions || { action: 'read', subject: 'Report' }
  }

  get menu_badge(): any {
    return this.props.menu_config?.menu_badge
  }

  // Business Methods
  addExecution(item: any): Result<void> {
    // Business logic for adding Execution
    return Result.ok<void>()
  }

  // Menu generation method
  generateMenuConfig(): any {
    if (!this.show_in_menu)
      return null

    return {
      title: this.menu_title,
      icon: { icon: this.menu_icon },
      to: { name: 'reports-viewer-id', params: { id: this.id } },
      action: this.menu_permissions.action,
      subject: this.menu_permissions.subject,
      badge: this.menu_badge,
    }
  }
}
