// Generated by DDD Module Generator on 2025-07-04

import { defineStore } from 'pinia'
import { ref } from 'vue'

export const useModuleStore = defineStore('module', () => {{
  const notifications = ref<any[]>([])
  
  const addNotification = (notification: any) => {{
    notifications.value.push({
      id: Date.now(),
      ...notification
    })
  }}
  
  const removeNotification = (id: number) => {{
    const index = notifications.value.findIndex(n => n.id === id)
    if (index > -1) {
      notifications.value.splice(index, 1)
    }
  }}
  
  const clearNotifications = () => {{
    notifications.value = []
  }}
  
  return {{
    notifications,
    addNotification,
    removeNotification,
    clearNotifications
  }}
}})
