// Generated by DDD Module Generator on 2025-09-10

export const TransportModuleConfig = {
  name: 'TransportModule',
  version: '1.0.0',
  description: 'Transport Management Module with DDD Architecture',
  author: 'Transport Module Generator',

  // Module settings
  settings: {
    enableCache: true,
    cacheTimeout: 300000, // 5 minutes
    enableOfflineMode: true,
    maxFileSize: 50 * 1024 * 1024, // 50MB
    supportedFileTypes: [
      'image/jpeg',
      'image/png',
      'image/gif',
      'application/pdf',
      'application/msword',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    ],
  },

  // API configuration
  api: {
    baseUrl: '/api/transport',
    timeout: 30000,
    retries: 3,
    endpoints: {
      vehicles: '/vehicles',
      drivers: '/drivers',
      concessions: '/concessions',
      concessionHolders: '/concession-holders',
      fines: '/fines',
      documents: '/documents',
      statistics: '/statistics',
    },
  },

  // UI configuration
  ui: {
    defaultPageSize: 20,
    maxPageSize: 100,
    showActionsColumn: true,
    enableExport: true,
    enableImport: true,
    dateFormat: 'DD/MM/YYYY',
    timeFormat: 'HH:mm:ss',
    currency: 'MXN',
    locale: 'es-MX',
  },

  // Numbering configuration
  numbering: {
    concession: {
      // Pattern tokens supported:
      // {YYYY} {YY} {MM} {DD} {HH} {mm} {ss} {TS} {TS6} {RNDn}
      // Example default: CON-20250920-123456
      pattern: 'CON-{YYYY}{MM}{DD}-{TS6}',

      // Allow users to switch to manual entry in UI
      allowManual: true,

      // Default mode when creating: 'auto' or 'manual'
      defaultMode: 'auto',
    },
  },

  // Feature flags
  features: {
    enableVehicleTracking: true,
    enableDriverLicenseValidation: true,
    enableConcessionRenewal: true,
    enableFinePayments: true,
    enableDocumentVerification: true,
    enableNotifications: true,
    enableReports: true,
    enableAuditLog: true,
  },

  // Permissions
  permissions: {
    vehicles: ['read', 'create', 'update', 'delete', 'export'],
    drivers: ['read', 'create', 'update', 'delete', 'export'],
    concessions: ['read', 'create', 'update', 'delete', 'export', 'renew'],
    concessionHolders: ['read', 'create', 'update', 'delete', 'export'],
    fines: ['read', 'create', 'update', 'delete', 'export', 'pay'],
    documents: ['read', 'create', 'update', 'delete', 'download', 'verify'],
  },
}
