// Generated by DDD Module Generator on 2025-09-10

import type { VerticalNavItems } from '@layouts/types'

const TransportModuleMenu: VerticalNavItems = [
  {
    title: 'Dashboards',
    icon: { icon: 'tabler-smart-home' },
    action: 'read',
    subject: 'transportmanagement',
    to: 'dashboards-crm',
  },
  {
    title: 'TransportModule.menu.title',
    icon: { icon: 'tabler-truck' },
    to: 'transportDashboard',
    action: 'read',
    subject: 'transportmanagement',
    children: [
      // {
      //   title: 'TransportModule.menu.vehicles',
      //   icon: { icon: 'tabler-car' },
      //   to: 'vehiclesList',
      //   action: 'read',
      //   subject: 'vehicles',
      // },
      // {
      //   title: 'TransportModule.menu.drivers',
      //   icon: { icon: 'tabler-user-circle' },
      //   to: 'driversList',
      //   action: 'read',
      //   subject: 'drivers',
      // },
      {
        title: 'TransportModule.menu.concession_holders',
        icon: { icon: 'tabler-users' },
        to: 'concessionHoldersList',
        action: 'read',
        subject: 'concessionholder',
      },
      {
        title: 'TransportModule.menu.concessions',
        icon: { icon: 'tabler-certificate' },
        to: 'concessionsList',
        action: 'read',
        subject: 'concession',
      },
      {
        title: 'TransportModule.menu.fines',
        icon: { icon: 'tabler-receipt' },
        to: 'finesList',
        action: 'read',
        subject: 'fine',
      },

      // {
      //   title: 'TransportModule.menu.documents',
      //   icon: { icon: 'tabler-file-text' },
      //   to: 'documentsList',
      //   action: 'read',
      //   subject: 'documents',
      // },
    ],
  },
]

export default TransportModuleMenu
