// Generated by DDD Module Generator on 2025-09-10

import type { RouteRecordRaw } from 'vue-router'

const TransportModuleRoutes: RouteRecordRaw[] = [
  // Transport Dashboard
  {
    path: '/transport',
    name: 'transportDashboard',
    component: () => import('@/modules/TransportModule/shared/presentation/views/TransportDashboard.vue'),
    meta: {
      action: 'read',
      subject: 'transport',
    },
  },

  // Vehicle Routes
  {
    path: '/vehicles',
    name: 'vehiclesList',
    component: () => import('@/modules/TransportModule/Vehicle/presentation/views/VehicleList.vue'),
    meta: {
      action: 'read',
      subject: 'vehicles',
    },
  },
  {
    path: '/vehicles/create',
    name: 'vehiclesCreate',
    component: () => import('@/modules/TransportModule/Vehicle/presentation/views/VehicleCreate.vue'),
    meta: {
      action: 'create',
      subject: 'vehicles',
    },
  },
  {
    path: '/vehicles/edit/:id',
    name: 'vehiclesEdit',
    component: () => import('@/modules/TransportModule/Vehicle/presentation/views/VehicleEdit.vue'),
    meta: {
      action: 'update',
      subject: 'vehicles',
    },
  },
  {
    path: '/vehicles/:id',
    name: 'vehiclesView',
    component: () => import('@/modules/TransportModule/Vehicle/presentation/views/VehicleView.vue'),
    meta: {
      action: 'read',
      subject: 'vehicles',
    },
  },

  // Driver Routes
  {
    path: '/drivers',
    name: 'driversList',
    component: () => import('@/modules/TransportModule/Driver/presentation/views/DriverList.vue'),
    meta: {
      action: 'read',
      subject: 'drivers',
    },
  },
  {
    path: '/drivers/create',
    name: 'driversCreate',
    component: () => import('@/modules/TransportModule/Driver/presentation/views/DriverCreate.vue'),
    meta: {
      action: 'create',
      subject: 'drivers',
    },
  },
  {
    path: '/drivers/edit/:id',
    name: 'driversEdit',
    component: () => import('@/modules/TransportModule/Driver/presentation/views/DriverEdit.vue'),
    meta: {
      action: 'update',
      subject: 'drivers',
    },
  },
  {
    path: '/drivers/:id',
    name: 'driversView',
    component: () => import('@/modules/TransportModule/Driver/presentation/views/DriverView.vue'),
    meta: {
      action: 'read',
      subject: 'drivers',
    },
  },

  // Concession Routes
  {
    path: '/concessions',
    name: 'concessionsList',
    component: () => import('@/modules/TransportModule/Concession/presentation/views/ConcessionList.vue'),
    meta: {
      action: 'read',
      subject: 'concessions',
    },
  },
  {
    path: '/concessions/create',
    name: 'concessionsCreate',
    component: () => import('@/modules/TransportModule/Concession/presentation/views/ConcessionCreate.vue'),
    meta: {
      action: 'create',
      subject: 'concessions',
    },
  },
  {
    path: '/concessions/edit/:id',
    name: 'concessionsEdit',
    component: () => import('@/modules/TransportModule/Concession/presentation/views/ConcessionEdit.vue'),
    meta: {
      action: 'update',
      subject: 'concessions',
    },
  },
  {
    path: '/concessions/:id',
    name: 'concessionsView',
    component: () => import('@/modules/TransportModule/Concession/presentation/views/ConcessionDetail.vue'),
    meta: {
      action: 'read',
      subject: 'concessions',
    },
  },

  // Concession Holder Routes
  {
    path: '/concession-holders',
    name: 'concessionHoldersList',
    component: () => import('@/modules/TransportModule/ConcessionHolder/presentation/views/ConcessionHolderList.vue'),
    meta: {
      action: 'read',
      subject: 'concession-holders',
    },
  },
  {
    path: '/concession-holders/create',
    name: 'concessionHoldersCreate',
    component: () => import('@/modules/TransportModule/ConcessionHolder/presentation/views/ConcessionHolderCreate.vue'),
    meta: {
      action: 'create',
      subject: 'concession-holders',
    },
  },
  {
    path: '/concession-holders/edit/:id',
    name: 'concessionHoldersEdit',
    component: () => import('@/modules/TransportModule/ConcessionHolder/presentation/views/ConcessionHolderEdit.vue'),
    meta: {
      action: 'update',
      subject: 'concession-holders',
    },
  },
  {
    path: '/concession-holders/:id',
    name: 'concessionHoldersView',
    component: () => import('@/modules/TransportModule/ConcessionHolder/presentation/views/ConcessionHolderDetail.vue'),
    meta: {
      action: 'read',
      subject: 'concession-holders',
    },
  },

  // Fine Routes
  {
    path: '/fines',
    name: 'finesList',
    component: () => import('@/modules/TransportModule/Fine/presentation/views/FineList.vue'),
    meta: {
      action: 'read',
      subject: 'fines',
    },
  },
  {
    path: '/fines/create',
    name: 'finesCreate',
    component: () => import('@/modules/TransportModule/Fine/presentation/views/FineCreate.vue'),
    meta: {
      action: 'create',
      subject: 'fines',
    },
  },
  {
    path: '/fines/edit/:id',
    name: 'finesEdit',
    component: () => import('@/modules/TransportModule/Fine/presentation/views/FineEdit.vue'),
    meta: {
      action: 'update',
      subject: 'fines',
    },
  },
  {
    path: '/fines/:id',
    name: 'finesView',
    component: () => import('@/modules/TransportModule/Fine/presentation/views/FineView.vue'),
    meta: {
      action: 'read',
      subject: 'fines',
    },
  },
  {
    path: '/fines/payment/:id',
    name: 'finesPayment',
    component: () => import('@/modules/TransportModule/Fine/presentation/views/FinePayment.vue'),
    meta: {
      action: 'update',
      subject: 'fines',
    },
  },

  // Document Routes
  {
    path: '/documents',
    name: 'documentsList',
    component: () => import('@/modules/TransportModule/Document/presentation/views/DocumentList.vue'),
    meta: {
      action: 'read',
      subject: 'documents',
    },
  },
  {
    path: '/documents/upload',
    name: 'documentsUpload',
    component: () => import('@/modules/TransportModule/Document/presentation/views/DocumentUpload.vue'),
    meta: {
      action: 'create',
      subject: 'documents',
    },
  },
  {
    path: '/documents/edit/:id',
    name: 'documentsEdit',
    component: () => import('@/modules/TransportModule/Document/presentation/views/DocumentEdit.vue'),
    meta: {
      action: 'update',
      subject: 'documents',
    },
  },
  {
    path: '/documents/:id',
    name: 'documentsView',
    component: () => import('@/modules/TransportModule/Document/presentation/views/DocumentView.vue'),
    meta: {
      action: 'read',
      subject: 'documents',
    },
  },
]

export default TransportModuleRoutes
