// Generated by DDD Module Generator on 2025-07-04

import { AggregateRoot } from '../../../shared/domain/base/AggregateRoot'
import type { UniqueEntityID } from '../../../shared/domain/base/UniqueEntityID'
import { Result } from '../../../shared/domain/base/Result'
import { Guard } from '../../../shared/domain/base/Guard'
import { DataSourceId } from '../valueObjects/DataSourceId'
import { DataSourceCreated } from '../events/DataSourceCreated'
import { DataSourceUpdated } from '../events/DataSourceUpdated'
import { DataSourceDeleted } from '../events/DataSourceDeleted'

export interface DataSourceProps {
  id?: string
  connection_id: string
  name: string
  type: 'custom_sql' | 'visual_builder' | 'hybrid'
  custom_sql?: string
  available_fields: Record<string, any>
  created_at?: Date
  updated_at?: Date
}

export class DataSource extends AggregateRoot<DataSourceProps> {
  private constructor(props: DataSourceProps, id?: UniqueEntityID) {
    super(props, id)
  }

  get dataSourceId(): DataSourceId {
    return DataSourceId.create(this.id)
  }

  public static create(props: DataSourceProps, id?: UniqueEntityID): Result<DataSource> {
    const guardResult = Guard.againstNullOrUndefinedBulk([
      { argument: props.connection_id, argumentName: 'connection_id' },
      { argument: props.name, argumentName: 'name' },
      { argument: props.type, argumentName: 'type' },
      { argument: props.available_fields, argumentName: 'available_fields' },
    ])

    if (!guardResult.succeeded)
      return Result.fail<DataSource>(guardResult.message)

    const dataSource = new DataSource({
      ...props,
      createdAt: props.createdAt || new Date(),
      updatedAt: props.updatedAt || new Date(),
    }, id)

    const isNew = !id
    if (isNew)
      dataSource.addDomainEvent(new DataSourceCreated(dataSource))

    return Result.ok<DataSource>(dataSource)
  }

  public update(props: Partial<DataSourceProps>): Result<void> {
    const guardResult = Guard.againstNullOrUndefined(props, 'props')

    if (!guardResult.succeeded)
      return Result.fail<void>(guardResult.message)

    this.props.updatedAt = new Date()
    Object.assign(this.props, props)

    this.addDomainEvent(new DataSourceUpdated(this))

    return Result.ok<void>()
  }

  public delete(): Result<void> {
    this.addDomainEvent(new DataSourceDeleted(this))

    return Result.ok<void>()
  }

  // Getters
  get id(): string {
    return this.props.id
  }

  get connection_id(): string {
    return this.props.connection_id
  }

  get name(): string {
    return this.props.name
  }

  get type(): 'custom_sql' | 'visual_builder' | 'hybrid' {
    return this.props.type
  }

  get custom_sql(): string {
    return this.props.custom_sql
  }

  get available_fields(): Record<string, any> {
    return this.props.available_fields
  }

  get created_at(): Date {
    return this.props.created_at
  }

  get updated_at(): Date {
    return this.props.updated_at
  }

  // Business Methods
  addReport(item: any): Result<void> {
    // Business logic for adding Report
    return Result.ok<void>()
  }
}
