// Generated by DDD Module Generator on 2025-09-11

import type { ConcessionHolderEntity } from '../../../domain/entities/ConcessionHolderEntity'
import { ConcessionHolderMapper } from '../../../application/mappers/ConcessionHolderMapper'
import type {
  ConcessionHolderListDto,
  PaginatedResponseDto,
} from '../../../application/dtos/ConcessionHolderDtos'

export class ConcessionHolderTransformer {
  static fromApi(apiData: any): ConcessionHolderEntity | null {
    if (!apiData)
      return null

    return ConcessionHolderMapper.toDomain(apiData)
  }

  static toApi(concessionHolder: Partial<ConcessionHolderEntity>): any {
    return ConcessionHolderMapper.toPersistence(concessionHolder)
  }

  static manyFromApi(apiDataArray: any[]): ConcessionHolderEntity[] {
    return apiDataArray
      .map(apiData => this.fromApi(apiData))
      .filter(Boolean) as ConcessionHolderEntity[]
  }

  // Transformar respuesta paginada de Laravel
  static fromPaginatedApi(apiResponse: any): PaginatedResponseDto<ConcessionHolderListDto> {
    return {
      data: apiResponse.data || [],
      links: apiResponse.links || {
        first: '',
        last: '',
        prev: null,
        next: null,
      },
      meta: apiResponse.meta || {
        current_page: 1,
        from: 1,
        last_page: 1,
        links: [],
        path: '',
        per_page: 20,
        to: 0,
        total: 0,
      },
    }
  }

  // Transformar lista de DTOs a entidades
  static fromListDtoToEntities(dtoList: ConcessionHolderListDto[]): ConcessionHolderEntity[] {
    return dtoList
      .map(dto => this.fromApi(dto))
      .filter(Boolean) as ConcessionHolderEntity[]
  }

  // Transformar entidades a DTOs de lista
  static fromEntitiesToListDtos(entities: ConcessionHolderEntity[]): ConcessionHolderListDto[] {
    return entities.map(entity => ConcessionHolderMapper.toListDto(entity))
  }
}
