// Generated by DDD Module Generator on 2025-07-04

export interface PaginationMeta {
  total: number
  page: number
  per_page: number
  total_pages: number
}

export interface ApiResponse<T> {
  data: T
  meta?: PaginationMeta
  message?: string
  success: boolean
}

export interface ListFilters {
  search?: string
  sortBy?: string
  sortOrder?: 'asc' | 'desc'
  page?: number
  limit?: number
  [key: string]: any
}

export interface BaseEntity {
  id: string
  createdAt: Date
  updatedAt: Date
}

export interface CreateEntityDto {
  [key: string]: any
}

export interface UpdateEntityDto {
  id: string
  [key: string]: any
}
