// Generated by DDD Module Generator

import type {
  ConcessionHolderCreateDto,
  ConcessionHolderDetailDto,
  ConcessionHolderFilterDto,
  ConcessionHolderListDto,
  ConcessionHolderStatsDto,
  ConcessionHolderUpdateDto,
  PaginatedResponseDto,
} from '../../../application/dtos/ConcessionHolderDtos'
import { rawApi } from '@/services/api'

export class ConcessionHolderApiService {
  private readonly baseUrl = '/transport/concession-holders'

  async create(data: ConcessionHolderCreateDto): Promise<ConcessionHolderDetailDto> {
    return await rawApi(this.baseUrl, { method: 'POST', body: data })
  }

  async update(id: string, data: ConcessionHolderUpdateDto): Promise<ConcessionHolderDetailDto> {
    return await rawApi(`${this.baseUrl}/${id}`, { method: 'PUT', body: data })
  }

  async delete(id: string): Promise<void> {
    return await rawApi(`${this.baseUrl}/${id}`, { method: 'DELETE' })
  }

  async getById(id: string): Promise<ConcessionHolderDetailDto> {
    return await rawApi(`${this.baseUrl}/${id}`, { method: 'GET' })
  }

  async getAll(): Promise<ConcessionHolderListDto[]> {
    return await rawApi(this.baseUrl, { method: 'GET' })
  }

  async getList(params?: ConcessionHolderFilterDto): Promise<PaginatedResponseDto<ConcessionHolderListDto>> {
    return await rawApi(this.baseUrl, { method: 'GET', params })
  }

  // ConcessionHolder specific methods
  async getHolderStats(): Promise<ConcessionHolderStatsDto> {
    return await rawApi(`${this.baseUrl}/stats`, { method: 'GET' })
  }

  async getHolderConcessions(id: string): Promise<any[]> {
    return await rawApi(`${this.baseUrl}/${id}/concessions`, { method: 'GET' })
  }

  async exportConcessionHolders(params?: ConcessionHolderFilterDto): Promise<Blob> {
    return await rawApi(`${this.baseUrl}/export`, {
      method: 'GET',
      params,
      responseType: 'blob',
    })
  }

  // Métodos de utilidad para paginación
  async getPage(page: number, perPage: number = 20, filters?: Omit<ConcessionHolderFilterDto, 'page' | 'per_page'>): Promise<PaginatedResponseDto<ConcessionHolderListDto>> {
    return await this.getList({
      ...filters,
      page,
      per_page: perPage,
    })
  }

  async search(query: string, page: number = 1, perPage: number = 20): Promise<PaginatedResponseDto<ConcessionHolderListDto>> {
    return await this.getList({
      search: query,
      page,
      per_page: perPage,
    })
  }
}
