// Generated by DDD Module Generator on 2025-07-04

import type { DataSourceRepository } from '../../../domain/contracts/repositories/DataSourceRepository'
import type { DataSource } from '../../../domain/entities/DataSource'
import type { DataSourceId } from '../../../domain/valueObjects/DataSourceId'
import { DataSourceMapper } from '../../../application/mappers/DataSourceMapper'

export class DataSourceRepositoryImpl implements DataSourceRepository {
  private models = new Map<string, any>()

  async exists(dataSourceId: DataSourceId): Promise<boolean> {
    return this.models.has(dataSourceId.value)
  }

  async getDataSourceById(dataSourceId: DataSourceId): Promise<DataSource> {
    const raw = this.models.get(dataSourceId.value)
    if (!raw)
      return null

    return DataSourceMapper.toDomain(raw)
  }

  async save(dataSource: DataSource): Promise<void> {
    const raw = DataSourceMapper.toPersistence(dataSource)

    this.models.set(dataSource.id.toString(), raw)
  }

  async delete(dataSourceId: DataSourceId): Promise<void> {
    this.models.delete(dataSourceId.value)
  }

  async getAll(): Promise<DataSource[]> {
    const all = Array.from(this.models.values())

    return all.map(raw => DataSourceMapper.toDomain(raw)).filter(Boolean)
  }

  async getAllPaginated(page: number, limit: number): Promise<{
    dataSources: DataSource[]
    totalPages: number
    total: number
  }> {
    const all = await this.getAll()
    const total = all.length
    const totalPages = Math.ceil(total / limit)
    const start = (page - 1) * limit
    const dataSources = all.slice(start, start + limit)

    return {
      dataSources,
      totalPages,
      total,
    }
  }
}
