/**
 * Concession Application Service - Application Layer
 *
 * Orchestrates business logic for concession operations
 */

import type { ConcessionEntity } from '../../domain/entities/ConcessionEntity'
import type { ConcessionRepository } from '../../domain/repositories/ConcessionRepository'
import type {
  ConcessionCreateDto,
  ConcessionFilterDto,
  ConcessionRenewalDto,
  ConcessionStatsDto,
  ConcessionUpdateDto,
} from '../dtos/ConcessionDtos'

export class ConcessionApplicationService {
  constructor(
    private readonly concessionRepository: ConcessionRepository,
  ) {}

  async getConcessions(filters: ConcessionFilterDto) {
    try {
      const concessions = await this.concessionRepository.findAll(filters)

      return {
        success: true,
        data: concessions.map(concession => ({
          id: concession.id,
          concession_number: concession.concessionNumber,
          concession_type: concession.concessionType,
          route_description: concession.routeDescription,
          service_area: concession.serviceArea,
          status: concession.status,
          issue_date: concession.issueDate,
          expiry_date: concession.expiryDate,
          renewal_date: concession.renewalDate,
          holder_id: concession.holderId,
          holder_name: concession.holderName || '',
          fee_amount: concession.feeAmount,
          fee_paid: concession.feePaid,
          last_payment_date: concession.lastPaymentDate,
          created_at: concession.createdAt,
          updated_at: concession.updatedAt,
        })),
        meta: {
          total: await this.concessionRepository.count(filters),
          page: filters.page || 1,
          per_page: filters.per_page || 20,
        },
      }
    }
    catch (error) {
      console.error('Error fetching concessions:', error)
      throw new Error('Failed to fetch concessions')
    }
  }

  async getConcessionById(id: string) {
    try {
      const concession = await this.concessionRepository.findById(id)
      if (!concession)
        throw new Error('Concession not found')

      return {
        success: true,
        data: {
          id: concession.id,
          concession_number: concession.concessionNumber,
          concession_type: concession.concessionType,
          route_description: concession.routeDescription,
          service_area: concession.serviceArea,
          status: concession.status,
          issue_date: concession.issueDate,
          expiry_date: concession.expiryDate,
          renewal_date: concession.renewalDate,
          holder_id: concession.holderId,
          holder_name: concession.holderName || '',
          fee_amount: concession.feeAmount,
          fee_paid: concession.feePaid,
          last_payment_date: concession.lastPaymentDate,
          terms_conditions: concession.termsConditions,
          notes: concession.notes,
          renewal_history: [],
          payment_history: [],
          created_at: concession.createdAt,
          updated_at: concession.updatedAt,
        },
      }
    }
    catch (error) {
      console.error('Error fetching concession:', error)
      throw error
    }
  }

  async createConcession(dto: ConcessionCreateDto) {
    try {
      // Validate dates
      if (new Date(dto.expiry_date) <= new Date(dto.issue_date))
        throw new Error('Expiry date must be after issue date')

      // Validate fee amount
      if (dto.fee_amount <= 0)
        throw new Error('Fee amount must be greater than zero')

      const concessionData: Omit<ConcessionEntity, 'id' | 'createdAt' | 'updatedAt'> = {
        concessionNumber: '', // Generated by backend
        concessionType: dto.concession_type,
        routeDescription: dto.route_description,
        serviceArea: dto.service_area,
        status: 'ACTIVE',
        issueDate: dto.issue_date,
        expiryDate: dto.expiry_date,
        holderId: dto.holder_id,
        feeAmount: dto.fee_amount,
        feePaid: false,
        termsConditions: dto.terms_conditions,
        notes: dto.notes,
      }

      const concession = await this.concessionRepository.create(concessionData)

      return {
        success: true,
        data: concession,
        message: 'Concession created successfully',
      }
    }
    catch (error) {
      console.error('Error creating concession:', error)
      throw error
    }
  }

  async updateConcession(id: string, dto: ConcessionUpdateDto) {
    try {
      const existingConcession = await this.concessionRepository.findById(id)
      if (!existingConcession)
        throw new Error('Concession not found')

      // Validate dates if provided
      if (dto.expiry_date) {
        const issueDate = existingConcession.issueDate
        if (new Date(dto.expiry_date) <= new Date(issueDate))
          throw new Error('Expiry date must be after issue date')
      }

      // Validate fee amount if provided
      if (dto.fee_amount !== undefined && dto.fee_amount <= 0)
        throw new Error('Fee amount must be greater than zero')

      const updateData: Partial<ConcessionEntity> = {}
      if (dto.concession_type !== undefined)
        updateData.concessionType = dto.concession_type
      if (dto.route_description !== undefined)
        updateData.routeDescription = dto.route_description
      if (dto.service_area !== undefined)
        updateData.serviceArea = dto.service_area
      if (dto.status !== undefined)
        updateData.status = dto.status
      if (dto.expiry_date !== undefined)
        updateData.expiryDate = dto.expiry_date
      if (dto.renewal_date !== undefined)
        updateData.renewalDate = dto.renewal_date
      if (dto.fee_amount !== undefined)
        updateData.feeAmount = dto.fee_amount
      if (dto.fee_paid !== undefined)
        updateData.feePaid = dto.fee_paid
      if (dto.last_payment_date !== undefined)
        updateData.lastPaymentDate = dto.last_payment_date
      if (dto.terms_conditions !== undefined)
        updateData.termsConditions = dto.terms_conditions
      if (dto.notes !== undefined)
        updateData.notes = dto.notes

      const concession = await this.concessionRepository.update(id, updateData)

      return {
        success: true,
        data: concession,
        message: 'Concession updated successfully',
      }
    }
    catch (error) {
      console.error('Error updating concession:', error)
      throw error
    }
  }

  async deleteConcession(id: string) {
    try {
      const existingConcession = await this.concessionRepository.findById(id)
      if (!existingConcession)
        throw new Error('Concession not found')

      await this.concessionRepository.delete(id)

      return {
        success: true,
        message: 'Concession deleted successfully',
      }
    }
    catch (error) {
      console.error('Error deleting concession:', error)
      throw error
    }
  }

  async renewConcession(dto: ConcessionRenewalDto) {
    try {
      const concession = await this.concessionRepository.findById(dto.concession_id)
      if (!concession)
        throw new Error('Concession not found')

      const updateData: Partial<ConcessionEntity> = {
        expiryDate: dto.new_expiry_date,
        renewalDate: new Date().toISOString(),
        feeAmount: dto.fee_amount,
        feePaid: !!dto.payment_method,
        lastPaymentDate: dto.payment_method ? new Date().toISOString() : undefined,
        status: 'ACTIVE',
      }

      const updatedConcession = await this.concessionRepository.update(dto.concession_id, updateData)

      return {
        success: true,
        data: updatedConcession,
        message: 'Concession renewed successfully',
      }
    }
    catch (error) {
      console.error('Error renewing concession:', error)
      throw error
    }
  }

  async getConcessionStats(): Promise<ConcessionStatsDto> {
    try {
      return await this.concessionRepository.getStats()
    }
    catch (error) {
      console.error('Error fetching concession stats:', error)
      throw new Error('Failed to fetch concession statistics')
    }
  }

  async getExpiringConcessions(days: number = 30) {
    try {
      const futureDate = new Date()

      futureDate.setDate(futureDate.getDate() + days)

      const filters: ConcessionFilterDto = {
        status: 'ACTIVE',
        expiry_date_to: futureDate.toISOString().split('T')[0],
      }

      const concessions = await this.concessionRepository.findAll(filters)

      return {
        success: true,
        data: concessions.map(c => ({
          id: c.id,
          concession_number: c.concessionNumber,
          concession_type: c.concessionType,
          route_description: c.routeDescription,
          service_area: c.serviceArea,
          status: c.status,
          issue_date: c.issueDate,
          expiry_date: c.expiryDate,
          renewal_date: c.renewalDate,
          holder_id: c.holderId,
          holder_name: c.holderName || '',
          fee_amount: c.feeAmount,
          fee_paid: c.feePaid,
          last_payment_date: c.lastPaymentDate,
          created_at: c.createdAt,
          updated_at: c.updatedAt,
        })),
      }
    }
    catch (error) {
      console.error('Error fetching expiring concessions:', error)
      throw new Error('Failed to fetch expiring concessions')
    }
  }
}
