export const CONSUMABLE_TYPES = [
  {
    title: 'Bentonita',
    value: 'bentonite',
    icon: 'tabler-droplet',
    color: '#10B981',
    category: 'drilling_fluid',
    description: 'Fluido de perforación base',
    translationKey: 'DrillingReportsModule.consumables.bentonite',
  },
  {
    title: 'Grasa para tubos',
    value: 'pipe_grease',
    icon: 'tabler-oil',
    color: '#F59E0B',
    category: 'lubrication',
    description: 'Grasa para lubricación de tubos',
    translationKey: 'DrillingReportsModule.consumables.pipe_grease',
  },
  {
    title: 'Pac',
    value: 'pac',
    icon: 'tabler-chemical',
    color: '#3B82F6',
    category: 'additive',
    description: 'Aditivo químico Pac',
    translationKey: 'DrillingReportsModule.consumables.pac',
  },
  {
    title: 'Penetrol',
    value: 'penetrol',
    icon: 'tabler-chemical',
    color: '#8B5CF6',
    category: 'additive',
    description: 'Aditivo químico Penetrol',
    translationKey: 'DrillingReportsModule.consumables.penetrol',
  },
  {
    title: 'Polimero',
    value: 'polymer',
    icon: 'tabler-chemical',
    color: '#8B5CF6',
    category: 'additive',
    description: 'Polímero para fluidos de perforación',
    translationKey: 'DrillingReportsModule.consumables.polymer',
  },
  {
    title: 'Soda ash',
    value: 'soda_ash',
    icon: 'tabler-chemical',
    color: '#6B7280',
    category: 'additive',
    description: 'Carbonato de sodio',
    translationKey: 'DrillingReportsModule.consumables.soda_ash',
  },
  {
    title: 'Jabón potásico',
    value: 'potassium_soap',
    icon: 'tabler-chemical',
    color: '#10B981',
    category: 'additive',
    description: 'Jabón potásico para fluidos',
    translationKey: 'DrillingReportsModule.consumables.potassium_soap',
  },
  {
    title: 'Diesel',
    value: 'diesel',
    icon: 'tabler-gas-station',
    color: '#F59E0B',
    category: 'fuel',
    description: 'Combustible diesel',
    translationKey: 'DrillingReportsModule.consumables.diesel',
  },
  {
    title: 'Gasolina',
    value: 'gasoline',
    icon: 'tabler-gas-station',
    color: '#EF4444',
    category: 'fuel',
    description: 'Combustible gasolina',
    translationKey: 'DrillingReportsModule.consumables.gasoline',
  },
  {
    title: 'Ezze Pac R',
    value: 'ezze_pac_r',
    icon: 'tabler-chemical',
    color: '#3B82F6',
    category: 'additive',
    description: 'Aditivo químico especializado',
    translationKey: 'DrillingReportsModule.consumables.ezze_pac_r',
  },
  {
    title: 'Agua',
    value: 'water',
    icon: 'tabler-droplet-filled',
    color: '#3B82F6',
    category: 'base_fluid',
    description: 'Agua como fluido base',
    translationKey: 'DrillingReportsModule.consumables.water',
  },
  {
    title: 'Cemento',
    value: 'cement',
    icon: 'tabler-building',
    color: '#6B7280',
    category: 'sealing',
    description: 'Cemento para sellado',
    translationKey: 'DrillingReportsModule.consumables.cement',
  },
  {
    title: 'Lubricante',
    value: 'lubricant',
    icon: 'tabler-oil',
    color: '#F59E0B',
    category: 'lubrication',
    description: 'Lubricante para equipos',
    translationKey: 'DrillingReportsModule.consumables.lubricant',
  },
  {
    title: 'Espuma',
    value: 'foam',
    icon: 'tabler-bubble',
    color: '#8B5CF6',
    category: 'additive',
    description: 'Agente espumante',
    translationKey: 'DrillingReportsModule.consumables.foam',
  },
  {
    title: 'Otros',
    value: 'other',
    icon: 'tabler-dots',
    color: '#6B7280',
    category: 'misc',
    description: 'Otros consumibles',
    translationKey: 'DrillingReportsModule.consumables.other',
  },
]

export const CONSUMABLE_UNITS = [
  {
    title: 'Kilogramos',
    value: 'kg',
    icon: 'tabler-scale',
    color: '#10B981',
    category: 'weight',
    symbol: 'kg',
    translationKey: 'DrillingReportsModule.units.kg',
  },
  {
    title: 'Sacos/Bolsas',
    value: 'bags',
    icon: 'tabler-package',
    color: '#3B82F6',
    category: 'count',
    symbol: 'sacos',
    translationKey: 'DrillingReportsModule.units.bags',
  },
  {
    title: 'Litros',
    value: 'liters',
    icon: 'tabler-droplet',
    color: '#3B82F6',
    category: 'volume',
    symbol: 'L',
    translationKey: 'DrillingReportsModule.units.liters',
  },
  {
    title: 'Galones',
    value: 'gallons',
    icon: 'tabler-droplet-filled',
    color: '#8B5CF6',
    category: 'volume',
    symbol: 'gal',
    translationKey: 'DrillingReportsModule.units.gallons',
  },
  {
    title: 'Unidades',
    value: 'units',
    icon: 'tabler-hash',
    color: '#6B7280',
    category: 'count',
    symbol: 'unid',
    translationKey: 'DrillingReportsModule.units.units',
  },
]

export const CONSUMABLE_CATEGORIES = [
  { value: 'drilling_fluid', label: 'Fluido de Perforación', icon: 'tabler-droplet', color: '#3B82F6' },
  { value: 'additive', label: 'Aditivo', icon: 'tabler-chemical', color: '#8B5CF6' },
  { value: 'base_fluid', label: 'Fluido Base', icon: 'tabler-droplet-filled', color: '#3B82F6' },
  { value: 'sealing', label: 'Sellado', icon: 'tabler-building', color: '#6B7280' },
  { value: 'lubrication', label: 'Lubricación', icon: 'tabler-oil', color: '#F59E0B' },
  { value: 'fuel', label: 'Combustible', icon: 'tabler-gas-station', color: '#EF4444' },
  { value: 'misc', label: 'Misceláneo', icon: 'tabler-dots', color: '#6B7280' },
]

export const CONSUMABLE_FILTERS = {
  TYPE: CONSUMABLE_TYPES,
  UNIT: CONSUMABLE_UNITS,
  CATEGORY: CONSUMABLE_CATEGORIES,
}

export const CONSUMABLE_PERMISSIONS = {
  CREATE: 'consumables.create',
  VIEW: 'consumables.view',
  UPDATE: 'consumables.update',
  DELETE: 'consumables.delete',
  EXPORT: 'consumables.export',
}

export const CONSUMABLE_NOTIFICATIONS = {
  CREATED: 'consumable_created',
  UPDATED: 'consumable_updated',
  DELETED: 'consumable_deleted',
  LOW_STOCK: 'consumable_low_stock',
  OUT_OF_STOCK: 'consumable_out_of_stock',
}
