// Generated by DDD Module Generator on 2025-07-04

import { computed } from 'vue'
import { useDataSourceStore } from '../stores/dataSourceStore'

export function useDataSource() {
  const store = useDataSourceStore()

  const isLoading = computed(() => store.loading)
  const hasError = computed(() => !!store.error)
  const errorMessage = computed(() => store.error)

  const dataSources = computed(() => store.items)
  const currentDataSource = computed(() => store.currentItem)

  const pagination = computed(() => ({
    page: store.currentPage,
    perPage: store.perPage,
    total: store.total,
    totalPages: store.totalPages,
  }))

  return {
    // Store
    store,

    // Computed
    isLoading,
    hasError,
    errorMessage,
    dataSources,
    currentDataSource,
    pagination,

    // Actions
    fetchList: store.fetchList,
    fetchById: store.fetchById,
    createItem: store.createItem,
    updateItem: store.updateItem,
    deleteItem: store.deleteItem,
    setPage: store.setPage,
    clearError: store.clearError,
  }
}
