// Generated by DDD Module Generator on 2025-07-04

import { computed, ref } from 'vue'
import type { ApiResponse } from '../types'

export function usePagination() {
  const page = ref(1)
  const perPage = ref(20)
  const total = ref(0)

  const totalPages = computed(() => Math.ceil(total.value / perPage.value))
  const hasNextPage = computed(() => page.value < totalPages.value)
  const hasPrevPage = computed(() => page.value > 1)

  const setPage = (newPage: number) => {
    page.value = newPage
  }

  const setPerPage = (newPerPage: number) => {
    perPage.value = newPerPage
    page.value = 1
  }

  const nextPage = () => {
    if (hasNextPage.value) {
      page.value++
    }
  }

  const prevPage = () => {
    if (hasPrevPage.value) {
      page.value--
    }
  }

  return {
    page,
    perPage,
    total,
    totalPages,
    hasNextPage,
    hasPrevPage,
    setPage,
    setPerPage,
    nextPage,
    prevPage,
  }
}

export function useApiCall<T>() {
  const loading = ref(false)
  const error = ref<string | null>(null)
  const data = ref<T | null>(null)

  const execute = async (apiCall: () => Promise<ApiResponse<T>>) => {
    loading.value = true
    error.value = null

    try {
      const response = await apiCall()

      data.value = response.data

      return response
    }
    catch (err) {
      error.value = err instanceof Error ? err.message : 'An error occurred'
      throw err
    }
    finally {
      loading.value = false
    }
  }

  const clearError = () => {
    error.value = null
  }

  return {
    loading,
    error,
    data,
    execute,
    clearError,
  }
}
