// Generated by DDD Module Generator on 2025-07-04

import { DynamicReportsConfig } from './config'
import { DynamicReportsRoutes } from './config/routes'
import { DynamicReportsMenu } from './config/menu'

// Import all entities
import * as Connection from './Connection'
import * as DataSource from './DataSource'
import * as Report from './Report'
import * as Execution from './Execution'

export class DynamicReportsContainer {
  private config = DynamicReportsConfig
  private routes = DynamicReportsRoutes
  private menu = DynamicReportsMenu

  // Entity containers
  private connectionContainer = Connection
  private dataSourceContainer = DataSource
  private reportContainer = Report
  private executionContainer = Execution

  constructor() {
    this.initializeContainers()
  }

  private initializeContainers() {
    // Initialize entity containers
    // This is where you would set up dependency injection
  }

  getConfig() {
    return this.config
  }

  getRoutes() {
    return this.routes
  }

  getMenu() {
    return this.menu
  }

  // Entity getters
  getConnectionContainer() { return this.connectionContainer }
  getDataSourceContainer() { return this.dataSourceContainer }
  getReportContainer() { return this.reportContainer }
  getExecutionContainer() { return this.executionContainer }

  // Module lifecycle
  install(app: any) {
    // Register routes
    this.routes.forEach(route => {
      app.router.addRoute(route)
    })

    // Register stores
    // Register components
    // Register composables
  }

  uninstall(app: any) {
    // Cleanup when module is uninstalled
  }
}
