// Generated by DDD Module Generator on 2025-07-04

import type { VerticalNavItems } from '@layouts/types'

const DynamicReportsMenu: VerticalNavItems = [
  {
    title: 'Reports',
    icon: { icon: 'tabler-report' },
    to: 'reportsCreate',
    action: 'create',
    subject: 'reports',
    children: [
      {
        title: 'Connections',
        icon: { icon: 'tabler-connection' },
        to: 'connectionsList',
        action: 'read',
        subject: 'connections',
      },
      {
        title: 'DataSources',
        icon: { icon: 'tabler-data-source' },
        to: 'data-sourcesList',
        action: 'read',
        subject: 'data-sources',
      },
      {
        title: 'Reports',
        icon: { icon: 'tabler-report' },
        to: 'reportsList',
        action: 'read',
        subject: 'reports',
      },
      {
        title: 'Executions',
        icon: { icon: 'tabler-execution' },
        to: 'executionsList',
        action: 'read',
        subject: 'executions',
      },
      {
        title: 'Dashboards',
        icon: { icon: 'tabler-layout-dashboard' },
        to: 'dashboards',
        action: 'read',
        subject: 'dashboards',
      },
      {
        title: 'Widgets',
        icon: { icon: 'tabler-widget' },
        to: 'widgets',
        action: 'read',
        subject: 'widgets',
      },
    ],
  },

]

export default DynamicReportsMenu
