// Generated by DDD Module Generator on 2025-07-04

import type { RouteRecordRaw } from 'vue-router'
import WidgetRoutes from '../Widget/routes'
import DashboardRoutes from '../Dashboard/routes'

const DynamicReportsRoutes: RouteRecordRaw[] = [
  {
    path: '/connections',
    name: 'connectionsList',
    component: () => import('@/modules/DynamicReports/Connection/presentation/views/ConnectionList.vue'),
    meta: {
      action: 'read',
      subject: 'connections',
    },
  },
  {
    path: '/connections/:id',
    name: 'connectionsView',
    component: () => import('@/modules/DynamicReports/Connection/presentation/views/ConnectionView.vue'),
    meta: {
      action: 'read',
      subject: 'connections',
    },
  },
  {
    path: '/data-sources',
    name: 'data-sourcesList',
    component: () => import('@/modules/DynamicReports/DataSource/presentation/views/DataSourceList.vue'),
    meta: {
      action: 'read',
      subject: 'data-sources',
    },
  },
  {
    path: '/data-sources/:id',
    name: 'data-sourcesView',
    component: () => import('@/modules/DynamicReports/DataSource/presentation/views/DataSourceView.vue'),
    meta: {
      action: 'read',
      subject: 'data-sources',
    },
  },
  {
    path: '/data-sources/wizard/:id?',
    name: 'data-sourcesWizard',
    component: () => import('@/modules/DynamicReports/DataSource/presentation/views/DataSourceWizard.vue'),
    meta: {
      action: 'create',
      subject: 'data-sources',
    },
  },
  {
    path: '/reports',
    name: 'reportsList',
    component: () => import('@/modules/DynamicReports/Report/presentation/views/ReportList.vue'),
    meta: {
      action: 'read',
      subject: 'reports',
    },
  },
  {
    path: '/reports/create',
    name: 'reportsCreate',
    component: () => import('@/modules/DynamicReports/Report/presentation/views/ReportCreateView.vue'),
    meta: {
      action: 'create',
      subject: 'reports',
    },
  },
  {
    path: '/reports/edit/:id',
    name: 'reportsEdit',
    component: () => import('@/modules/DynamicReports/Report/presentation/views/ReportCreateView.vue'),
    meta: {
      action: 'update',
      subject: 'reports',
    },
  },
  {
    path: '/reports/viewer/:id',
    name: 'reportsViewer',
    component: () => import('@/modules/DynamicReports/Report/presentation/views/ReportViewer.vue'),
    meta: {
      action: 'read',
      subject: 'reports',
    },
  },
  {
    path: '/reports/viewer_advance/:id',
    name: 'reportsViewerAdvance',
    component: () => import('@/modules/DynamicReports/Report/presentation/views/ReportViewer_advance.vue'),
    meta: {
      action: 'read',
      subject: 'reports',
    },
  },
  {
    path: '/executions',
    name: 'executionsList',
    component: () => import('@/modules/DynamicReports/Execution/presentation/views/ExecutionList.vue'),
    meta: {
      action: 'read',
      subject: 'executions',
    },
  },
  {
    path: '/executions/:id',
    name: 'executionsView',
    component: () => import('@/modules/DynamicReports/Execution/presentation/views/ExecutionView.vue'),
    meta: {
      action: 'read',
      subject: 'executions',
    },
  },
  // Widget Routes
  ...WidgetRoutes,
  // Dashboard Routes
  ...DashboardRoutes,
]

export default DynamicReportsRoutes
