<!-- Generated by DDD Module Generator on 2025-07-04 -->
<script setup lang="ts">
import { useForm } from 'vee-validate'
import { toTypedSchema } from '@vee-validate/zod'
import * as z from 'zod'
import { computed, ref, watch } from 'vue'
import { useConnectionStore } from '../../stores/connectionStore'
import type { ApiAuthType, ConnectionDriver, DatabaseDriver, FileFormat } from '../../../domain/entities/Connection'
import ConnectionDriverSelect from '../atoms/ConnectionDriverSelect.vue'
import DatabaseConnectionConfig from '../molecules/DatabaseConnectionConfig.vue'
import ApiConnectionConfig from '../molecules/ApiConnectionConfig.vue'
import FileConnectionConfig from '../molecules/FileConnectionConfig.vue'

interface Props {
  mode: 'create' | 'edit'
  initialData?: any
  title?: string
  loading?: boolean
}

interface Emits {
  (e: 'submit', data: any): void
  (e: 'cancel'): void
  (e: 'close'): void
}

const props = withDefaults(defineProps<Props>(), {
  title: 'Connection Form',
  loading: false,
})

const emit = defineEmits<Emits>()
const connectionStore = useConnectionStore()
const { closeDialog } = useAppManager()

// Initial form values
const initialValues = props.initialData || {
  name: '',
  description: '',
  driver: 'mysql',
  host: '',
  port: 3306,
  database_name: '',
  username: '',
  password: '',
  api_base_url: '',
  api_auth_type: 'none',
  api_auth_config: {},
  file_source: 'url',
  file_url: '',
  file_path: '',
  file_upload: null,
  file_config: {
    format: 'csv',
    delimiter: ',',
    has_header: true,
    encoding: 'utf-8',
    date_format: 'Y-m-d H:i:s',
  },
  options: {},
  metadata: {},
}

// Ref local para el driver
const driver = ref(initialValues.driver)

// Form validation schema - dynamic based on driver
const createSchema = (driver: ConnectionDriver) => {
  const baseSchema = {
    name: z.string().min(1, 'Name is required'),
    description: z.string().optional(),
    driver: z.enum(['mysql', 'postgresql', 'sqlserver', 'oracle', 'sqlite', 'api', 'file']),
    metadata: z.record(z.any()).optional(),
  }

  switch (driver) {
    case 'mysql':
    case 'postgresql':
    case 'sqlserver':
    case 'oracle':
    case 'sqlite':
      return z.object({
        ...baseSchema,
        host: z.string().min(1, 'Host is required'),
        port: z.number().min(1, 'Port is required'),
        database_name: z.string().min(1, 'Database name is required'),
        username: z.string().min(1, 'Username is required'),
        password: z.string().min(1, 'Password is required'),
        options: z.record(z.any()).optional(),
      })
    case 'api':
      return z.object({
        ...baseSchema,
        api_base_url: z.string().url('Valid URL is required'),
        api_auth_type: z.enum(['none', 'bearer', 'basic', 'api_key']),
        api_auth_config: z.record(z.any()).optional(),
      })
    case 'file':
      return z.object({
        ...baseSchema,
        file_source: z.enum(['url', 'upload', 'path'], { required_error: 'File source is required' }),
        file_url: z.string().url('Valid file URL is required').optional().or(z.literal('')),
        file_path: z.string().optional().or(z.literal('')),
        file_upload: z.any().optional(),
        file_config: z.object({
          format: z.enum(['csv', 'excel', 'json', 'xml']),
          delimiter: z.string().optional(),
          has_header: z.boolean().optional(),
          encoding: z.string().optional(),
          date_format: z.string().optional(),
        }),
      }).superRefine((data, ctx) => {
        if (data.file_source === 'url' && !data.file_url)
        ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['file_url'], message: 'File URL is required' })

        if (data.file_source === 'path' && !data.file_path)
        ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['file_path'], message: 'File path is required' })

        if (data.file_source === 'upload' && !data.file_upload)
        ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['file_upload'], message: 'File upload is required' })
    })
    default:
      return z.object(baseSchema)
  }
}

const validationSchema = computed(() => toTypedSchema(createSchema(driver.value)))

const { handleSubmit, errors, values, setFieldValue, validate, resetForm } = useForm({
  validationSchema,
  initialValues,
})

const touched = ref<Record<string, boolean>>({})
const testResult = ref<null | { success: boolean; message?: string; data?: any }>(null)
const testing = ref(false)

// Computed properties for v-model objects - moved after form initialization
const databaseConfig = computed({
  get: () => ({
    host: values.host || '',
    port: values.port || 3306,
    database_name: values.database_name || '',
    username: values.username || '',
    password: values.password || '',
    options: values.options || {},
  }),
  set: config => {
    setFieldValue('host', config.host)
    setFieldValue('port', config.port)
    setFieldValue('database_name', config.database_name)
    setFieldValue('username', config.username)
    setFieldValue('password', config.password)
    setFieldValue('options', config.options)
  },
})

const apiConfig = computed({
  get: () => ({
    api_base_url: values.api_base_url || '',
    api_auth_type: values.api_auth_type || 'none',
    api_auth_config: values.api_auth_config || {},
  }),
  set: config => {
    setFieldValue('api_base_url', config.api_base_url)
    setFieldValue('api_auth_type', config.api_auth_type)
    setFieldValue('api_auth_config', config.api_auth_config)
  },
})

const fileConfig = computed({
  get: () => ({
    file_source: values.file_source || 'url',
    file_url: values.file_url || '',
    file_path: values.file_path || '',
    file_upload: values.file_upload || null,
    file_config: values.file_config || {
      format: 'csv',
      delimiter: ',',
      has_header: true,
      encoding: 'utf-8',
      date_format: 'Y-m-d H:i:s',
    },
  }),
  set: config => {
    setFieldValue('file_source', config.file_source)
    setFieldValue('file_url', config.file_url)
    setFieldValue('file_path', config.file_path)
    setFieldValue('file_upload', config.file_upload)
    setFieldValue('file_config', config.file_config)
  },
})

function setTouched(field: string) {
  touched.value[field] = true
}

function showError(field: string) {
  return (touched.value[field] || testResult.value !== null) ? errors[field] : undefined
}

const allFieldsFilled = computed(() => {
  const driver = values.driver

  switch (driver) {
    case 'mysql':
    case 'postgresql':
    case 'sqlserver':
    case 'oracle':
    case 'sqlite':
      return values.name && values.host && values.port && values.database_name && values.username && values.password
    case 'api':
      return values.name && values.api_base_url
    case 'file':
      if (values.file_source === 'url')
      return values.name && values.file_url && values.file_config?.format

      if (values.file_source === 'upload') {
        return values.name && values.file_upload && (
          (Array.isArray(values.file_upload) && values.file_upload.length > 0)
          || (!Array.isArray(values.file_upload) && values.file_upload)
        ) && values.file_config?.format
      }
      if (values.file_source === 'path')
      return values.name && values.file_path && values.file_config?.format

      return false
    default:
      return false
  }
})

const onSubmit = handleSubmit(async values => {
  try {
    // Prepare payload based on driver type
    const payload = {
      name: values.name,
      description: values.description,
      driver: values.driver,
      status: 'active',
      metadata: values.metadata,
    }

    // Add driver-specific fields
    switch (values.driver) {
      case 'mysql':
      case 'postgresql':
      case 'sqlserver':
      case 'oracle':
      case 'sqlite':
        Object.assign(payload, {
          host: values.host,
          port: values.port,
          database_name: values.database_name,
          username: values.username,
          password: values.password,
          options: values.options,
        })
        break
      case 'api':
        Object.assign(payload, {
          api_base_url: values.api_base_url,
          api_auth_type: values.api_auth_type,
          api_auth_config: values.api_auth_config,
        })
        break
      case 'file':
        Object.assign(payload, {
          file_source: values.file_source,
          file_url: values.file_url,
          file_path: values.file_path,
          file_upload: values.file_upload,
          file_config: values.file_config,
        })
        break
    }

    if (props.mode === 'create')
      await connectionStore.createItem(payload)
    else if (props.mode === 'edit')
      await connectionStore.updateItem(values.id, payload)

    close('submit')
  }
  catch (error) {
    console.error(error)
  }
})

async function onTestConnection() {
  // Mark all fields as touched to show errors
  Object.keys(values).forEach(setTouched)

  const { valid } = await validate()
  if (!valid) {
    console.log('errors', errors)
    testResult.value = null

    return
  }

  // Prepare test payload based on driver type
  const testPayload = {
    name: values.name,
    driver: values.driver,
  }

  switch (values.driver) {
    case 'mysql':
    case 'postgresql':
    case 'sqlserver':
    case 'oracle':
    case 'sqlite':
      Object.assign(testPayload, {
        host: values.host,
        port: values.port,
        database_name: values.database_name,
        username: values.username,
        password: values.password,
        options: values.options,
      })
      break
    case 'api':
      Object.assign(testPayload, {
        api_base_url: values.api_base_url,
        api_auth_type: values.api_auth_type,
        api_auth_config: values.api_auth_config,
      })
      break
    case 'file':
      Object.assign(testPayload, {
        file_source: values.file_source,
        file_url: values.file_url,
        file_path: values.file_path,
        file_upload: values.file_upload,
        file_config: values.file_config,
      })
      break
  }

  testing.value = true

  const result = await connectionStore.testConnectionBeforeSave(testPayload)

  testResult.value = result
  testing.value = false
}

function close(result: 'close' | 'submit' | 'cancel' = 'close') {
  closeDialog(result)
}

// Reset form when driver changes
watch(() => values.driver, newDriver => {
  // Reset driver-specific fields when changing driver type
  if (newDriver === 'api') {
    setFieldValue('host', '')
    setFieldValue('port', 0)
    setFieldValue('database_name', '')
    setFieldValue('username', '')
    setFieldValue('password', '')
    setFieldValue('file_path', '')
    setFieldValue('file_config', {
      format: 'csv',
      delimiter: ',',
      has_header: true,
      encoding: 'utf-8',
      date_format: 'Y-m-d H:i:s',
    })
  }
  else if (newDriver === 'file') {
    setFieldValue('host', '')
    setFieldValue('port', 0)
    setFieldValue('database_name', '')
    setFieldValue('username', '')
    setFieldValue('password', '')
    setFieldValue('api_base_url', '')
    setFieldValue('api_auth_type', 'none')
    setFieldValue('api_auth_config', {})
  }
  else {
    // Database connection
    setFieldValue('api_base_url', '')
    setFieldValue('api_auth_type', 'none')
    setFieldValue('api_auth_config', {})
    setFieldValue('file_path', '')
    setFieldValue('file_config', {
      format: 'csv',
      delimiter: ',',
      has_header: true,
      encoding: 'utf-8',
      date_format: 'Y-m-d H:i:s',
    })
  }

  // Clear test result when driver changes
  testResult.value = null
})

// Clear test result when form data changes
watch(values, () => {
  testResult.value = null
})

// Sincroniza el driver local con el del formulario
watch(() => values.driver, val => { driver.value = val })

const steps = [
  { title: 'Información básica', subtitle: 'Nombre, descripción y tipo' },
  { title: 'Credenciales', subtitle: 'Configura la conexión' },
  { title: 'Opciones avanzadas', subtitle: 'Opciones y metadata' },
  { title: 'Resumen', subtitle: 'Confirma y crea la conexión' },
]

const currentStep = ref(0)

function nextStep() {
  if (currentStep.value < steps.length - 1)
    currentStep.value++
}
function prevStep() {
  if (currentStep.value > 0)
    currentStep.value--
}

const showGeneralValidationError = ref(false)
const visibleFieldErrors = ref<Record<string, string>>({})

watch(() => testResult.value, newValue => {
  if (newValue && !newValue.success) {
    showGeneralValidationError.value = true
    visibleFieldErrors.value = newValue.data?.details?.errors || {}
  }
  else {
    showGeneralValidationError.value = false
    visibleFieldErrors.value = {}
  }
})
</script>

<template>
  <DialogCloseBtn @click="close('cancel')" />
  <VCard
    class="pa-0"
    style="max-inline-size: 900px; min-inline-size: 600px;"
  >
    <VCardTitle class="d-flex align-center justify-space-between px-6 pt-4 pb-2">
      <div class="text-h5 font-weight-bold">
        Agregar conexión
      </div>
    </VCardTitle>
    <VDivider />
    <VRow no-gutters>
      <VCol
        cols="12"
        md="4"
        class="border-e-sm pa-0"
        style="background: #fafbfc; min-block-size: 100%;"
      >
        <VCardText class="pa-6">
          <AppStepper
            v-model:current-step="currentStep"
            direction="vertical"
            :items="steps"
          />
        </VCardText>
      </VCol>
      <VCol
        cols="12"
        md="8"
        class="pa-0"
      >
        <VCardText class="pa-6">
          <!-- Alerta de error general de validación -->
          <VAlert
            v-if="showGeneralValidationError"
            type="error"
            class="mb-4"
            border="start"
            variant="tonal"
            closable
            @click:close="showGeneralValidationError = false"
          >
            Corrige los errores en los campos marcados antes de continuar.
            <ul class="mt-2 mb-0">
              <li
                v-for="(msg, key) in visibleFieldErrors"
                :key="key"
              >
                {{ msg }}
              </li>
            </ul>
          </VAlert>
          <VForm @submit.prevent="onSubmit">
            <VWindow
              v-model="currentStep"
              class="disable-tab-transition"
            >
              <!-- Paso 1: Información básica -->
              <VWindowItem>
                <div class="mb-6">
                  <div class="text-h6 font-weight-medium mb-2">
                    Información básica
                  </div>
                  <div class="text-body-2 text-medium-emphasis mb-6">
                    Nombre, descripción y tipo de conexión
                  </div>
                  <VTextField
                    :model-value="values.name"
                    label="Connection Name"
                    :error-messages="showError('name')"
                    density="comfortable"
                    hide-details="auto"
                    autofocus
                    autocomplete="off"
                    placeholder="My Database Connection"
                    class="mb-4"
                    @update:model-value="val => setFieldValue('name', val)"
                    @blur="setTouched('name')"
                  />
                  <VTextarea
                    :model-value="values.description"
                    label="Description (Optional)"
                    :error-messages="showError('description')"
                    density="comfortable"
                    hide-details="auto"
                    rows="2"
                    placeholder="Brief description of this connection..."
                    class="mb-4"
                    @update:model-value="val => setFieldValue('description', val)"
                    @blur="setTouched('description')"
                  />
                  <ConnectionDriverSelect
                    :model-value="values.driver"
                    :error="showError('driver')"
                    @update:model-value="val => setFieldValue('driver', val)"
                    @blur="setTouched('driver')"
                  />
                </div>
              </VWindowItem>

              <!-- Paso 2: Credenciales -->
              <VWindowItem>
                <div class="mb-6">
                  <div class="text-h6 font-weight-medium mb-2">
                    Configuración de credenciales
                  </div>
                  <div class="text-body-2 text-medium-emphasis mb-6">
                    Completa los datos de acceso para validar la conexión
                  </div>
                  <DatabaseConnectionConfig
                    v-if="['mysql', 'postgresql', 'sqlserver', 'oracle', 'sqlite'].includes(values.driver)"
                    v-model="databaseConfig"
                    :driver="values.driver as DatabaseDriver"
                    :errors="{
                      host: showError('host'),
                      port: showError('port'),
                      database_name: showError('database_name'),
                      username: showError('username'),
                      password: showError('password'),
                      options: showError('options'),
                    }"
                    :disabled="loading"
                    class="mb-4"
                  />
                  <ApiConnectionConfig
                    v-if="values.driver === 'api'"
                    v-model="apiConfig"
                    :errors="{
                      api_base_url: showError('api_base_url'),
                      api_auth_type: showError('api_auth_type'),
                    }"
                    :disabled="loading"
                    class="mb-4"
                    @blur-base-url="setTouched('api_base_url')"
                    @blur-auth-type="setTouched('api_auth_type')"
                  />
                  <FileConnectionConfig
                    v-if="values.driver === 'file'"
                    v-model="fileConfig"
                    :errors="{
                      file_path: showError('file_path'),
                      format: showError('file_config.format'),
                    }"
                    :disabled="loading"
                    class="mb-4"
                  />
                  <VSelect
                    v-if="values.driver === 'file'"
                    :model-value="values.file_source"
                    :items="[
                      { title: 'Desde URL', value: 'url' },
                      { title: 'Subir archivo', value: 'upload' },
                      { title: 'Ruta en servidor', value: 'path' },
                    ]"
                    label="Fuente del archivo"
                    :error-messages="showError('file_source')"
                    class="mb-4"
                    @update:model-value="val => setFieldValue('file_source', val)"
                  />
                  <VTextField
                    v-if="values.driver === 'file' && values.file_source === 'url'"
                    :model-value="values.file_url"
                    label="URL del archivo CSV"
                    :error-messages="showError('file_url')"
                    class="mb-4"
                    @update:model-value="val => setFieldValue('file_url', val)"
                    @blur="setTouched('file_url')"
                  />
                  <VFileInput
                    v-if="values.driver === 'file' && values.file_source === 'upload'"
                    :model-value="values.file_upload"
                    label="Subir archivo CSV"
                    :error-messages="showError('file_upload')"
                    class="mb-4"
                    accept=".csv,application/vnd.ms-excel,text/csv"
                    @update:model-value="val => setFieldValue('file_upload', val)"
                    @blur="setTouched('file_upload')"
                  />
                  <VTextField
                    v-if="values.driver === 'file' && values.file_source === 'path'"
                    :model-value="values.file_path"
                    label="Ruta en servidor"
                    :error-messages="showError('file_path')"
                    class="mb-4"
                    @update:model-value="val => setFieldValue('file_path', val)"
                    @blur="setTouched('file_path')"
                  />
                  <VBtn
                    color="info"
                    variant="tonal"
                    class="mt-2 mb-4"
                    :disabled="!allFieldsFilled || testing"
                    :loading="testing"
                    @click.prevent="onTestConnection"
                  >
                    <VIcon
                      icon="tabler-plug"
                      class="me-2"
                    />
                    Test Connection
                  </VBtn>
                  <VAlert
                    v-if="testResult"
                    :type="testResult.success ? 'success' : 'error'"
                    class="mt-2"
                    border="start"
                    variant="tonal"
                    closable
                    @click:close="testResult = null"
                  >
                    <template v-if="testResult.success">
                      {{ testResult.message || 'Connection test successful!' }}
                      <div
                        v-if="testResult.data?.details?.message"
                        class="text-caption mt-1"
                      >
                        {{ testResult.data.details.message }}
                      </div>
                    </template>
                    <template v-else>
                      {{ testResult.message }}
                    </template>
                  </VAlert>
                </div>
              </VWindowItem>

              <!-- Paso 3: Opciones avanzadas -->
              <VWindowItem>
                <div class="mb-6">
                  <div class="text-h6 font-weight-medium mb-2">
                    Opciones avanzadas
                  </div>
                  <div class="text-body-2 text-medium-emphasis mb-6">
                    Opciones y metadata adicionales
                  </div>
                  <VExpansionPanels variant="accordion">
                    <VExpansionPanel>
                      <VExpansionPanelTitle>
                        <VIcon
                          icon="tabler-settings"
                          class="me-2"
                        />
                        Advanced Options
                      </VExpansionPanelTitle>
                      <VExpansionPanelText>
                        <VTextarea
                          :model-value="JSON.stringify(values.metadata || {}, null, 2)"
                          label="Metadata (JSON)"
                          :error-messages="showError('metadata')"
                          density="comfortable"
                          hide-details="auto"
                          :disabled="loading"
                          rows="4"
                          placeholder="{&quot;environment&quot;: &quot;production&quot;, &quot;backup_schedule&quot;: &quot;daily&quot;}"
                          @update:model-value="val => {
                            try {
                              setFieldValue('metadata', JSON.parse(val))
                            }
                            catch {}
                          }"
                        />
                      </VExpansionPanelText>
                    </VExpansionPanel>
                  </VExpansionPanels>
                </div>
              </VWindowItem>

              <!-- Paso 4: Resumen -->
              <VWindowItem>
                <div class="mb-6">
                  <div class="text-h6 font-weight-medium mb-2">
                    Resumen
                  </div>
                  <div class="text-body-2 text-medium-emphasis mb-6">
                    Confirma y crea la conexión
                  </div>
                  <div class="mb-4">
                    <strong>Nombre:</strong> {{ values.name }}<br>
                    <strong>Descripción:</strong> {{ values.description }}<br>
                    <strong>Tipo:</strong> {{ values.driver }}<br>
                    <template v-if="['mysql', 'postgresql', 'sqlserver', 'oracle', 'sqlite'].includes(values.driver)">
                      <strong>Host:</strong> {{ values.host }}<br>
                      <strong>Base de datos:</strong> {{ values.database_name }}<br>
                      <strong>Usuario:</strong> {{ values.username }}<br>
                    </template>
                    <template v-if="values.driver === 'api'">
                      <strong>API URL:</strong> {{ values.api_base_url }}<br>
                      <strong>Auth Type:</strong> {{ values.api_auth_type }}<br>
                    </template>
                    <template v-if="values.driver === 'file'">
                      <strong>Archivo:</strong> {{ values.file_path }}<br>
                      <strong>Formato:</strong> {{ values.file_config?.format }}<br>
                    </template>
                    <strong>Metadata:</strong> <pre>{{ JSON.stringify(values.metadata, null, 2) }}</pre>
                  </div>
                </div>
              </VWindowItem>
            </VWindow>

            <div class="d-flex flex-wrap gap-4 justify-sm-space-between justify-center mt-8">
              <VBtn
                color="secondary"
                variant="tonal"
                :disabled="currentStep === 0"
                @click="prevStep"
              >
                <VIcon
                  icon="tabler-arrow-left"
                  start
                  class="flip-in-rtl"
                />
                Anterior
              </VBtn>

              <VBtn
                v-if="currentStep === steps.length - 1"
                type="submit"
                color="primary"
                :loading="loading"
                :disabled="!testResult || !testResult.success"
              >
                {{ mode === 'create' ? 'Crear' : 'Actualizar' }}
              </VBtn>

              <VBtn
                v-else
                color="primary"
                :disabled="
                  (currentStep === 0 && !values.name)
                    || (currentStep === 1 && !testResult?.success)
                "
                @click="nextStep"
              >
                Siguiente
                <VIcon
                  icon="tabler-arrow-right"
                  end
                  class="flip-in-rtl"
                />
              </VBtn>
            </div>
          </VForm>
        </VCardText>
      </VCol>
    </VRow>
  </VCard>
</template>

<style scoped>
.connection-form {
  max-inline-size: 600px;
  min-inline-size: 500px;
}
</style>
