<!-- Generated by DDD Module Generator on 2025-07-04 -->
<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import { ref } from 'vue'

interface Props {
  connection: any
}

const props = defineProps<Props>()
const { t } = useI18n()
const copied = ref(false)

function copyConnectionString() {
  navigator.clipboard.writeText(props.connection.connection_string)
  copied.value = true
  setTimeout(() => (copied.value = false), 1500)
}
</script>

<template>
  <div
    v-if="connection"
    class="connection-detail"
  >
    <VCard flat>
      <VCardTitle class="text-h5 mb-2">
        {{ t('connection.details_title', 'Connection Details') }}
      </VCardTitle>
      <VCardText>
        <VRow dense>
          <VCol
            v-if="connection.name"
            cols="12"
            md="6"
          >
            <strong>{{ t('connection.name', 'Name') }}:</strong> {{ connection.name }}
          </VCol>
          <VCol
            v-if="connection.driver"
            cols="12"
            md="6"
          >
            <strong>{{ t('connection.driver', 'Driver') }}:</strong>
            <VChip
              size="small"
              color="primary"
              variant="tonal"
            >
              {{ connection.driver }}
            </VChip>
          </VCol>
          <VCol
            v-if="connection.host"
            cols="12"
            md="6"
          >
            <strong>{{ t('connection.host', 'Host') }}:</strong> {{ connection.host }}
          </VCol>
          <VCol
            v-if="connection.port"
            cols="12"
            md="6"
          >
            <strong>{{ t('connection.port', 'Port') }}:</strong> {{ connection.port }}
          </VCol>
          <VCol
            v-if="connection.database_name"
            cols="12"
            md="6"
          >
            <strong>{{ t('connection.database_name', 'Database') }}:</strong> {{ connection.database_name }}
          </VCol>
          <VCol
            v-if="connection.username"
            cols="12"
            md="6"
          >
            <strong>{{ t('connection.username', 'Username') }}:</strong> {{ connection.username }}
          </VCol>
          <VCol
            v-if="connection.is_active !== undefined"
            cols="12"
            md="6"
          >
            <strong>{{ t('connection.status', 'Status') }}:</strong>
            <VChip
              size="small"
              :color="connection.is_active ? 'success' : 'grey'"
              variant="tonal"
            >
              {{ connection.is_active ? t('connection.active', 'Active') : t('connection.inactive', 'Inactive') }}
            </VChip>
          </VCol>
          <VCol
            v-if="connection.created_at"
            cols="12"
            md="6"
          >
            <strong>{{ t('connection.created_at', 'Created At') }}:</strong>
            {{ new Date(connection.created_at).toLocaleDateString() }}
          </VCol>
          <VCol
            v-if="connection.creator"
            cols="12"
            md="6"
          >
            <strong>{{ t('connection.created_by', 'Created By') }}:</strong>
            {{ connection.creator.name }} <span v-if="connection.creator.email">({{ connection.creator.email }})</span>
          </VCol>
          <VCol
            v-if="connection.connection_string"
            cols="12"
          >
            <strong>{{ t('connection.connection_string', 'Connection String') }}:</strong>
            <VTextField
              :model-value="connection.connection_string"
              readonly
              density="compact"
              hide-details
              append-inner-icon="tabler-copy"
              :append-inner-icon-color="copied ? 'success' : 'grey'"
              @click:append-inner="copyConnectionString"
            />
            <span
              v-if="copied"
              class="text-success text-caption"
            >{{ t('connection.copied', 'Copied!') }}</span>
          </VCol>
        </VRow>
      </VCardText>
    </VCard>
  </div>
  <div v-else>
    Loading...
  </div>
</template>

<style scoped>
.connection-detail {
  margin-block: 0;
  margin-inline: auto;
  max-inline-size: 700px;
}
</style>
