// Generated by DDD Module Generator on 2025-07-04

import type { ConnectionRepository } from '../../../domain/contracts/repositories/ConnectionRepository'
import type { Connection } from '../../../domain/entities/Connection'
import type { ConnectionId } from '../../../domain/valueObjects/ConnectionId'
import { ConnectionMapper } from '../../../application/mappers/ConnectionMapper'

export class ConnectionRepositoryImpl implements ConnectionRepository {
  private models = new Map<string, any>()

  async exists(connectionId: ConnectionId): Promise<boolean> {
    return this.models.has(connectionId.value)
  }

  async getConnectionById(connectionId: ConnectionId): Promise<Connection | null> {
    const raw = this.models.get(connectionId.value)
    if (!raw)
      return null

    return ConnectionMapper.toDomain(raw)
  }

  async save(connection: Connection): Promise<void> {
    const raw = ConnectionMapper.toPersistence(connection)

    this.models.set(connection.id.toString(), raw)
  }

  async delete(connectionId: ConnectionId): Promise<void> {
    this.models.delete(connectionId.value)
  }

  async getAll(): Promise<Connection[]> {
    const all = Array.from(this.models.values())

    return all.map(raw => ConnectionMapper.toDomain(raw)).filter(Boolean)
  }

  async getAllPaginated(page: number, limit: number): Promise<{
    connections: Connection[]
    totalPages: number
    total: number
  }> {
    const all = await this.getAll()
    const total = all.length
    const totalPages = Math.ceil(total / limit)
    const start = (page - 1) * limit
    const connections = all.slice(start, start + limit)

    return {
      connections,
      totalPages,
      total,
    }
  }
}
