// Generated by DDD Module Generator on 2025-07-04

import { computed } from 'vue'
import { useReportStore } from '../stores/reportStore'

export function useReport() {
  const store = useReportStore()

  const isLoading = computed(() => store.loading)
  const hasError = computed(() => !!store.error)
  const errorMessage = computed(() => store.error)

  const reports = computed(() => store.items)
  const currentReport = computed(() => store.currentItem)

  const pagination = computed(() => ({
    page: store.currentPage,
    perPage: store.perPage,
    total: store.total,
    totalPages: store.totalPages,
  }))

  return {
    // Store
    store,

    // Computed
    isLoading,
    hasError,
    errorMessage,
    reports,
    currentReport,
    pagination,

    // Actions
    fetchList: store.fetchList,
    fetchById: store.fetchById,
    createItem: store.createItem,
    updateItem: store.updateItem,
    deleteItem: store.deleteItem,
    setPage: store.setPage,
    clearError: store.clearError,
  }
}
