<!-- Generated by DDD Module Generator on 2025-07-04 -->
<script setup lang="ts">
import { computed } from 'vue'

interface Props {
  headers: any[]
  items: any[]
  loading: boolean
  itemsPerPage: number
  page: number
  total: number
  selection: any[]
}

interface Emits {
  (e: 'update:page', page: number): void
  (e: 'update:items-per-page', itemsPerPage: number): void
  (e: 'view', item: any): void
  (e: 'edit', item: any): void
  (e: 'delete', item: any): void
  (e: 'update:selection', selection: any[]): void
}

const props = defineProps<Props>()
const emit = defineEmits<Emits>()

const selection = computed({
  get: () => props.selection,
  set: value => emit('update:selection', value),
})
</script>

<template>
  <VDataTable
    v-model:selected="selection"
    :headers="headers"
    :items="items"
    :loading="loading"
    :items-per-page="itemsPerPage"
    :page="page"
    :total="total"
    @update:page="$emit('update:page', $event)"
    @update:items-per-page="$emit('update:items-per-page', $event)"
  >
    <template #item.actions="{ item }">
      <VBtn
        icon="tabler-eye"
        size="small"
        variant="text"
        color="primary"
        @click="$emit('view', item)"
      />
      <VBtn
        icon="tabler-edit"
        size="small"
        variant="text"
        color="warning"
        @click="$emit('edit', item)"
      />
      <VBtn
        icon="tabler-trash"
        size="small"
        variant="text"
        color="error"
        @click="$emit('delete', item)"
      />
    </template>
    <template #item.is_active="{ item }">
      <VChip
        :color="item.is_active ? 'success' : 'error'"
        :prepend-icon="item.is_active ? 'tabler-check' : 'tabler-x'"
        :label="item.is_active ? 'Activo' : 'Inactivo'"
      />
    </template>
  </VDataTable>
</template>
