<!-- Generated by DDD Module Generator on 2025-07-04 -->
<script setup lang="ts">
import { useForm } from 'vee-validate'
import { toTypedSchema } from '@vee-validate/zod'
import * as z from 'zod'
import { useAppManager } from '@/composables/useAppManager'
import { useReportStore } from '../../stores/reportStore'

interface Props {
  mode: 'create' | 'edit'
  initialData?: any
  title?: string
  loading?: boolean
}

interface Emits {
  (e: 'submit', data: any): void
  (e: 'cancel'): void
  (e: 'close'): void
}

const props = withDefaults(defineProps<Props>(), {
  title: 'Report Form',
  loading: false,
})

const emit = defineEmits<Emits>()
const reportStore = useReportStore()
const { closeDialog } = useAppManager()

// Form validation schema
const schema = toTypedSchema(z.object({
  data_source_id: z.string().min(1, 'This field is required'),
  name: z.string().min(1, 'This field is required'),
  description: z.string().optional(),
  selected_fields: z.array(z.any()).min(1, 'At least one field is required'),
  export_formats: z.array(z.any()).min(1, 'At least one export format is required'),
  default_filters: z.record(z.any()).optional(),
  is_public: z.boolean().optional(),
}))

const { handleSubmit, errors, values, setFieldValue } = useForm({
  validationSchema: schema,
  initialValues: props.initialData || {},
})

const onSubmit = handleSubmit(async values => {
  try {
    if (props.mode === 'create')
      await reportStore.createItem(values)
    else if (props.mode === 'edit')
      await reportStore.updateItem(values.id, values)

    closeDialog('submit', values)
  }
  catch (error) {
    // Opcional: mostrar error
    console.error(error)
  }
})
</script>

<template>
  <VForm @submit.prevent="onSubmit">
    <DialogCloseBtn @click="closeDialog('cancel')" />
    <VCard>
      <VCardTitle>{{ title }}</VCardTitle>
      <VCardText>
        <VRow>
          <VCol cols="12">
            <VTextField
              :model-value="values.data_source_id"
              label="Data Source Id"
              :error-messages="errors.data_source_id"
              @update:model-value="val => setFieldValue('data_source_id', val)"
            />
          </VCol>
          <VCol cols="12">
            <VTextField
              :model-value="values.name"
              label="Name"
              :error-messages="errors.name"
              @update:model-value="val => setFieldValue('name', val)"
            />
          </VCol>
          <VCol cols="12">
            <VTextField
              :model-value="values.description"
              label="Description"
              :error-messages="errors.description"
              @update:model-value="val => setFieldValue('description', val)"
            />
          </VCol>
          <VCol cols="12">
            <VTextField
              :model-value="values.selected_fields"
              label="Selected Fields"
              :error-messages="errors.selected_fields"
              @update:model-value="val => setFieldValue('selected_fields', val)"
            />
          </VCol>
          <VCol cols="12">
            <VTextField
              :model-value="values.export_formats"
              label="Export Formats"
              :error-messages="errors.export_formats"
              @update:model-value="val => setFieldValue('export_formats', val)"
            />
          </VCol>
          <VCol cols="12">
            <VTextField
              :model-value="values.default_filters"
              label="Default Filters"
              :error-messages="errors.default_filters"
              @update:model-value="val => setFieldValue('default_filters', val)"
            />
          </VCol>
          <VCol cols="12">
            <VCheckbox
              :model-value="values.is_public"
              label="Is Public"
              :error-messages="errors.is_public"
              @update:model-value="val => setFieldValue('is_public', val)"
            />
          </VCol>
        </VRow>
      </VCardText>
      <VCardActions>
        <VBtn
          type="submit"
          color="primary"
          :loading="loading"
        >
          {{ mode === 'create' ? 'Create' : 'Update' }}
        </VBtn>
        <VBtn
          color="secondary"
          variant="tonal"
          @click="closeDialog('cancel')"
        >
          Cancel
        </VBtn>
      </VCardActions>
    </VCard>
  </VForm>
</template>
