<!-- Generated by DDD Module Generator on 2025-07-04 -->
<script setup lang="ts">
interface Props {
  report: any
}

const props = defineProps<Props>()
</script>

<template>
  <div class="report-detail">
    <VList>
      <VListItem>
        <VListItemTitle>{ t('Data Source Id') }</VListItemTitle>
        <VListItemSubtitle>{{ report.data_source_id }}</VListItemSubtitle>
      </VListItem>
      <VListItem>
        <VListItemTitle>{ t('Name') }</VListItemTitle>
        <VListItemSubtitle>{{ report.name }}</VListItemSubtitle>
      </VListItem>
      <VListItem>
        <VListItemTitle>{ t('Description') }</VListItemTitle>
        <VListItemSubtitle>{{ report.description }}</VListItemSubtitle>
      </VListItem>
      <VListItem>
        <VListItemTitle>{ t('Selected Fields') }</VListItemTitle>
        <VListItemSubtitle>{{ report.selected_fields }}</VListItemSubtitle>
      </VListItem>
      <VListItem>
        <VListItemTitle>{ t('Export Formats') }</VListItemTitle>
        <VListItemSubtitle>{{ report.export_formats }}</VListItemSubtitle>
      </VListItem>
      <VListItem>
        <VListItemTitle>{ t('Default Filters') }</VListItemTitle>
        <VListItemSubtitle>{{ report.default_filters }}</VListItemSubtitle>
      </VListItem>
      <VListItem>
        <VListItemTitle>{ t('Is Public') }</VListItemTitle>
        <VListItemSubtitle>
          <VChip
            :color="report.is_public ? 'success' : 'error'"
            size="small"
          >
            {{ report.is_public ? 'Yes' : 'No' }}
          </VChip>
        </VListItemSubtitle>
      </VListItem>
    </VList>
  </div>
</template>
