<!-- Generated by DDD Module Generator on 2025-07-04 -->
<script setup lang="ts">
import { ref } from 'vue'

interface Props {
  modelValue: boolean
  shareLink: string
  title?: string
}

interface Emits {
  (e: 'update:modelValue', value: boolean): void
  (e: 'copy-link'): void
}

const props = withDefaults(defineProps<Props>(), {
  title: 'Compartir reporte',
})

const emit = defineEmits<Emits>()

const copyShareLink = () => {
  navigator.clipboard.writeText(props.shareLink)
  emit('copy-link')
}
</script>

<template>
  <VDialog
    :model-value="modelValue"
    max-width="500"
    @update:model-value="emit('update:modelValue', $event)"
  >
    <VCard>
      <VCardTitle>{{ title }}</VCardTitle>
      <VCardText>
        <VTextField
          :model-value="shareLink"
          label="Link de compartir"
          readonly
          variant="outlined"
        />
      </VCardText>
      <VCardActions>
        <VBtn @click="copyShareLink">
          Copiar link
        </VBtn>
        <VSpacer />
        <VBtn
          variant="text"
          @click="emit('update:modelValue', false)"
        >
          Cerrar
        </VBtn>
      </VCardActions>
    </VCard>
  </VDialog>
</template>
