// Generated by DDD Module Generator on 2025-07-04

import { DomainEvent } from '../../../shared/domain/base/DomainEvent'
import type { Report } from '../entities/Report'

export class ReportDeleted extends DomainEvent {
  public report: Report

  constructor(report: Report) {
    super(report.id.toString())
    this.report = report
  }
}
