// Generated by DDD Module Generator on 2025-07-04

import { AggregateRoot } from '../../../shared/domain/base/AggregateRoot'
import type { UniqueEntityID } from '../../../shared/domain/base/UniqueEntityID'
import { Result } from '../../../shared/domain/base/Result'
import { Guard } from '../../../shared/domain/base/Guard'
import { ConnectionId } from '../valueObjects/ConnectionId'
import { ConnectionCreated } from '../events/ConnectionCreated'
import { ConnectionUpdated } from '../events/ConnectionUpdated'
import { ConnectionDeleted } from '../events/ConnectionDeleted'

// Tipos de drivers soportados
export type DatabaseDriver = 'mysql' | 'postgresql' | 'sqlserver' | 'oracle' | 'sqlite'
export type ApiAuthType = 'none' | 'bearer' | 'basic' | 'api_key'
export type FileFormat = 'csv' | 'excel' | 'json' | 'xml'
export type ConnectionDriver = DatabaseDriver | 'api' | 'file'

// Configuraciones específicas por tipo
export interface DatabaseConnectionConfig {
  host: string
  port: number
  database_name: string
  username: string
  password: string
  options?: Record<string, any>
}

export interface ApiConnectionConfig {
  api_base_url: string
  api_auth_type: ApiAuthType
  api_auth_config?: {
    token?: string
    username?: string
    password?: string
    api_key?: string
    headers?: Record<string, string>
  }
}

export interface FileConnectionConfig {
  file_path: string
  file_config: {
    format: FileFormat
    delimiter?: string
    has_header?: boolean
    encoding?: string
    date_format?: string
  }
}

export interface ConnectionProps {
  id?: string
  name: string
  description?: string
  driver: ConnectionDriver
  
  // Configuraciones específicas por tipo
  host?: string
  port?: number
  database_name?: string
  username?: string
  password_encrypted?: string
  file_path?: string
  file_config?: Record<string, any>
  api_base_url?: string
  api_auth_type?: ApiAuthType
  api_auth_config?: Record<string, any>
  options?: Record<string, any>
  
  // Campos comunes
  status?: 'active' | 'inactive' | 'testing' | 'error'
  created_at?: Date
  updated_at?: Date
  company_id?: string
  is_active?: boolean
  created_by?: string
  metadata?: Record<string, any>
}

export class Connection extends AggregateRoot<ConnectionProps> {
  private constructor(props: ConnectionProps, id?: UniqueEntityID) {
    super(props, id)
  }

  get connectionId(): ConnectionId {
    return ConnectionId.create(this.id)
  }

  public static create(props: ConnectionProps, id?: UniqueEntityID): Result<Connection> {
    const guardResult = Guard.againstNullOrUndefinedBulk([
      { argument: props.name, argumentName: 'name' },
      { argument: props.driver, argumentName: 'driver' },
    ])

    if (!guardResult.succeeded)
      return Result.fail<Connection>(guardResult.message)

    // Validaciones específicas por tipo de driver
    const validationResult = Connection.validateDriverConfig(props)
    if (!validationResult.succeeded)
      return Result.fail<Connection>(validationResult.message)

    const connection = new Connection({
      ...props,
      created_at: props.created_at || new Date(),
      updated_at: props.updated_at || new Date(),
      is_active: props.is_active ?? true,
      status: props.status || 'inactive',
    }, id)

    const isNew = !id
    if (isNew)
      connection.addDomainEvent(new ConnectionCreated(connection))

    return Result.ok<Connection>(connection)
  }

  private static validateDriverConfig(props: ConnectionProps): Result<void> {
    switch (props.driver) {
      case 'mysql':
      case 'postgresql':
      case 'sqlserver':
      case 'oracle':
      case 'sqlite':
        return Connection.validateDatabaseConfig(props)
      case 'api':
        return Connection.validateApiConfig(props)
      case 'file':
        return Connection.validateFileConfig(props)
      default:
        return Result.fail<void>(`Unsupported driver: ${props.driver}`)
    }
  }

  private static validateDatabaseConfig(props: ConnectionProps): Result<void> {
    const requiredFields = ['host', 'port', 'database_name', 'username']
    const missingFields = requiredFields.filter(field => !props[field])
    
    if (missingFields.length > 0) {
      return Result.fail<void>(`Missing required fields for database connection: ${missingFields.join(', ')}`)
    }

    return Result.ok<void>()
  }

  private static validateApiConfig(props: ConnectionProps): Result<void> {
    if (!props.api_base_url) {
      return Result.fail<void>('API base URL is required for API connections')
    }

    if (props.api_auth_type && !['none', 'bearer', 'basic', 'api_key'].includes(props.api_auth_type)) {
      return Result.fail<void>('Invalid API auth type')
    }

    return Result.ok<void>()
  }

  private static validateFileConfig(props: ConnectionProps): Result<void> {
    if (!props.file_path) {
      return Result.fail<void>('File path is required for file connections')
    }

    if (!props.file_config?.format) {
      return Result.fail<void>('File format is required for file connections')
    }

    return Result.ok<void>()
  }

  public update(props: Partial<ConnectionProps>): Result<void> {
    const guardResult = Guard.againstNullOrUndefined(props, 'props')

    if (!guardResult.succeeded)
      return Result.fail<void>(guardResult.message)

    // Validar configuración si se está cambiando el driver
    if (props.driver && props.driver !== this.props.driver) {
      const validationResult = Connection.validateDriverConfig({ ...this.props, ...props })
      if (!validationResult.succeeded)
        return Result.fail<void>(validationResult.message)
    }

    this.props.updated_at = new Date()
    Object.assign(this.props, props)

    this.addDomainEvent(new ConnectionUpdated(this))

    return Result.ok<void>()
  }

  public delete(): Result<void> {
    this.addDomainEvent(new ConnectionDeleted(this))

    return Result.ok<void>()
  }

  // Getters
  get id(): string {
    return this.props.id
  }

  get name(): string {
    return this.props.name
  }

  get description(): string {
    return this.props.description
  }

  get driver(): ConnectionDriver {
    return this.props.driver
  }

  get host(): string {
    return this.props.host
  }

  get port(): number {
    return this.props.port
  }

  get database_name(): string {
    return this.props.database_name
  }

  get username(): string {
    return this.props.username
  }

  get password_encrypted(): string {
    return this.props.password_encrypted
  }

  get file_path(): string {
    return this.props.file_path
  }

  get file_config(): Record<string, any> {
    return this.props.file_config
  }

  get api_base_url(): string {
    return this.props.api_base_url
  }

  get api_auth_type(): ApiAuthType {
    return this.props.api_auth_type
  }

  get api_auth_config(): Record<string, any> {
    return this.props.api_auth_config
  }

  get options(): Record<string, any> {
    return this.props.options
  }

  get status(): 'active' | 'inactive' | 'testing' | 'error' {
    return this.props.status
  }

  get created_at(): Date {
    return this.props.created_at
  }

  get updated_at(): Date {
    return this.props.updated_at
  }

  get company_id(): string {
    return this.props.company_id
  }

  get is_active(): boolean {
    return this.props.is_active
  }

  get created_by(): string {
    return this.props.created_by
  }

  get metadata(): Record<string, any> {
    return this.props.metadata
  }

  // Business Methods
  public isDatabaseConnection(): boolean {
    return ['mysql', 'postgresql', 'sqlserver', 'oracle', 'sqlite'].includes(this.props.driver)
  }

  public isApiConnection(): boolean {
    return this.props.driver === 'api'
  }

  public isFileConnection(): boolean {
    return this.props.driver === 'file'
  }

  public getConnectionConfig(): DatabaseConnectionConfig | ApiConnectionConfig | FileConnectionConfig {
    switch (this.props.driver) {
      case 'mysql':
      case 'postgresql':
      case 'sqlserver':
      case 'oracle':
      case 'sqlite':
        return {
          host: this.props.host,
          port: this.props.port,
          database_name: this.props.database_name,
          username: this.props.username,
          password: this.props.password_encrypted,
          options: this.props.options,
        } as DatabaseConnectionConfig
      case 'api':
        return {
          api_base_url: this.props.api_base_url,
          api_auth_type: this.props.api_auth_type,
          api_auth_config: this.props.api_auth_config,
        } as ApiConnectionConfig
      case 'file':
        return {
          file_path: this.props.file_path,
          file_config: this.props.file_config,
        } as FileConnectionConfig
      default:
        throw new Error(`Unsupported driver: ${this.props.driver}`)
    }
  }

  addDataSource(item: any): Result<void> {
    // Business logic for adding DataSource
    return Result.ok<void>()
  }
}
