// Generated by DDD Module Generator on 2025-07-04

import { Report } from '../../domain/entities/Report'
import { ReportResponseDto } from '../dtos/ReportDtos'
import { UniqueEntityID } from '../../../shared/domain/base/UniqueEntityID'

export class ReportMapper {
  public static toDto(report: Report): ReportResponseDto {
    return {
      id: report.id.toString(),
      data_source_id: report.props.data_source_id,
      name: report.props.name,
      description: report.props.description,
      selected_fields: report.props.selected_fields,
      export_formats: report.props.export_formats,
      default_filters: report.props.default_filters,
      is_public: report.props.is_public,
      created_at: report.props.created_at,
      updated_at: report.props.updated_at,,
      createdAt: report.props.createdAt,
      updatedAt: report.props.updatedAt
    }
  }

  public static toDomain(raw: any): Report {
    const reportOrError = Report.create(
      {
        data_source_id: raw.data_source_id,
        name: raw.name,
        description: raw.description,
        selected_fields: raw.selected_fields,
        export_formats: raw.export_formats,
        default_filters: raw.default_filters,
        is_public: raw.is_public,
        created_at: raw.created_at,
        updated_at: raw.updated_at,,
        createdAt: raw.created_at ? new Date(raw.created_at) : new Date(),
        updatedAt: raw.updated_at ? new Date(raw.updated_at) : new Date()
      },
      new UniqueEntityID(raw.id)
    )

    return reportOrError.isSuccess 
      ? reportOrError.getValue() 
      : null
  }

  public static toPersistence(report: Report): any {
    return {
      id: report.id.toString(),
      data_source_id: report.props.data_source_id,
      name: report.props.name,
      description: report.props.description,
      selected_fields: report.props.selected_fields,
      export_formats: report.props.export_formats,
      default_filters: report.props.default_filters,
      is_public: report.props.is_public,
      created_at: report.props.created_at,
      updated_at: report.props.updated_at,,
      created_at: report.props.createdAt,
      updated_at: report.props.updatedAt
    }
  }
}
