// Generated by DDD Module Generator on 2025-07-04

import { ValueObject } from '../../../shared/domain/base/ValueObject'
import { UniqueEntityID } from '../../../shared/domain/base/UniqueEntityID'

interface DataSourceIdProps {
  value: string
}

export class DataSourceId extends ValueObject<DataSourceIdProps> {
  get value(): string {
    return this.props.value
  }

  private constructor(props: DataSourceIdProps) {
    super(props)
  }

  public static create(id: UniqueEntityID | string): DataSourceId {
    const idValue = id instanceof UniqueEntityID ? id.toString() : id

    return new DataSourceId({ value: idValue })
  }

  public static createUnique(): DataSourceId {
    return new DataSourceId({ value: new UniqueEntityID().toString() })
  }
}
