// Generated by DDD Module Generator on 2025-07-04

// Module exports
export { default as DynamicReportsRoutes } from './config/routes'
export { default as DynamicReportsMenu } from './config/menu'

// Entity exports
export * from './Connection'
export * from './DataSource'
export * from './Report'
export * from './Execution'

// Store exports
export { useConnectionStore } from './Connection/presentation/stores/connectionStore'
export { useDataSourceStore } from './DataSource/presentation/stores/dataSourceStore'
export { useReportStore } from './Report/presentation/stores/reportStore'
export { useExecutionStore } from './Execution/presentation/stores/executionStore'

// Component exports
export { default as ConnectionTable } from './Connection/presentation/components/organisms/ConnectionTable.vue'
export { default as DataSourceTable } from './DataSource/presentation/components/organisms/DataSourceTable.vue'
export { default as ReportTable } from './Report/presentation/components/organisms/ReportTable.vue'
export { default as ExecutionTable } from './Execution/presentation/components/organisms/ExecutionTable.vue'
export { default as ConnectionForm } from './Connection/presentation/components/organisms/ConnectionForm.vue'
export { default as DataSourceForm } from './DataSource/presentation/components/organisms/DataSourceForm.vue'
export { default as DataSourceConnectStep } from './DataSource/presentation/components/organisms/DataSourceConnectStep.vue'
export { default as DataSourceModelStep } from './DataSource/presentation/components/organisms/DataSourceModelStep.vue'
export { default as DataSourceFilterStep } from './DataSource/presentation/components/organisms/DataSourceFilterStep.vue'
export { default as ReportForm } from './Report/presentation/components/organisms/ReportForm.vue'
export { default as ExecutionForm } from './Execution/presentation/components/organisms/ExecutionForm.vue'
export { default as ConnectionDetail } from './Connection/presentation/components/organisms/ConnectionDetail.vue'
export { default as DataSourceDetail } from './DataSource/presentation/components/organisms/DataSourceDetail.vue'
export { default as ReportDetail } from './Report/presentation/components/organisms/ReportDetail.vue'
export { default as ExecutionDetail } from './Execution/presentation/components/organisms/ExecutionDetail.vue'

// View exports
export { default as ConnectionList } from './Connection/presentation/views/ConnectionList.vue'
export { default as DataSourceList } from './DataSource/presentation/views/DataSourceList.vue'
export { default as ReportList } from './Report/presentation/views/ReportList.vue'
export { default as ExecutionList } from './Execution/presentation/views/ExecutionList.vue'
export { default as ConnectionAdd } from './Connection/presentation/views/ConnectionAdd.vue'
export { default as ReportAdd } from './Report/presentation/views/ReportAdd.vue'
export { default as ExecutionAdd } from './Execution/presentation/views/ExecutionAdd.vue'
export { default as ConnectionEdit } from './Connection/presentation/views/ConnectionEdit.vue'
export { default as DataSourceEdit } from './DataSource/presentation/views/DataSourceEdit.vue'
export { default as ReportEdit } from './Report/presentation/views/ReportEdit.vue'
export { default as ExecutionEdit } from './Execution/presentation/views/ExecutionEdit.vue'
export { default as ConnectionDelete } from './Connection/presentation/views/ConnectionDelete.vue'
export { default as DataSourceDelete } from './DataSource/presentation/views/DataSourceDelete.vue'
export { default as ReportDelete } from './Report/presentation/views/ReportDelete.vue'
export { default as ExecutionDelete } from './Execution/presentation/views/ExecutionDelete.vue'
export { default as ConnectionView } from './Connection/presentation/views/ConnectionView.vue'
export { default as DataSourceView } from './DataSource/presentation/views/DataSourceView.vue'
export { default as ReportView } from './Report/presentation/views/ReportView.vue'
export { default as ExecutionView } from './Execution/presentation/views/ExecutionView.vue'

// Composable exports
export { useConnection } from './Connection/presentation/composables/useConnection'
export { useDataSource } from './DataSource/presentation/composables/useDataSource'
export { useReport } from './Report/presentation/composables/useReport'
export { useExecution } from './Execution/presentation/composables/useExecution'

// Validator exports
export { connectionCreateValidation, connectionUpdateValidation } from './Connection/presentation/validators/ConnectionValidators'
export { dataSourceCreateValidation, dataSourceUpdateValidation } from './DataSource/presentation/validators/DataSourceValidators'
export { reportCreateValidation, reportUpdateValidation } from './Report/presentation/validators/ReportValidators'
export { executionCreateValidation, executionUpdateValidation } from './Execution/presentation/validators/ExecutionValidators'
