// Generated by DDD Module Generator on 2025-07-04

const dbConfig = {
  tableName: 'dynamic-reports',
  version: 1,
  stores: [
    {
      name: 'dynamic-reports',
      keyPath: 'id',
      indexes: [
        { name: 'createdAt', keyPath: 'createdAt' },
        { name: 'updatedAt', keyPath: 'updatedAt' },
      ],
    },
  ],
}

export default dbConfig
