// Generated by DDD Module Generator on 2025-07-04

import { useRouter } from 'vue-router'
import { useI18n } from 'vue-i18n'

// Import module routes and menu
import DynamicReportsRoutes from './config/routes'
import DynamicReportsMenu from './config/menu'

export class DynamicReportsInstaller {
  private router: any
  private i18n: any

  constructor() {
    this.setupDependencies()
  }

  private setupDependencies() {
    // Get router from the current app context
    try {
      this.router = useRouter()
    }
    catch (error) {
      console.warn('Router not available in current context, will register routes later')
      this.router = null
    }

    // Get i18n from the current app context
    try {
      this.i18n = useI18n()
    }
    catch (error) {
      console.warn('i18n not available in current context')
      this.i18n = null
    }
  }

  install() {
    try {
      // Register routes
      this.registerRoutes()

      // Add menu items
      this.addMenuItems()

      // Add translations
      this.addTranslations()

      // Add CASL abilities
      this.addCaslAbilities()

      return true
    }
    catch (error) {
      console.error('❌ Error installing DynamicReports module:', error)

      return false
    }
  }

  private registerRoutes() {
    if (!this.router) {
      console.warn('Router not available, routes will be registered when router is available')

      return
    }

    DynamicReportsRoutes.forEach(route => {
      this.router.addRoute(route)
    })
  }

  private addMenuItems() {
    // Add menu items to the main navigation
    if (window.mainMenu)
      window.mainMenu.push(...DynamicReportsMenu)
  }

  private addTranslations() {
    // console.log('🌐 Adding translations...')

    const translations = {
      en: {
        'dynamic-reports': {
          title: 'DynamicReports',
          description: 'DynamicReports Management Module',
          dashboard: 'DynamicReports Dashboard',
          settings: 'DynamicReports Settings',
        },
        'connection': {
          title: 'Connection',
          list: 'Connection List',
          create: 'Create Connection',
          edit: 'Edit Connection',
          delete: 'Delete Connection',
          view: 'View Connection',
          add: 'Add Connection',
          update: 'Update Connection',
          search: 'Search Connections',
          export: 'Export Connections',
          deleteSelected: 'Delete Selected Connections',
          confirmDelete: 'Are you sure you want to delete this Connection?',
          deleteItemDescription: 'This action cannot be undone.',
          cancel: 'Cancel',
          confirm: 'Confirm',
          save: 'Save',
          loading: 'Loading...',
          error: 'Error',
          success: 'Success',
        },
        'data-source': {
          title: 'DataSource',
          list: 'DataSource List',
          create: 'Create DataSource',
          edit: 'Edit DataSource',
          delete: 'Delete DataSource',
          view: 'View DataSource',
          add: 'Add DataSource',
          update: 'Update DataSource',
          search: 'Search DataSources',
          export: 'Export DataSources',
          deleteSelected: 'Delete Selected DataSources',
          confirmDelete: 'Are you sure you want to delete this DataSource?',
          deleteItemDescription: 'This action cannot be undone.',
          cancel: 'Cancel',
          confirm: 'Confirm',
          save: 'Save',
          loading: 'Loading...',
          error: 'Error',
          success: 'Success',
        },
        'report': {
          title: 'Report',
          list: 'Report List',
          create: 'Create Report',
          edit: 'Edit Report',
          delete: 'Delete Report',
          view: 'View Report',
          add: 'Add Report',
          update: 'Update Report',
          search: 'Search Reports',
          export: 'Export Reports',
          deleteSelected: 'Delete Selected Reports',
          confirmDelete: 'Are you sure you want to delete this Report?',
          deleteItemDescription: 'This action cannot be undone.',
          cancel: 'Cancel',
          confirm: 'Confirm',
          save: 'Save',
          loading: 'Loading...',
          error: 'Error',
          success: 'Success',
        },
        'execution': {
          title: 'Execution',
          list: 'Execution List',
          create: 'Create Execution',
          edit: 'Edit Execution',
          delete: 'Delete Execution',
          view: 'View Execution',
          add: 'Add Execution',
          update: 'Update Execution',
          search: 'Search Executions',
          export: 'Export Executions',
          deleteSelected: 'Delete Selected Executions',
          confirmDelete: 'Are you sure you want to delete this Execution?',
          deleteItemDescription: 'This action cannot be undone.',
          cancel: 'Cancel',
          confirm: 'Confirm',
          save: 'Save',
          loading: 'Loading...',
          error: 'Error',
          success: 'Success',
        },
      },
    }

    if (this.i18n && this.i18n.global)
      this.i18n.global.mergeLocaleMessage('en', translations.en)
  }

  private addCaslAbilities() {
    // Add CASL abilities for module permissions
    const abilities = [
      { action: 'read', subject: 'connections' },
      { action: 'read', subject: 'data-sources' },
      { action: 'read', subject: 'reports' },
      { action: 'read', subject: 'executions' },
      { action: 'create', subject: 'connections' },
      { action: 'create', subject: 'data-sources' },
      { action: 'create', subject: 'reports' },
      { action: 'create', subject: 'executions' },
      { action: 'update', subject: 'connections' },
      { action: 'update', subject: 'data-sources' },
      { action: 'update', subject: 'reports' },
      { action: 'update', subject: 'executions' },
      { action: 'delete', subject: 'connections' },
      { action: 'delete', subject: 'data-sources' },
      { action: 'delete', subject: 'reports' },
      { action: 'delete', subject: 'executions' },
    ]

    if (window.caslAbilities)
      window.caslAbilities.push(...abilities)
  }

  uninstall() {
    try {
      // Remove routes
      this.removeRoutes()

      // Remove menu items
      this.removeMenuItems()

      // Remove translations
      this.removeTranslations()

      // Remove CASL abilities
      this.removeCaslAbilities()

      return true
    }
    catch (error) {
      console.error('❌ Error uninstalling DynamicReports module:', error)

      return false
    }
  }

  private removeRoutes() {
    // Remove module routes
    if (this.router) {
      DynamicReportsRoutes.forEach(route => {
        const existingRoute = this.router.getRoutes().find(r => r.name === route.name)
        if (existingRoute)
          this.router.removeRoute(route.name)
      })
    }
  }

  private removeMenuItems() {
    // Remove menu items
    if (window.mainMenu) {
      window.mainMenu = window.mainMenu.filter(item =>
        !DynamicReportsMenu.some(menuItem => menuItem.to === item.to),
      )
    }
  }

  private removeTranslations() {
    // Remove translations
    if (this.i18n && this.i18n.global) {
      // Implementation depends on i18n setup
    }
  }

  private removeCaslAbilities() {
    // Remove CASL abilities
    if (window.caslAbilities) {
      window.caslAbilities = window.caslAbilities.filter(ability =>
        !DynamicReportsMenu.some(menuItem =>
          ability.subject === menuItem.subject,
        ),
      )
    }
  }
}

// Auto-install function
export function installDynamicReportsModule() {
  const installer = new DynamicReportsInstaller()

  return installer.install()
}

// Auto-uninstall function
export function uninstallDynamicReportsModule() {
  const installer = new DynamicReportsInstaller()

  return installer.uninstall()
}

// Default export for plugin usage
export default {
  install: installDynamicReportsModule,
  uninstall: uninstallDynamicReportsModule,
  installer: DynamicReportsInstaller,
}

// Auto-install on import (optional)
if (typeof window !== 'undefined' && window.autoInstallModules !== false)
  installDynamicReportsModule()
