// Generated by DDD Module Generator on 2025-07-04

export interface UpdateConnectionCommand {
  id: string
  name: string
  driver: 'mysql' | 'pgsql' | 'sqlsrv' | 'oracle' | 'sqlite'
  host: string
  port: number
  database_name: string
  username: string
  password: string
  status?: 'active' | 'inactive' | 'testing' | 'error'
}
