// Generated by DDD Module Generator on 2025-07-04

export interface CreateDataSourceDto {
  connection_id: string
  name: string
  type: 'custom_sql' | 'visual_builder' | 'hybrid'
  custom_sql?: string
  available_fields: Record<string, any>
}

export interface UpdateDataSourceDto {
  id: string
  connection_id: string
  name: string
  type: 'custom_sql' | 'visual_builder' | 'hybrid'
  custom_sql?: string
  available_fields: Record<string, any>
}

export interface DataSourceResponseDto {
  id: string
  connection_id: string
  name: string
  type: 'custom_sql' | 'visual_builder' | 'hybrid'
  custom_sql: string
  available_fields: Record<string, any>
  created_at: Date
  updated_at: Date
  createdAt: Date
  updatedAt: Date
}
