// Generated by DDD Module Generator on 2025-07-04

import { ValueObject } from '../../../shared/domain/base/ValueObject'
import { UniqueEntityID } from '../../../shared/domain/base/UniqueEntityID'

interface ConnectionIdProps {
  value: string
}

export class ConnectionId extends ValueObject<ConnectionIdProps> {
  get value(): string {
    return this.props.value
  }

  private constructor(props: ConnectionIdProps) {
    super(props)
  }

  public static create(id: UniqueEntityID | string): ConnectionId {
    const idValue = id instanceof UniqueEntityID ? id.toString() : id

    return new ConnectionId({ value: idValue })
  }

  public static createUnique(): ConnectionId {
    return new ConnectionId({ value: new UniqueEntityID().toString() })
  }
}
