// Generated by DDD Module Generator on 2025-07-04

import type { Execution } from '../entities/Execution'
import type { ExecutionId } from '../valueObjects/ExecutionId'

export interface ExecutionRepository {
  exists(executionId: ExecutionId): Promise<boolean>
  getExecutionById(executionId: ExecutionId): Promise<Execution>
  save(execution: Execution): Promise<void>
  delete(executionId: ExecutionId): Promise<void>
  getAll(): Promise<Execution[]>
  getAllPaginated(page: number, limit: number): Promise<{
    executions: Execution[]
    totalPages: number
    total: number
  }>
}
