// Generated by DDD Module Generator on 2025-07-04

export class ReportValidationError extends Error {
  constructor(message: string = 'Report validation failed') {
    super(message)
    this.name = 'ReportValidationError'
  }
}
