// Generated by DDD Module Generator on 2025-07-04

export class ReportAlreadyExists extends Error {
  constructor(message: string = 'Report already exists') {
    super(message)
    this.name = 'ReportAlreadyExists'
  }
}
