// Generated by DDD Module Generator on 2025-07-04

export class ReportNotFound extends Error {
  constructor(message: string = 'Report not found') {
    super(message)
    this.name = 'ReportNotFound'
  }
}
