<!-- Generated by DDD Module Generator on 2025-07-04 -->
<script setup lang="ts">
import { computed, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import { useReportStore } from '../stores/reportStore'
import ReportForm from '../components/organisms/ReportForm.vue'

const route = useRoute()
const store = useReportStore()
const currentItem = computed(() => store.currentItem)

onMounted(async () => {
  await store.fetchById(route.params.id as string)
})
</script>

<template>
  <ReportForm
    mode="edit"
    :initial-data="currentItem"
  />
</template>
