<!-- Generated by DDD Module Generator on 2025-07-04 -->
<script setup lang="ts">
import { computed, onMounted, onUnmounted, reactive, ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import { useRoute, useRouter } from 'vue-router'
import { useReportStore } from '../stores/reportStore'
import ReportFiltersPanel from '../components/organisms/ReportFiltersPanel.vue'
import ReportToolbar from '../components/organisms/ReportToolbar.vue'
import ShareDialogOrganism from '../components/organisms/ShareDialogOrganism.vue'

import ReportDataTable from '../components/organisms/ReportDataTable.vue'

// Types
interface ReportConfig {
  name: string
  description?: string
  basicInfo: any
  selectedFields: any[]
  filters: any[]
  sorting: any
  exportOptions: any
  advanced?: any
  meta?: any
}

interface FilterValue {
  field: string
  operator: string
  value: any
}

interface SortingRule {
  field: string
  direction: 'ASC' | 'DESC'
}

const emit = defineEmits<{
  refresh: []
  export: [format: string]
  share: []
}>()

const { t: _t } = useI18n()
const router = useRouter()
const route = useRoute()
const store = useReportStore()

// Estado principal
const loading = ref(false)
const error = ref<string | null>(null)
const reportData = ref<any[]>([])
const totalRecords = ref(0)
const lastUpdated = ref<Date>(new Date())
const isFullscreen = ref(false)

// Configuración del reporte
const reportConfig = ref<ReportConfig | null>(null)

// Paginación - ahora manejada por el store

// Filtros aplicados
const appliedFilters = ref<FilterValue[]>([])
const showFilterPanel = ref(true)
const quickSearchQuery = ref('')

// Ordenamiento
const activeSorting = ref<SortingRule[]>([])

// Columnas
const visibleColumns = ref<string[]>([])
const columnWidths = ref<Record<string, number>>({})
const frozenColumns = ref<string[]>([])

// Exportación
const showExportDialog = ref(false)
const exportLoading = ref(false)

// Vista
const viewMode = ref<'table' | 'card' | 'chart'>('table')
const density = ref<'comfortable' | 'compact' | 'default'>('default')
const showTotals = ref(true)

// Compartir
const showShareDialog = ref(false)
const shareLink = ref('')

// Mapa reactivo para los valores de los filtros
const appliedFiltersMap = reactive<Record<string, any>>({})

// Inicializar columnas visibles
const initializeReportConfig = () => {
  if (!reportConfig.value)
    return

  // Solo inicializar si visibleColumns está vacío
  if (visibleColumns.value.length === 0) {
    const selected = reportConfig.value.selectedFields && reportConfig.value.selectedFields.length > 0
      ? reportConfig.value.selectedFields.filter(f => f.visible !== false).map(f => f.field)
      : []

    const calculated = (reportConfig.value.advanced?.calculatedFields || [])
      .filter(f => f.enabled !== false)
      .map(f => f.id)

    visibleColumns.value = Array.from(new Set([...selected, ...calculated]))
  }

  // Siempre inicializar anchos
  if (reportConfig.value.selectedFields) {
    reportConfig.value.selectedFields.forEach(field => {
      if (!columnWidths.value[field.field])
        columnWidths.value[field.field] = field.width || 150
    })
  }

  if (reportConfig.value.advanced?.calculatedFields) {
    reportConfig.value.advanced.calculatedFields.forEach(field => {
      if (!columnWidths.value[field.id])
        columnWidths.value[field.id] = 150
    })
  }

  // Inicializar ordenamiento
  if (reportConfig.value.sorting) {
    const sortingRules: SortingRule[] = []
    if (reportConfig.value.sorting.primary?.field) {
      sortingRules.push({
        field: reportConfig.value.sorting.primary.field,
        direction: reportConfig.value.sorting.primary.direction || 'ASC',
      })
    }
    if (reportConfig.value.sorting.secondary?.field) {
      sortingRules.push({
        field: reportConfig.value.sorting.secondary.field,
        direction: reportConfig.value.sorting.secondary.direction || 'ASC',
      })
    }
    activeSorting.value = sortingRules
  }
}

onMounted(async () => {
  await loadReportData()
})

// Computed
// Normaliza los datos para que los keys sean los de selectedFields (field) y calculatedFields (id), usando el label, alias, field, name o id del row
function normalizeDataBySelectedFields(data: any[], selectedFields: any[], calculatedFields: any[] = []) {
  if ((!selectedFields || selectedFields.length === 0) && (!calculatedFields || calculatedFields.length === 0))
    return data

  return data.map(row => {
    const newRow: Record<string, any> = {}

    // Campos normales
    selectedFields.forEach(field => {
      newRow[field.field] = row[field.label] ?? row[field.alias] ?? row[field.field] ?? row[field.name] ?? null
    })

    // Campos calculados
    calculatedFields.forEach(field => {
      newRow[field.id] = row[field.name] ?? row[field.id] ?? null
    })

    return newRow
  })
}

// Normaliza los datos usando meta.columns si existe, si no usa selectedFields/calculatedFields
function normalizeDataWithMetaColumns(data: any[], metaColumns: any[]): any[] {
  if (!metaColumns || metaColumns.length === 0)
    return data

  return data.map(row => {
    const newRow: Record<string, any> = {}

    metaColumns.forEach(col => {
      newRow[col.key] = row[col.key] ?? row[col.label] ?? null
    })

    return newRow
  })
}

const paginatedData = computed(() => {
  const metaColumns = reportConfig.value?.meta?.columns || store.meta?.columns || []
  if (metaColumns.length > 0)
    return normalizeDataWithMetaColumns(store.reportData, metaColumns)

  const selectedFields = reportConfig.value?.selectedFields || []
  const calculatedFields = reportConfig.value?.advanced?.calculatedFields || []

  return normalizeDataBySelectedFields(store.reportData, selectedFields, calculatedFields)
})

const availableColumns = computed(() => {
  const columns = []

  // Columnas del meta (prioridad)
  if (reportConfig.value?.meta?.columns) {
    reportConfig.value.meta.columns.forEach(col => {
      columns.push({
        field: col.key,
        label: col.label,
        type: col.type || 'text',
      })
    })

    return columns
  }

  // Columnas de selectedFields
  if (reportConfig.value?.selectedFields) {
    reportConfig.value.selectedFields.forEach(field => {
      columns.push({
        field: field.field,
        label: field.label || field.field,
        type: field.type,
      })
    })
  }

  // Columnas calculadas
  if (reportConfig.value?.advanced?.calculatedFields) {
    reportConfig.value.advanced.calculatedFields.forEach(field => {
      columns.push({
        field: field.id,
        label: field.name || field.id,
        type: 'calculated',
      })
    })
  }

  // Si no hay nada configurado pero hay datos, usar las keys
  if (columns.length === 0 && store.reportData && store.reportData.length > 0) {
    Object.keys(store.reportData[0]).forEach(key => {
      columns.push({
        field: key,
        label: key,
        type: 'text',
      })
    })
  }

  return columns
})

const availableExportFormats = computed(() => {
  if (!reportConfig.value?.exportOptions)
    return []

  const formats = []

  // Formato nuevo con array de formats
  if (reportConfig.value.exportOptions.formats)
    return reportConfig.value.exportOptions.formats.filter((f: any) => f.enabled)

  // Formato antiguo
  if (reportConfig.value.exportOptions.excel?.enabled) {
    formats.push({
      id: 'excel',
      name: 'Excel',
      icon: 'tabler-file-spreadsheet',
      color: 'success',
    })
  }
  if (reportConfig.value.exportOptions.pdf?.enabled) {
    formats.push({
      id: 'pdf',
      name: 'PDF',
      icon: 'tabler-file-type-pdf',
      color: 'error',
    })
  }
  if (reportConfig.value.exportOptions.csv?.enabled) {
    formats.push({
      id: 'csv',
      name: 'CSV',
      icon: 'tabler-file-text',
      color: 'info',
    })
  }

  return formats
})

const reportTitle = computed(() => {
  return reportConfig.value?.basicInfo?.name || 'Reporte sin título'
})

const reportDescription = computed(() => {
  return reportConfig.value?.description || reportConfig.value?.basicInfo?.description
})

// Helpers
const getFieldConfig = (fieldName: string) => {
  return reportConfig.value?.selectedFields.find(f => f.field === fieldName)
}

const generateSampleData = () => {
  if (!reportConfig.value)
    return []

  // Generar datos de ejemplo basados en los campos configurados
  const data = []
  const numRows = 150

  for (let i = 0; i < numRows; i++) {
    const row: any = {}

    reportConfig.value.selectedFields.forEach(field => {
      switch (field.type) {
        case 'varchar':
        case 'text':
          if (field.field === 'CUENTA')
          row[field.field] = `CUENTA-${1000 + i}`

          else if (field.field === 'USUARIO')
          row[field.field] = ['Juan Pérez', 'María García', 'Carlos López', 'Ana Martínez'][i % 4]

          else if (field.field === 'RFC')
          row[field.field] = `RFC${Math.random().toString(36).substring(2, 15).toUpperCase()}`

          else
          row[field.field] = `Texto ${i + 1}`

          break

        case 'double':
        case 'number':
        case 'integer':
          row[field.field] = Math.round(Math.random() * 10000 * 100) / 100
          break

        case 'date':
        case 'datetime': {
          const date = new Date()

          date.setDate(date.getDate() - Math.floor(Math.random() * 365))
          row[field.field] = date.toISOString().split('T')[0]
          break
        }

        case 'boolean':
          row[field.field] = Math.random() > 0.5
          break

        default:
          row[field.field] = `Valor ${i + 1}`
      }
    })

    data.push(row)
  }

  return data
}

const buildFiltersPayload = () => {
  const filters: any = {}

  // Función recursiva para buscar filtros en grupos anidados
  const findFilterInConfig = (filters: any[], fieldName: string): any => {
    for (const filter of filters) {
      if (filter.type === 'filter' && filter.field === fieldName)
        return filter

      if (filter.type === 'group' && filter.children) {
        const found = findFilterInConfig(filter.children, fieldName)
        if (found)
          return found
      }
    }

    return null
  }

  // Agregar filtros aplicados
  appliedFilters.value.forEach(filter => {
    const fieldConfig = getFieldConfig(filter.field)
    if (fieldConfig) {
      // Convertir el valor según el tipo de campo
      let value = filter.value

      if (fieldConfig.type === 'date' || fieldConfig.type === 'datetime') {
        // Para fechas, asegurar formato correcto
        if (typeof value === 'string')
          value = new Date(value).toISOString().split('T')[0]
      }
      else if (fieldConfig.type === 'number' || fieldConfig.type === 'double' || fieldConfig.type === 'integer') {
        // Para números, convertir a número
        value = Number.parseFloat(value)
      }

      filters[filter.field] = value
    }
  })

  // Agregar búsqueda rápida si existe
  if (quickSearchQuery.value)
    filters._search = quickSearchQuery.value

  return filters
}

const buildSortingPayload = () => {
  if (activeSorting.value.length === 0)
    return null

  return activeSorting.value.map(sort => ({
    field: sort.field,
    direction: sort.direction,
  }))
}

// Métodos
const loadReportData = async () => {
  loading.value = true
  error.value = null

  try {
    const reportId = route.params.id as string
    if (reportId) {
      await store.fetchById(reportId)

      // Obtener datos del localStorage si existen
      const savedData = localStorage.getItem('reportWizardProgress')
      if (savedData) {
        const parsedData = JSON.parse(savedData)
        if (parsedData.wizardData) {
          reportConfig.value = parsedData.wizardData
          initializeReportConfig()

          // Ahora cargar datos reales del backend usando el store
          await loadRealDataFromBackend(reportId)
        }
      }
    }
  }
  catch (err) {
    error.value = 'Error al cargar los datos del reporte'
    console.error(err)
  }
  finally {
    loading.value = false
  }
}

const loadRealDataFromBackend = async (reportId: string) => {
  try {
    const payload = {
      report_id: reportId,
      export_format: 'table',
      filters: buildFiltersPayload(),
      sorting: buildSortingPayload(),
      pagination: {
        page: store.page,
        per_page: store.itemsPerPage,
      },
    }

    await store.executeReport(payload)

    reportData.value = store.reportData
    totalRecords.value = store.reportTotalRecords
    lastUpdated.value = new Date()

    // CRÍTICO: Actualizar visibleColumns con TODAS las columnas del response
    if (store.meta?.columns && store.meta.columns.length > 0) {
      // Actualizar meta en reportConfig
      if (!reportConfig.value) {
        reportConfig.value = {
          basicInfo: {},
          selectedFields: [],
          filters: [],
          sorting: {},
          exportOptions: {},
        }
      }

      if (!reportConfig.value.meta)
        reportConfig.value.meta = {}

      reportConfig.value.meta.columns = store.meta.columns

      // IMPORTANTE: Actualizar visibleColumns con TODAS las columnas del meta
      const allColumnKeys = store.meta.columns.map(col => col.key)

      visibleColumns.value = allColumnKeys

      // Actualizar anchos de columna para las nuevas columnas
      store.meta.columns.forEach(col => {
        if (!columnWidths.value[col.key])
          columnWidths.value[col.key] = 150
      })
    }

    // Fallback: Si no hay meta pero hay datos, usar las keys de los datos
    else if (store.reportData && store.reportData.length > 0) {
      const dataKeys = Object.keys(store.reportData[0])

      visibleColumns.value = dataKeys

      dataKeys.forEach(key => {
        if (!columnWidths.value[key])
          columnWidths.value[key] = 150
      })
    }

    if (store.reportError) {
      error.value = store.reportError
      reportData.value = generateSampleData()
      totalRecords.value = reportData.value.length
    }
  }
  catch (err) {
    console.error('Error al cargar datos del backend:', err)
    error.value = 'Error al cargar los datos del reporte desde el servidor'
    reportData.value = generateSampleData()
    totalRecords.value = reportData.value.length
  }
}

// Formatear valor según el tipo de campo
const formatCellValue = (value: any, field: any) => {
  if (value === null || value === undefined)
    return '-'

  switch (field.format) {
    case 'number': {
      const num = Number.parseFloat(value)
      if (Number.isNaN(num))
        return value

      return field.thousandsSeparator
        ? num.toLocaleString('es-MX', { minimumFractionDigits: field.decimals || 0, maximumFractionDigits: field.decimals || 0 })
        : num.toFixed(field.decimals || 2)
    }

    case 'currency': {
      const curr = Number.parseFloat(value)
      if (Number.isNaN(curr))
        return value

      return new Intl.NumberFormat('es-MX', {
        style: 'currency',
        currency: 'MXN',
        minimumFractionDigits: field.decimals || 2,
        maximumFractionDigits: field.decimals || 2,
      }).format(curr)
    }

    case 'percentage': {
      const perc = Number.parseFloat(value)
      if (Number.isNaN(perc))
        return value

      return `${(perc * 100).toFixed(field.decimals || 2)}%`
    }

    case 'date':
      try {
        return new Date(value).toLocaleDateString('es-MX')
      }
      catch {
        return value
      }

    case 'datetime':
      try {
        return new Date(value).toLocaleString('es-MX')
      }
      catch {
        return value
      }

    case 'boolean':
      return value ? 'Sí' : 'No'

    default:
      return value
  }
}

// Actualizar función de aplicar filtro
const _applyFilter = (filter: any, value: any) => {
  appliedFilters.value = [
    ...appliedFilters.value.filter(f => f.field !== filter.field),
    { field: filter.field, operator: filter.operator, value },
  ]
}

const applyAllFilters = () => {
  // Función recursiva para buscar filtros en grupos anidados
  const findFilterInConfig = (filters: any[], fieldName: string): any => {
    for (const filter of filters) {
      if (filter.type === 'filter' && filter.field === fieldName)

        return filter

      if (filter.type === 'group' && filter.children) {
        const found = findFilterInConfig(filter.children, fieldName)
        if (found)
          return found
      }
    }

    return null
  }

  // Aplica todos los filtros del mapa
  appliedFilters.value = Object.entries(appliedFiltersMap)
    .filter(([_, v]) => v !== undefined && v !== null && v !== '')
    .map(([field, value]) => {
      const filter = findFilterInConfig(reportConfig.value?.filters || [], field)

      return filter ? { field, operator: filter.operator || 'equals', value } : null
    })
    .filter(Boolean) as FilterValue[]

  // Recargar datos con los nuevos filtros
  loadRealDataFromBackend(route.params.id as string)
}

const removeFilter = (field: string) => {
  appliedFilters.value = appliedFilters.value.filter(f => f.field !== field)
  loadRealDataFromBackend(route.params.id as string)
}

const clearAllFilters = () => {
  appliedFilters.value = []
  quickSearchQuery.value = ''
  loadRealDataFromBackend(route.params.id as string)
}

// Manejar actualizaciones de filtros desde el componente
const handleFiltersUpdate = (updatedFilters: any[]) => {
  // Actualizar el mapa de filtros aplicados
  Object.keys(appliedFiltersMap).forEach(key => {
    delete appliedFiltersMap[key]
  })

  const extractFilterValues = (filters: any[]) => {
    filters.forEach(filter => {
      if (filter.type === 'filter' && filter.value !== undefined && filter.value !== '' && filter.value !== null)
        appliedFiltersMap[filter.field] = filter.value

      else if (filter.type === 'group' && filter.children)
        extractFilterValues(filter.children)
    })
  }

  extractFilterValues(updatedFilters)
}

// Gestión de ordenamiento
const toggleSort = (field: string) => {
  const existingSort = activeSorting.value.find(s => s.field === field)

  if (existingSort) {
    // Cambiar dirección
    if (existingSort.direction === 'ASC') {
      existingSort.direction = 'DESC'
    }
    else {
      // Eliminar ordenamiento
      activeSorting.value = activeSorting.value.filter(s => s.field !== field)
    }
  }
  else {
    // Agregar nuevo ordenamiento
    activeSorting.value.push({
      field,
      direction: 'ASC',
    })
  }

  // Recargar datos con el nuevo ordenamiento
  loadRealDataFromBackend(route.params.id as string)
}

const getSortIcon = (field: string) => {
  const sort = activeSorting.value.find(s => s.field === field)
  if (!sort)
    return 'tabler-selector'

  return sort.direction === 'ASC' ? 'tabler-sort-ascending' : 'tabler-sort-descending'
}

const getSortIndex = (field: string) => {
  const index = activeSorting.value.findIndex(s => s.field === field)

  return index >= 0 ? index + 1 : null
}

// Gestión de columnas
const toggleColumnVisibility = (field: string) => {
  const index = visibleColumns.value.indexOf(field)
  if (index >= 0)
    visibleColumns.value.splice(index, 1)
  else
    visibleColumns.value.push(field)
}

const freezeColumn = (field: string) => {
  const index = frozenColumns.value.indexOf(field)
  if (index >= 0)
    frozenColumns.value.splice(index, 1)
  else
    frozenColumns.value.push(field)
}

// Exportación
const exportReport = async (format: string) => {
  exportLoading.value = true

  try {
    // Simular exportación
    await new Promise(resolve => setTimeout(resolve, 1500))

    // En producción, esto llamaría a la API para generar el archivo
    emit('export', format)

    // Mostrar mensaje de éxito
    showExportDialog.value = false
  }
  catch (err) {
    console.error('Error al exportar:', err)
  }
  finally {
    exportLoading.value = false
  }
}

// Compartir
const shareReport = () => {
  // Generar link de compartir
  const baseUrl = window.location.origin
  const reportId = route.params.id as string

  shareLink.value = `${baseUrl}/reports/viewer/${reportId}?token=${generateShareToken()}`
  showShareDialog.value = true
}

// Generar token de compartir
const generateShareToken = () => {
  return Math.random().toString(36).substring(2, 15)
}

const copyShareLink = () => {
  navigator.clipboard.writeText(shareLink.value)

  // Mostrar notificación de copiado
}

// Actualización automática
const autoRefreshInterval = computed(() => {
  return reportConfig.value?.basicInfo?.performance?.refreshInterval || 0
})

let refreshTimer: any = null

watch(autoRefreshInterval, newInterval => {
  if (refreshTimer)
    clearInterval(refreshTimer)

  if (newInterval > 0 && reportConfig.value?.basicInfo?.performance?.autoRefresh) {
    refreshTimer = setInterval(() => {
      loadReportData()
    }, newInterval * 1000)
  }
})

onUnmounted(() => {
  if (refreshTimer)
    clearInterval(refreshTimer)
})

// Pantalla completa
const toggleFullscreen = () => {
  if (!document.fullscreenElement) {
    document.documentElement.requestFullscreen()
    isFullscreen.value = true
  }
  else {
    document.exitFullscreen()
    isFullscreen.value = false
  }
}

// Calcular totales
const _calculateTotals = (field: any) => {
  if (!showTotals.value || !['number', 'double', 'integer', 'currency'].includes(field.type))
    return null

  const values = reportData.value.map(row => Number.parseFloat(row[field.field]) || 0)

  switch (field.aggregation) {
    case 'SUM':
      return values.reduce((a, b) => a + b, 0)
    case 'AVG':
      return values.length > 0 ? values.reduce((a, b) => a + b, 0) / values.length : 0
    case 'COUNT':
      return values.length
    case 'MIN':
      return Math.min(...values)
    case 'MAX':
      return Math.max(...values)
    default:
      return values.reduce((a, b) => a + b, 0)
  }
}

// Helpers
const _getFilterConfig = (fieldName: string) => {
  if (!reportConfig.value)
    return null

  // Buscar en los filtros configurados
  const findInFilters = (filters: any[]): any => {
    for (const filter of filters) {
      if (filter.type === 'filter' && filter.field === fieldName)
        return filter

      if (filter.type === 'group' && filter.children) {
        const found = findInFilters(filter.children)
        if (found)
          return found
      }
    }

    return null
  }

  return findInFilters(reportConfig.value.filters || [])
}

// Navegación
const goToReportsList = () => {
  router.push('/reports')
}

const editReport = () => {
  const reportId = route.params.id as string

  router.push(`/reports/edit/${reportId}`)
}

// Manejar cambio de página
const handlePageChange = (page: number) => {
  store.page = page
  loadRealDataFromBackend(route.params.id as string)
}

// Manejar cambio de items por página
const handleItemsPerPageChange = (items: number) => {
  store.itemsPerPage = items
  store.page = 1 // Reset a la primera página
  loadRealDataFromBackend(route.params.id as string)
}
</script>

<template>
  <div
    class="report-viewer"
    :class="{ 'fullscreen-mode': isFullscreen }"
  >
    <ReportToolbar
      :report-title="reportTitle"
      :report-description="reportDescription"
      :last-updated="lastUpdated"
      :loading="loading"
      :is-fullscreen="isFullscreen"
      :view-mode="viewMode"
      :density="density"
      :show-filter-panel="showFilterPanel"
      :available-export-formats="availableExportFormats"
      :frozen-columns="frozenColumns"
      :visible-columns="visibleColumns"
      :visible-columns-fields="availableColumns || []"
      :quick-search-query="quickSearchQuery"
      @go-to-reports-list="goToReportsList"
      @refresh="loadReportData"
      @export="exportReport"
      @share-report="shareReport"
      @edit-report="editReport"
      @toggle-fullscreen="toggleFullscreen"
      @update:view-mode="val => viewMode.value = val"
      @update:density="val => density.value = val"
      @toggle-filter-panel="showFilterPanel = !showFilterPanel"
      @update:quick-search-query="val => quickSearchQuery.value = val"
      @toggle-column-visibility="toggleColumnVisibility"
      @freeze-column="freezeColumn"
    />

    <!-- Contenido principal -->
    <div
      class="report-content"
      :class="{ 'with-filters': showFilterPanel }"
    >
      <!-- Panel de filtros -->
      <ReportFiltersPanel
        v-model="showFilterPanel"
        :applied-filters="appliedFilters"
        :report-config="reportConfig"
        :loading="loading"
        @remove-filter="removeFilter"
        @update:filters="handleFiltersUpdate"
        @apply-filters="applyAllFilters"
        @clear-filters="clearAllFilters"
      />
      <!-- Tabla de datos -->
      <ReportDataTable
        :report-config="reportConfig"
        :visible-columns="visibleColumns"
        :frozen-columns="frozenColumns"
        :column-widths="columnWidths"
        :active-sorting="activeSorting"
        :density="density"
        :is-fullscreen="isFullscreen"
        :paginated-data="paginatedData"
        :store="store"
        :loading="loading"
        :error="error"
        :format-cell-value="formatCellValue"
        :get-sort-icon="getSortIcon"
        :get-sort-index="getSortIndex"
        @toggle-sort="toggleSort"
        @handle-page-change="handlePageChange"
        @handle-items-per-page-change="handleItemsPerPageChange"
      />
    </div>

    <!-- Share Dialog -->
    <ShareDialogOrganism
      v-model="showShareDialog"
      :share-link="shareLink"
      @copy-link="copyShareLink"
    />
  </div>
</template>

<style scoped>
.report-viewer {
  display: flex;
  flex-direction: column;
  block-size: 100%;
}

.report-content {
  display: flex;
  flex: 1;
  gap: 16px;
}

.data-table-container {
  overflow: auto;
}

.sortable-header {
  cursor: pointer;
  user-select: none;
}

.sortable-header:hover {
  background-color: rgb(var(--v-theme-surface-variant));
}

.filter-input-placeholder {
  padding: 8px;
  border: 1px dashed #ccc;
  border-radius: 4px;
  color: #666;
  text-align: center;
}

.fullscreen-mode {
  position: fixed;
  z-index: 9999;
  background: white;
  block-size: 100vh;
  inline-size: 100vw;
  inset-block-start: 0;
  inset-inline-start: 0;
}

.filters-list {
  display: flex;
  flex-direction: column;
  gap: 12px;
}
</style>
