<!-- Generated by DDD Module Generator on 2025-07-04 -->
<script setup lang="ts">
import ReportForm from '../components/organisms/ReportForm.vue'
</script>

<template>
  <ReportForm mode="create" />
</template>
