<!-- Generated by DDD Module Generator on 2025-07-04 -->
<script setup lang="ts">
import { computed, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import { useReportStore } from '../stores/reportStore'
import ReportDetail from '../components/organisms/ReportDetail.vue'

const route = useRoute()
const store = useReportStore()
const currentItem = computed(() => store.currentItem)

onMounted(async () => {
  await store.fetchById(route.params.id as string)
})
</script>

<template>
  <VCard>
    <VCardTitle>
      <h4 class="text-h4 mb-1">
        { title }
      </h4>
      <p class="text-body-1 mb-4">
        { description }
      </p>
    </VCardTitle>

    <VCardText>
      <ReportDetail :report="currentItem" />
    </VCardText>
  </VCard>
</template>
