<!-- Generated by DDD Module Generator on 2025-07-04 -->
<script setup lang="ts">
import debounce from 'lodash/debounce'
import { useI18n } from 'vue-i18n'
import { useReportStore } from '../stores/reportStore'

// Componentes internos
import ReportTable from '../components/organisms/ReportTable.vue'
import ReportAdd from './ReportAdd.vue'
import ReportDelete from './ReportDelete.vue'
import ReportEdit from './ReportEdit.vue'

// Composable para manejar diálogos
const { openDialog, navigateTo } = useAppManager()
const { t } = useI18n()

// Store
const reportStore = useReportStore()

// Headers para la tabla
const headers = [
  { title: t('report.name'), key: 'name' },
  { title: t('report.description'), key: 'description' },
  { title: t('report.status'), key: 'status' },
  { title: t('actions'), key: 'actions', sortable: false },
]

// Opciones del menú de exportación
const menuOptions = [
  {
    text: `${t('export_to')} ${t('excel')}`,
    icon: 'tabler-file-spreadsheet',
    action: () => exportItems('excel'),
  },
  {
    text: `${t('export_to')} ${t('pdf')}`,
    icon: 'tabler-file-type-pdf',
    action: () => exportItems('pdf'),
  },
]

// Métodos
const debouncedFetchList = debounce(() => {
  reportStore.fetchList()
}, 500)

function applyFilters() {
  debouncedFetchList()
}

function onPageChange(newPage: number) {
  reportStore.page = newPage
  reportStore.fetchList()
}

function onItemsPerPageChange(newItemsPerPage: number) {
  reportStore.itemsPerPage = newItemsPerPage
  reportStore.fetchList()
}

function deleteSelected() {
  openDialog(ReportDelete, {}, { width: '900px', persistent: true }).then(result => {
    if (result === 'submit')
      reportStore.fetchList()
  })
}

function openAddDialog() {
  openDialog(ReportAdd, { title: t('add Report') }, { width: '900px', persistent: true }).then(result => {
    if (result === 'submit')
      reportStore.fetchList()
  })
}

function openEditDialog(item: any) {
  openDialog(ReportEdit, { item, title: t('edit Report') }, { width: '800px', persistent: true }).then(result => {
    if (result === 'submit')
      reportStore.fetchList()
  })
}

function openViewDialog(item: any) {
  navigateTo(`/reports/${item.id}`)
}

function openDeleteDialog(item: any) {
  openDialog(ReportDelete, { item, title: t('delete Report') }, { width: '900px', persistent: true }).then(result => {
    if (result === 'submit')
      reportStore.fetchList()
  })
}

function exportItems(type: string) {
  reportStore.exportItems(type)
}

// onMounted
onMounted(() => {
  reportStore.fetchList()
})
</script>

<template>
  <VCard>
    <VCardTitle>
      <h4 class="text-h4 mb-1">
        report.title
      </h4>
      <p class="text-body-1 mb-4">
        report.description
      </p>
    </VCardTitle>

    <VCardText>
      <div class="d-flex align-center flex-wrap gap-4 justify-end">
        <!-- Campo de búsqueda -->
        <VTextField
          v-model="reportStore.filters.search"
          label="report.search_report"
          variant="outlined"
          dense
          class="filter-field"
          @input="applyFilters"
        />

        <!-- Botón para exportar -->
        <GlobalMenu
          label="export"
          :options="menuOptions"
          color="secondary"
          variant="tonal"
          icon="tabler-chevron-down"
        />

        <!-- Botón para agregar -->
        <VBtn
          prepend-icon="tabler-plus"
          color="primary"
          @click="openAddDialog"
        >
          { ('report.add report') }
        </VBtn>

        <!-- Botones para acciones con seleccionados -->
        <VBtn
          v-if="reportStore.selectedItems.length > 1"
          color="error"
          @click="deleteSelected"
        >
          { ('delete selected') }
        </VBtn>
      </div>
    </VCardText>

    <VDivider />

    <!-- Tabla de elementos -->
    <ReportTable
      :headers="headers"
      :items="reportStore.list"
      :total="reportStore.total"
      :page="reportStore.page"
      :items-per-page="reportStore.itemsPerPage"
      :loading="reportStore.isLoading"
      :selection="reportStore.selectedItems"
      @update:selection="val => reportStore.selectedItems = val"
      @update:page="onPageChange"
      @update:items-per-page="onItemsPerPageChange"
      @view="openViewDialog"
      @edit="openEditDialog"
      @delete="openDeleteDialog"
    />
  </VCard>
</template>

<style scoped>
.filter-field {
  flex: 1;
  max-inline-size: 300px;
}
</style>
