<!-- Generated by DDD Module Generator on 2025-07-04 -->
<script setup lang="ts">
import { computed, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { useAppManager } from '@/composables/useAppManager'
import { useGlobalSnackbarStore } from '@/stores/globalSnackbarStore'
import { useReportStore } from '../stores/reportStore'

// Si tienes un store de notificaciones global

interface Props {
  item?: any
}

const props = defineProps<Props>()
const { t } = useI18n()
const { closeDialog } = useAppManager()
const store = useReportStore()

const ReportTitle = t('report')
const isDeleting = ref(false)
const confirmationText = ref('')
const requiredText = 'eliminar'

// Alternativa: usar el nombre del reporte como confirmación
// const requiredText = computed(() => itemInfo.value?.name || 'eliminar')

const itemInfo = computed(() => {
  if (!props.item)
    return null

  return {
    name: props.item.name || 'Sin nombre',
    description: props.item.description || 'Sin descripción',
    category: props.item.category || 'Sin categoría',
    isActive: props.item.is_active || false,
    lastUsed: props.item.lastUsed || null,
    usageCount: props.item.usageCount || 0,
  }
})

const isConfirmationValid = computed(() => {
  return confirmationText.value.toLowerCase().trim() === requiredText.toLowerCase()
})

function close(result: 'close' | 'submit' | 'cancel' = 'close') {
  // Limpiar el texto de confirmación al cerrar
  confirmationText.value = ''
  closeDialog(result)
}

async function confirmDelete() {
  try {
    isDeleting.value = true
    if (props.item)
      await store.deleteItem(props.item.id)

    // Mostrar snackbar de éxito
    useGlobalSnackbarStore().showSnackbar(
      'Éxito',
      { messageKey: 'Reporte eliminado correctamente', variables: {} },
      'success',
    )

    close('submit')
  }
  catch (error) {
    console.error('Error al eliminar:', error)
    useGlobalSnackbarStore().showSnackbar(
      'Error',
      { messageKey: 'Error al eliminar el reporte', variables: {} },
      'error',
    )
  }
  finally {
    isDeleting.value = false
  }
}
</script>

<template>
  <VDialog
    model-value
    max-width="600"
    persistent
    @update:model-value="close"
  >
    <DialogCloseBtn @click="close('cancel')" />
    <VCard>
      <!-- Header con icono de alerta -->
      <VCardText class="pa-6 pb-0">
        <div class="text-center mb-6">
          <div
            class="mx-auto mb-4 d-flex align-center justify-center"
            style=" border-radius: 50%; background-color: rgba(var(--v-theme-error), 0.1); block-size: 80px;inline-size: 80px;"
          >
            <VIcon
              icon="tabler-trash"
              color="error"
              size="40"
            />
          </div>

          <h4 class="text-h5 font-weight-medium mb-2">
            {{ t('deleteModule', { moduleName: ReportTitle }) }}
          </h4>

          <VChip
            color="error"
            variant="tonal"
            size="small"
          >
            <VIcon
              icon="tabler-alert-triangle"
              size="16"
              start
            />
            Acción irreversible
          </VChip>
        </div>

        <!-- Alert de advertencia principal -->
        <VAlert
          type="error"
          variant="tonal"
          class="mb-6"
        >
          <template #prepend>
            <VIcon icon="tabler-alert-circle" />
          </template>
          <div>
            <div class="font-weight-medium mb-1">
              {{ t('deleteItemDescription') }}
            </div>
            <div class="text-caption">
              Esta acción no se puede deshacer y se perderán todos los datos asociados
            </div>
          </div>
        </VAlert>

        <!-- Información del reporte -->
        <VCard
          v-if="itemInfo"
          variant="outlined"
          class="mb-6"
        >
          <VCardText class="pa-4">
            <div class="d-flex align-center mb-3">
              <VIcon
                icon="tabler-file-text"
                class="me-2"
              />
              <span class="text-subtitle-1 font-weight-medium">Información del Reporte</span>
            </div>

            <VRow dense>
              <VCol cols="12">
                <div class="d-flex align-center mb-2">
                  <VIcon
                    icon="tabler-tag"
                    size="16"
                    class="me-2 text-medium-emphasis"
                  />
                  <span class="text-body-2 text-medium-emphasis me-2">Nombre:</span>
                  <span class="font-weight-medium">{{ itemInfo.name }}</span>
                </div>
              </VCol>

              <VCol
                v-if="itemInfo.description && itemInfo.description !== 'Sin descripción'"
                cols="12"
              >
                <div class="d-flex align-center mb-2">
                  <VIcon
                    icon="tabler-align-left"
                    size="16"
                    class="me-2 text-medium-emphasis"
                  />
                  <span class="text-body-2 text-medium-emphasis me-2">Descripción:</span>
                  <span class="text-body-2">{{ itemInfo.description }}</span>
                </div>
              </VCol>

              <VCol cols="6">
                <div class="d-flex align-center mb-2">
                  <VIcon
                    :icon="itemInfo.isActive ? 'tabler-circle-check' : 'tabler-circle-x'"
                    :color="itemInfo.isActive ? 'success' : 'error'"
                    size="16"
                    class="me-2"
                  />
                  <span class="text-body-2 text-medium-emphasis me-2">Estado:</span>
                  <VChip
                    :color="itemInfo.isActive ? 'success' : 'error'"
                    size="x-small"
                    variant="tonal"
                  >
                    {{ itemInfo.isActive ? 'Activo' : 'Inactivo' }}
                  </VChip>
                </div>
              </VCol>

              <VCol
                v-if="itemInfo.usageCount > 0"
                cols="12"
              >
                <VAlert
                  type="warning"
                  variant="tonal"
                  density="compact"
                  class="mt-2"
                >
                  <template #prepend>
                    <VIcon icon="tabler-users" />
                  </template>
                  <span class="text-caption">
                    Este reporte ha sido utilizado <strong>{{ itemInfo.usageCount }}</strong> veces
                  </span>
                </VAlert>
              </VCol>
            </VRow>
          </VCardText>
        </VCard>

        <!-- Confirmación final -->
        <!--
          <VCard
          variant="tonal"
          color="error"
          class="mb-4"
          >
          <VCardText class="pa-4">
          <div class="d-flex align-center">
          <VIcon
          icon="tabler-shield-exclamation"
          color="error"
          size="24"
          class="me-3"
          />
          <div>
          <div class="font-weight-medium text-body-2 mb-1">
          ¿Estás seguro de que quieres eliminar este reporte?
          </div>
          <div class="text-caption text-medium-emphasis">
          Confirma que entiendes las consecuencias de esta acción
          </div>
          </div>
          </div>
          </VCardText>
          </VCard>
        -->

        <!-- Confirmación por texto -->
        <VCard
          variant="outlined"
          class="mb-4"
        >
          <VCardText class="pa-4">
            <div class="mb-3">
              <VIcon
                icon="tabler-keyboard"
                color="warning"
                class="me-2"
              />
              <span class="text-subtitle-2 font-weight-medium">Confirmación requerida</span>
            </div>

            <p class="text-body-2 text-medium-emphasis mb-3">
              Para confirmar la eliminación, escribe <VChip
                size="small"
                color="error"
                variant="tonal"
              >
                <strong>{{ requiredText }}</strong>
              </VChip> en el campo de abajo:
            </p>

            <VTextField
              v-model="confirmationText"
              label="Escribe para confirmar"
              :placeholder="requiredText"
              variant="outlined"
              density="compact"
              :color="isConfirmationValid ? 'success' : 'error'"
              clearable
              autofocus
            >
              <template #prepend-inner>
                <VIcon
                  :icon="isConfirmationValid ? 'tabler-check' : 'tabler-alert-circle'"
                  :color="isConfirmationValid ? 'success' : 'error'"
                  size="18"
                />
              </template>
              <template #append-inner>
                <VFadeTransition>
                  <VIcon
                    v-if="isConfirmationValid"
                    icon="tabler-circle-check"
                    color="success"
                    size="20"
                  />
                </VFadeTransition>
              </template>
            </VTextField>

            <div
              v-if="confirmationText && !isConfirmationValid"
              class="text-caption text-error mt-1"
            >
              <VIcon
                icon="tabler-x"
                size="12"
                class="me-1"
              />
              El texto no coincide. Debe escribir exactamente "{{ requiredText }}"
            </div>

            <div
              v-if="isConfirmationValid"
              class="text-caption text-success mt-1"
            >
              <VIcon
                icon="tabler-check"
                size="12"
                class="me-1"
              />
              Confirmación válida. Puedes proceder con la eliminación
            </div>
          </VCardText>
        </VCard>
      </VCardText>

      <!-- Acciones -->
      <VCardActions class="pa-6 pt-0">
        <div class="d-flex justify-center gap-3 w-100">
          <VBtn
            color="secondary"
            variant="outlined"
            min-width="120"
            :disabled="isDeleting"
            @click="close"
          >
            <VIcon
              icon="tabler-x"
              start
            />
            {{ t('cancel') }}
          </VBtn>
          <VBtn
            color="error"
            min-width="140"
            :loading="isDeleting"
            :disabled="!isConfirmationValid"
            @click="confirmDelete"
          >
            <VIcon
              icon="tabler-trash"
              start
            />
            {{ t('confirmDelete') }}
          </VBtn>
        </div>
      </VCardActions>
    </VCard>
  </VDialog>
</template>

<style scoped>
.cursor-help {
  cursor: help;
}
</style>
