<!-- Generated by DDD Module Generator on 2025-07-04 -->
<script setup lang="ts">
import ReportWizard from '../components/organisms/ReportWizard.vue'
</script>

<template>
  <ReportWizard />
</template>
