// Generated by DDD Module Generator

import { rawApi } from '@/services/api'

export class FineApiService {
  private readonly baseUrl = '/transport/fines'

  async create(data: any) {
    return await rawApi(this.baseUrl, { method: 'POST', body: data })
  }

  async update(id: string, data: any) {
    return await rawApi(`${this.baseUrl}/${id}`, { method: 'PUT', body: data })
  }

  async delete(id: string) {
    return await rawApi(`${this.baseUrl}/${id}`, { method: 'DELETE' })
  }

  async getById(id: string) {
    return await rawApi(`${this.baseUrl}/${id}`, { method: 'GET' })
  }

  async getAll() {
    return await rawApi(this.baseUrl, { method: 'GET' })
  }

  async getList(params: any) {
    return await rawApi(this.baseUrl, { method: 'GET', params })
  }

  async getFines(params: any) {
    return await rawApi('/fines/list', { method: 'GET', params })
  }

  // Fine specific methods
  async payFine(id: string, data: any) {
    return await rawApi(`${this.baseUrl}/${id}/pay`, { method: 'POST', body: data })
  }

  async contestFine(id: string, data: any) {
    return await rawApi(`${this.baseUrl}/${id}/contest`, { method: 'POST', body: data })
  }

  async getFineStats() {
    return await rawApi(`${this.baseUrl}/stats`, { method: 'GET' })
  }

  async getOverdueFines(params: any) {
    return await rawApi(`${this.baseUrl}/overdue`, { method: 'GET', params })
  }

  async exportFines(params: any) {
    return await rawApi(`${this.baseUrl}/export`, { method: 'GET', params })
  }
}
