// Generated by DDD Module Generator

import { rawApi } from '@/services/api'

export class DriverApiService {
  private readonly baseUrl = '/transport/drivers'

  async create(data: any) {
    return await rawApi(this.baseUrl, { method: 'POST', body: data })
  }

  async update(id: string, data: any) {
    return await rawApi(`${this.baseUrl}/${id}`, { method: 'PUT', body: data })
  }

  async delete(id: string) {
    return await rawApi(`${this.baseUrl}/${id}`, { method: 'DELETE' })
  }

  async getById(id: string) {
    return await rawApi(`${this.baseUrl}/${id}`, { method: 'GET' })
  }

  async getAll() {
    return await rawApi(this.baseUrl, { method: 'GET' })
  }

  async getList(params: any) {
    return await rawApi(this.baseUrl, { method: 'GET', params })
  }

  // Driver specific methods
  async assignToVehicle(driverId: string, vehicleId: string) {
    return await rawApi(`${this.baseUrl}/${driverId}/assign`, {
      method: 'POST',
      body: { vehicle_id: vehicleId },
    })
  }

  async unassignFromVehicle(driverId: string) {
    return await rawApi(`${this.baseUrl}/${driverId}/unassign`, { method: 'POST' })
  }

  async getDriverLicenseHistory(id: string) {
    return await rawApi(`${this.baseUrl}/${id}/license-history`, { method: 'GET' })
  }

  async getDriverStats() {
    return await rawApi(`${this.baseUrl}/stats`, { method: 'GET' })
  }

  async getExpiringLicenses(params: any) {
    return await rawApi(`${this.baseUrl}/expiring-licenses`, { method: 'GET', params })
  }

  async exportDrivers(params: any) {
    return await rawApi(`${this.baseUrl}/export`, { method: 'GET', params })
  }
}
