// Generated by DDD Module Generator on 2025-07-04

import { rawApi } from '@/services/api'

export class ReportApiService {
  private readonly baseUrl = '/dynamic-reports/reports'

  async create(data: any) {
    return await rawApi(this.baseUrl, { method: 'POST', body: data })
  }

  async update(id: string, data: any) {
    return await rawApi(`${this.baseUrl}/${id}`, { method: 'PUT', body: data })
  }

  async delete(id: string) {
    return await rawApi(`${this.baseUrl}/${id}`, { method: 'DELETE' })
  }

  async getById(id: string) {
    return await rawApi(`${this.baseUrl}/${id}`, { method: 'GET' })
  }

  async getAll() {
    return await rawApi(this.baseUrl, { method: 'GET' })
  }

  async getList(params: any) {
    return await rawApi(this.baseUrl, { method: 'GET', params })
  }

  async executeReport(payload: {
    report_id: string
    export_format: string
    filters?: any
    sorting?: any
    pagination?: {
      page: number
      per_page: number
    }
  }) {
    return await rawApi('/dynamic-reports/executions/execute', {
      method: 'POST',
      body: payload,
    })
  }
}
