// Generated by DDD Module Generator on 2025-07-04

import type { DataSource } from '../../entities/DataSource'
import type { DataSourceId } from '../../valueObjects/DataSourceId'

export interface DataSourceRepository {
  exists(dataSourceId: DataSourceId): Promise<boolean>
  getDataSourceById(dataSourceId: DataSourceId): Promise<DataSource>
  save(dataSource: DataSource): Promise<void>
  delete(dataSourceId: DataSourceId): Promise<void>
  getAll(): Promise<DataSource[]>
  getAllPaginated(page: number, limit: number): Promise<{
    dataSources: DataSource[]
    totalPages: number
    total: number
  }>
}
