<!-- Generated by DDD Module Generator on 2025-07-04 -->
<script setup lang="ts">
import { h, resolveComponent } from 'vue'
import ReportFilterInput from '../ReportFilterInput.vue'

interface FilterGroup {
  type: 'group'
  alias?: string
  children: any[]
}

interface Props {
  group: FilterGroup
  appliedFiltersMap: Record<string, any>
  applyFilter: (filter: any, value: any) => void
}

defineProps<Props>()
</script>

<template>
  <div class="filter-group mb-2 ps-2">
    <div class="d-flex align-center mb-1">
      <VIcon
        icon="tabler-category"
        size="18"
        class="me-1"
      />
      <span class="text-subtitle-2 font-weight-medium">
        {{ group.alias || 'Grupo de filtros' }}
      </span>
    </div>
    <div class="d-flex flex-column gap-2">
      <template
        v-for="child in group.children"
        :key="child.field || child.alias"
      >
        <FilterGroupAtom
          v-if="child.type === 'group'"
          :group="child"
          :applied-filters-map="appliedFiltersMap"
          :apply-filter="applyFilter"
        />
        <ReportFilterInput
          v-else
          :filter="child"
          :model-value="appliedFiltersMap[child.field]"
          @update:model-value="val => appliedFiltersMap[child.field] = val"
          @apply="val => applyFilter(child, val)"
        />
      </template>
    </div>
  </div>
</template>

<style scoped>
.filter-group {
  border-inline-start: 2px solid #e0e0e0;
  margin-block-end: 12px;
  padding-inline-start: 12px;
}
</style>
