// Generated by DDD Module Generator on 2025-07-04

import type { Report } from '../entities/Report'

export interface Specification<T> {
  isSatisfiedBy(candidate: T): boolean
}

export class ReportIsActiveSpecification implements Specification<Report> {
  isSatisfiedBy(report: Report): boolean {
    return report.status === 'active'
  }
}
