// Generated by DDD Module Generator on 2025-07-04

import type { CreateDataSourceCommand } from '../commands/CreateDataSourceCommand'
import type { DataSourceRepository } from '../../domain/contracts/repositories/DataSourceRepository'
import { DataSource } from '../../domain/entities/DataSource'
import type { DataSourceMapper } from '../mappers/DataSourceMapper'
import { Result } from '../../../shared/domain/base/Result'
import type { DataSourceResponseDto } from '../dtos/DataSourceDtos'

export class CreateDataSourceHandler {
  private dataSourceRepository: DataSourceRepository
  private mapper: DataSourceMapper

  constructor(
    dataSourceRepository: DataSourceRepository,
    mapper: DataSourceMapper,
  ) {
    this.dataSourceRepository = dataSourceRepository
    this.mapper = mapper
  }

  async execute(command: CreateDataSourceCommand): Promise<Result<DataSourceResponseDto>> {
    try {
      const dataSourceOrError = DataSource.create({
        ...command,
        createdAt: new Date(),
        updatedAt: new Date(),
      })

      if (dataSourceOrError.isFailure)
        return Result.fail<DataSourceResponseDto>(dataSourceOrError.error)

      const dataSource = dataSourceOrError.getValue()

      await this.dataSourceRepository.save(dataSource)

      return Result.ok<DataSourceResponseDto>(
        this.mapper.toDto(dataSource),
      )
    }
    catch (err) {
      return Result.fail<DataSourceResponseDto>(`Unexpected error creating DataSource: ${err}`)
    }
  }
}
