// Generated by DDD Module Generator on 2025-07-04

import type { DeleteDataSourceCommand } from '../commands/DeleteDataSourceCommand'
import type { DataSourceRepository } from '../../domain/contracts/repositories/DataSourceRepository'
import { DataSourceId } from '../../domain/valueObjects/DataSourceId'
import { Result } from '../../../shared/domain/base/Result'
import { DataSourceNotFound } from '../../domain/exceptions/DataSourceNotFound'

export class DeleteDataSourceHandler {
  private dataSourceRepository: DataSourceRepository

  constructor(dataSourceRepository: DataSourceRepository) {
    this.dataSourceRepository = dataSourceRepository
  }

  async execute(command: DeleteDataSourceCommand): Promise<Result<void>> {
    try {
      const dataSourceId = DataSourceId.create(command.id)
      const exists = await this.dataSourceRepository.exists(dataSourceId)

      if (!exists)
        return Result.fail<void>(new DataSourceNotFound().message)

      await this.dataSourceRepository.delete(dataSourceId)

      return Result.ok<void>()
    }
    catch (err) {
      return Result.fail<void>(`Unexpected error deleting DataSource: ${err}`)
    }
  }
}
