// Generated by DDD Module Generator on 2025-07-04

import type { GetDataSourceListQuery } from '../queries/GetDataSourceListQuery'
import type { DataSourceRepository } from '../../domain/contracts/repositories/DataSourceRepository'
import type { DataSourceMapper } from '../mappers/DataSourceMapper'
import { Result } from '../../../shared/domain/base/Result'
import type { DataSourceResponseDto } from '../dtos/DataSourceDtos'

export class GetDataSourceListHandler {
  private dataSourceRepository: DataSourceRepository
  private mapper: DataSourceMapper

  constructor(
    dataSourceRepository: DataSourceRepository,
    mapper: DataSourceMapper,
  ) {
    this.dataSourceRepository = dataSourceRepository
    this.mapper = mapper
  }

  async execute(query: GetDataSourceListQuery): Promise<Result<{
    items: DataSourceResponseDto[]
    total: number
    totalPages: number
    page: number
    limit: number
  }>> {
    try {
      const page = query.page || 1
      const limit = query.limit || 20

      const result = await this.dataSourceRepository.getAllPaginated(page, limit)

      return Result.ok({
        items: result.dataSources.map(dataSource => this.mapper.toDto(dataSource)),
        total: result.total,
        totalPages: result.totalPages,
        page,
        limit,
      })
    }
    catch (err) {
      return Result.fail(`Unexpected error getting DataSource list: ${err}`)
    }
  }
}
