// Generated by DDD Module Generator on 2025-07-04

import type { GetDataSourceByIdQuery } from '../queries/GetDataSourceByIdQuery'
import type { DataSourceRepository } from '../../domain/contracts/repositories/DataSourceRepository'
import { DataSourceId } from '../../domain/valueObjects/DataSourceId'
import type { DataSourceMapper } from '../mappers/DataSourceMapper'
import { Result } from '../../../shared/domain/base/Result'
import type { DataSourceResponseDto } from '../dtos/DataSourceDtos'
import { DataSourceNotFound } from '../../domain/exceptions/DataSourceNotFound'

export class GetDataSourceByIdHandler {
  private dataSourceRepository: DataSourceRepository
  private mapper: DataSourceMapper

  constructor(
    dataSourceRepository: DataSourceRepository,
    mapper: DataSourceMapper,
  ) {
    this.dataSourceRepository = dataSourceRepository
    this.mapper = mapper
  }

  async execute(query: GetDataSourceByIdQuery): Promise<Result<DataSourceResponseDto>> {
    try {
      const dataSourceId = DataSourceId.create(query.id)
      const dataSource = await this.dataSourceRepository.getDataSourceById(dataSourceId)

      if (!dataSource)
        return Result.fail<DataSourceResponseDto>(new DataSourceNotFound().message)

      return Result.ok<DataSourceResponseDto>(
        this.mapper.toDto(dataSource),
      )
    }
    catch (err) {
      return Result.fail<DataSourceResponseDto>(`Unexpected error getting DataSource: ${err}`)
    }
  }
}
