// Generated by DDD Module Generator on 2025-07-04

import type { UpdateDataSourceCommand } from '../commands/UpdateDataSourceCommand'
import type { DataSourceRepository } from '../../domain/contracts/repositories/DataSourceRepository'
import { DataSourceId } from '../../domain/valueObjects/DataSourceId'
import type { DataSourceMapper } from '../mappers/DataSourceMapper'
import { Result } from '../../../shared/domain/base/Result'
import type { DataSourceResponseDto } from '../dtos/DataSourceDtos'
import { DataSourceNotFound } from '../../domain/exceptions/DataSourceNotFound'

export class UpdateDataSourceHandler {
  private dataSourceRepository: DataSourceRepository
  private mapper: DataSourceMapper

  constructor(
    dataSourceRepository: DataSourceRepository,
    mapper: DataSourceMapper,
  ) {
    this.dataSourceRepository = dataSourceRepository
    this.mapper = mapper
  }

  async execute(command: UpdateDataSourceCommand): Promise<Result<DataSourceResponseDto>> {
    try {
      const dataSourceId = DataSourceId.create(command.id)
      const dataSource = await this.dataSourceRepository.getDataSourceById(dataSourceId)

      if (!dataSource)
        return Result.fail<DataSourceResponseDto>(new DataSourceNotFound().message)

      const { id, ...updateData } = command
      const updateResult = dataSource.update(updateData)

      if (updateResult.isFailure)
        return Result.fail<DataSourceResponseDto>(updateResult.error)

      await this.dataSourceRepository.save(dataSource)

      return Result.ok<DataSourceResponseDto>(
        this.mapper.toDto(dataSource),
      )
    }
    catch (err) {
      return Result.fail<DataSourceResponseDto>(`Unexpected error updating DataSource: ${err}`)
    }
  }
}
