// Generated by DDD Module Generator on 2025-07-04

import type { ReportRepository } from '../../../domain/contracts/repositories/ReportRepository'
import type { Report } from '../../../domain/entities/Report'
import type { ReportId } from '../../../domain/valueObjects/ReportId'
import { ReportMapper } from '../../../application/mappers/ReportMapper'

export class ReportRepositoryImpl implements ReportRepository {
  private models = new Map<string, any>()

  async exists(reportId: ReportId): Promise<boolean> {
    return this.models.has(reportId.value)
  }

  async getReportById(reportId: ReportId): Promise<Report> {
    const raw = this.models.get(reportId.value)
    if (!raw)
      return null

    return ReportMapper.toDomain(raw)
  }

  async save(report: Report): Promise<void> {
    const raw = ReportMapper.toPersistence(report)

    this.models.set(report.id.toString(), raw)
  }

  async delete(reportId: ReportId): Promise<void> {
    this.models.delete(reportId.value)
  }

  async getAll(): Promise<Report[]> {
    const all = Array.from(this.models.values())

    return all.map(raw => ReportMapper.toDomain(raw)).filter(Boolean)
  }

  async getAllPaginated(page: number, limit: number): Promise<{
    reports: Report[]
    totalPages: number
    total: number
  }> {
    const all = await this.getAll()
    const total = all.length
    const totalPages = Math.ceil(total / limit)
    const start = (page - 1) * limit
    const reports = all.slice(start, start + limit)

    return {
      reports,
      totalPages,
      total,
    }
  }
}
