// Generated by DDD Module Generator on 2025-07-04

import { rawApi } from '@/services/api'

export class DataSourceApiService {
  private readonly baseUrl = '/dynamic-reports/data-sources'

  async create(data: any) {
    return await rawApi(this.baseUrl, { method: 'POST', body: data })
  }

  async update(id: string, data: any) {
    return await rawApi(`${this.baseUrl}/${id}`, { method: 'PUT', body: data })
  }

  async delete(id: string) {
    return await rawApi(`${this.baseUrl}/${id}`, { method: 'DELETE' })
  }

  async getById(id: string) {
    return await rawApi(`${this.baseUrl}/${id}`, { method: 'GET' })
  }

  async getAll() {
    return await rawApi(this.baseUrl, { method: 'GET' })
  }

  async getList(params: any) {
    return await rawApi(this.baseUrl, { method: 'GET', params })
  }

  // Probar consulta de data source
  async testQuery(connectionId: string, payload: any) {
    return await rawApi(`/dynamic-reports/connections/${connectionId}/test-query`, {
      method: 'POST',
      body: payload,
    })
  }

  async getFields(id: string) {
    return await rawApi(`${this.baseUrl}/${id}/fields`, { method: 'GET' })
  }
}
