// Generated by DDD Module Generator on 2025-07-04

import type { Connection } from '../entities/Connection'

export interface Specification<T> {
  isSatisfiedBy(candidate: T): boolean
}

export class ConnectionIsActiveSpecification implements Specification<Connection> {
  isSatisfiedBy(connection: Connection): boolean {
    return connection.status === 'active'
  }
}
