<!-- Generated by DDD Module Generator on 2025-07-04 -->
<script setup lang="ts">
interface Props {
  loading: boolean
  message?: string
}

defineProps<Props>()
</script>

<template>
  <div
    v-if="loading"
    class="flex justify-center items-center p-4"
  >
    <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-indigo-600" />
    <span class="ml-2 text-gray-600">{{ message || 'Loading...' }}</span>
  </div>
</template>
