<!-- Generated by DDD Module Generator on 2025-07-04 -->
<script setup lang="ts">
import { computed, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import { useDataSourceStore } from '../stores/dataSourceStore'
import DataSourceForm from '../components/organisms/DataSourceForm.vue'

const route = useRoute()
const store = useDataSourceStore()
const currentItem = computed(() => store.currentItem)

onMounted(async () => {
  await store.fetchById(route.params.id as string)
})
</script>

<template>
  <DataSourceForm
    mode="edit"
    :initial-data="currentItem"
  />
</template>
