<!-- Generated by DDD Module Generator on 2025-07-04 -->
<script setup lang="ts">
import debounce from 'lodash/debounce'
import { useI18n } from 'vue-i18n'
import { useDataSourceStore } from '../stores/dataSourceStore'

// Componentes internos
import DataSourceTable from '../components/organisms/DataSourceTable.vue'
import DataSourceDelete from './DataSourceDelete.vue'

// Composable para manejar diálogos
const { openDialog, navigateTo } = useAppManager()
const { t } = useI18n()

// Store
const dataSourceStore = useDataSourceStore()

// Headers para la tabla
const headers = [
  { title: t('data-source.name'), key: 'name' },
  { title: t('data-source.type'), key: 'type' },
  { title: t('data-source.table'), key: 'table' },
  { title: t('data-source.status'), key: 'is_active' },
  { title: t('actions'), key: 'actions', sortable: false },
]

// Opciones del menú de exportación
const menuOptions = [
  {
    text: `${t('export_to')} ${t('excel')}`,
    icon: 'tabler-file-spreadsheet',
    action: () => exportItems('excel'),
  },
  {
    text: `${t('export_to')} ${t('pdf')}`,
    icon: 'tabler-file-type-pdf',
    action: () => exportItems('pdf'),
  },
]

// Métodos
const debouncedFetchList = debounce(() => {
  dataSourceStore.fetchList()
}, 500)

function applyFilters() {
  debouncedFetchList()
}

function onPageChange(newPage: number) {
  dataSourceStore.page = newPage
  dataSourceStore.fetchList()
}

function onItemsPerPageChange(newItemsPerPage: number) {
  dataSourceStore.itemsPerPage = newItemsPerPage
  dataSourceStore.fetchList()
}

function deleteSelected() {
  openDialog(DataSourceDelete, {}, { width: '900px', persistent: true }).then(result => {
    if (result === 'submit')
      dataSourceStore.fetchList()
  })
}

function goToWizard() {
  navigateTo('/data-sources/wizard')
}

function openEditDialog(item: any) {
  navigateTo(`/data-sources/wizard/${item.id}`)
}

function openViewDialog(item: any) {
  navigateTo(`/data-sources/${item.id}`)
}

function openDeleteDialog(item: any) {
  openDialog(DataSourceDelete, { item, title: t('delete DataSource') }, { width: '900px', persistent: true }).then(result => {
    if (result === 'submit')
      dataSourceStore.fetchList()
  })
}

function exportItems(type: string) {
  dataSourceStore.exportItems(type)
}

// onMounted
onMounted(() => {
  dataSourceStore.fetchList()
})
</script>

<template>
  <VCard>
    <VCardTitle>
      <h4 class="text-h4 mb-1">
        data-source.title
      </h4>
      <p class="text-body-1 mb-4">
        data-source.description
      </p>
    </VCardTitle>

    <VCardText>
      <div class="d-flex align-center flex-wrap gap-4 justify-end">
        <!-- Campo de búsqueda -->
        <VTextField
          v-model="dataSourceStore.filters.search"
          label="data-source.search_data-source"
          variant="outlined"
          dense
          class="filter-field"
          @input="applyFilters"
        />

        <!-- Botón para exportar -->
        <GlobalMenu
          label="export"
          :options="menuOptions"
          color="secondary"
          variant="tonal"
          icon="tabler-chevron-down"
        />

        <!-- Botón para agregar -->
        <VBtn
          prepend-icon="tabler-plus"
          color="primary"
          @click="goToWizard"
        >
          {{ t('data-source.add data-source') }}
        </VBtn>

        <!-- Botones para acciones con seleccionados -->
        <VBtn
          v-if="dataSourceStore.selectedItems.length > 1"
          color="error"
          @click="deleteSelected"
        >
          {{ t('delete selected') }}
        </VBtn>
      </div>
    </VCardText>

    <VDivider />

    <!-- Tabla de elementos -->
    <DataSourceTable
      :headers="headers"
      :items="dataSourceStore.items"
      :total="dataSourceStore.total"
      :page="dataSourceStore.page"
      :items-per-page="dataSourceStore.itemsPerPage"
      :loading="dataSourceStore.loading"
      :selection="dataSourceStore.selectedItems"
      @update:selection="val => dataSourceStore.selectedItems = val"
      @update:page="onPageChange"
      @update:items-per-page="onItemsPerPageChange"
      @view="openViewDialog"
      @edit="openEditDialog"
      @delete="openDeleteDialog"
    />
  </VCard>
</template>

<style scoped>
.filter-field {
  flex: 1;
  max-inline-size: 300px;
}
</style>
