// Generated by DDD Module Generator on 2025-07-04

import { DomainEvent } from '../../../shared/domain/base/DomainEvent'
import type { Execution } from '../entities/Execution'

export class ExecutionCreated extends DomainEvent {
  public execution: Execution

  constructor(execution: Execution) {
    super(execution.id.toString())
    this.execution = execution
  }
}
