// Generated by DDD Module Generator on 2025-09-11

import type { Vehicle } from '../../../domain/entities/Vehicle'
import { VehicleMapper } from '../../../application/mappers/VehicleMapper'

export class VehicleTransformer {
  static fromApi(apiData: any): Vehicle | null {
    return VehicleMapper.toDomain(apiData)
  }

  static toApi(vehicle: Vehicle): any {
    return VehicleMapper.toPersistence(vehicle)
  }

  static manyFromApi(apiDataArray: any[]): Vehicle[] {
    return apiDataArray
      .map(apiData => this.fromApi(apiData))
      .filter(Boolean) as Vehicle[]
  }
}
