// Generated by DDD Module Generator on 2025-07-04

export class ConnectionNotFound extends Error {
  constructor(message: string = 'Connection not found') {
    super(message)
    this.name = 'ConnectionNotFound'
  }
}
