// Generated by DDD Module Generator on 2025-07-04

export class ConnectionAlreadyExists extends Error {
  constructor(message: string = 'Connection already exists') {
    super(message)
    this.name = 'ConnectionAlreadyExists'
  }
}
