// Generated by DDD Module Generator on 2025-07-04

export class ConnectionValidationError extends Error {
  constructor(message: string = 'Connection validation failed') {
    super(message)
    this.name = 'ConnectionValidationError'
  }
}
