// Generated by DDD Module Generator on 2025-07-04

import type { Execution } from '../../../domain/entities/Execution'
import { ExecutionMapper } from '../../../application/mappers/ExecutionMapper'

export class ExecutionTransformer {
  static fromApi(apiData: any): Execution | null {
    return ExecutionMapper.toDomain(apiData)
  }

  static toApi(execution: Execution): any {
    return ExecutionMapper.toPersistence(execution)
  }

  static manyFromApi(apiDataArray: any[]): Execution[] {
    return apiDataArray
      .map(apiData => this.fromApi(apiData))
      .filter(Boolean) as Execution[]
  }
}
