// Generated by DDD Module Generator

import { rawApi } from '@/services/api'

export class DocumentApiService {
  private readonly baseUrl = '/transport/documents'

  async create(data: any) {
    return await rawApi(this.baseUrl, { method: 'POST', body: data })
  }

  async update(id: string, data: any) {
    return await rawApi(`${this.baseUrl}/${id}`, { method: 'PUT', body: data })
  }

  async delete(id: string) {
    return await rawApi(`${this.baseUrl}/${id}`, { method: 'DELETE' })
  }

  async getById(id: string) {
    return await rawApi(`${this.baseUrl}/${id}`, { method: 'GET' })
  }

  async getAll() {
    return await rawApi(this.baseUrl, { method: 'GET' })
  }

  async getList(params: any) {
    return await rawApi(this.baseUrl, { method: 'GET', params })
  }

  // Document specific methods
  async uploadDocument(data: any) {
    return await rawApi(`${this.baseUrl}/upload`, { method: 'POST', body: data })
  }

  async downloadDocument(id: string) {
    return await rawApi(`${this.baseUrl}/${id}/download`, { method: 'GET' })
  }

  async validateDocument(params: any) {
    return await rawApi(`${this.baseUrl}/validate`, { method: 'GET', params })
  }

  async getDocumentStats() {
    return await rawApi(`${this.baseUrl}/stats`, { method: 'GET' })
  }

  async getExpiringDocuments(params: any) {
    return await rawApi(`${this.baseUrl}/expiring`, { method: 'GET', params })
  }

  async bulkOperation(data: any) {
    return await rawApi(`${this.baseUrl}/bulk`, { method: 'POST', body: data })
  }

  async exportDocuments(params: any) {
    return await rawApi(`${this.baseUrl}/export`, { method: 'GET', params })
  }
}
