// Generated by DDD Module Generator on 2025-07-04

import { defineStore } from 'pinia'
import { computed, ref } from 'vue'
import { ExecutionApiService } from '../../infrastructure/api/services/ExecutionApiService'
import type { ListFilters } from '../../../shared/types'

export const useExecutionStore = defineStore('execution', () => {
  // State
  const items = ref<any[]>([])
  const currentItem = ref<any>(null)
  const loading = ref(false)
  const error = ref<string | null>(null)

  // Pagination
  const page = ref(1)
  const itemsPerPage = ref(20)
  const total = ref(0)
  const totalPages = ref(0)

  // Filters
  const filters = ref<ListFilters>({})

  // Selection
  const selectedItems = ref<any[]>([])

  // Computed
  const currentPage = computed(() => page.value)
  const perPage = computed(() => itemsPerPage.value)

  // API Service
  const apiService = new ExecutionApiService()

  // Actions
  const fetchList = async () => {
    loading.value = true
    error.value = null

    try {
      const response = await apiService.getList({
        page: page.value,
        limit: itemsPerPage.value,
        ...filters.value,
      })

      items.value = response.data
      total.value = response.meta.total
      totalPages.value = response.meta.total_pages
    }
    catch (err) {
      error.value = err instanceof Error ? err.message : 'Failed to fetch executions'
    }
    finally {
      loading.value = false
    }
  }

  const fetchById = async (id: string) => {
    loading.value = true
    error.value = null

    try {
      const response = await apiService.getById(id)

      currentItem.value = response.data
    }
    catch (err) {
      error.value = err instanceof Error ? err.message : 'Failed to fetch execution'
    }
    finally {
      loading.value = false
    }
  }

  const createItem = async (data: any) => {
    loading.value = true
    error.value = null

    try {
      const response = await apiService.create(data)

      await fetchList()

      return response.data
    }
    catch (err) {
      error.value = err instanceof Error ? err.message : 'Failed to create execution'
      throw err
    }
    finally {
      loading.value = false
    }
  }

  const updateItem = async (id: string, data: any) => {
    loading.value = true
    error.value = null

    try {
      const response = await apiService.update(id, data)

      await fetchList()

      return response.data
    }
    catch (err) {
      error.value = err instanceof Error ? err.message : 'Failed to update execution'
      throw err
    }
    finally {
      loading.value = false
    }
  }

  const deleteItem = async (id: string) => {
    loading.value = true
    error.value = null

    try {
      await apiService.delete(id)
      await fetchList()
    }
    catch (err) {
      error.value = err instanceof Error ? err.message : 'Failed to delete execution'
      throw err
    }
    finally {
      loading.value = false
    }
  }

  const setPage = (newPage: number) => {
    page.value = newPage
  }

  const clearError = () => {
    error.value = null
  }

  const exportItems = (type: string) => {
    // TODO: Implement export functionality
    console.log('Exporting executions as', type)
  }

  return {
    // State
    items,
    currentItem,
    loading,
    error,

    // Pagination
    page,
    itemsPerPage,
    total,
    totalPages,
    currentPage,
    perPage,

    // Filters
    filters,

    // Selection
    selectedItems,

    // Actions
    fetchList,
    fetchById,
    createItem,
    updateItem,
    deleteItem,
    setPage,
    clearError,
    exportItems,
  }
})
