<!-- Generated by DDD Module Generator on 2025-07-04 -->
<script setup lang="ts">
import { computed, watch } from 'vue'

interface MenuConfig {
  show_in_menu: boolean
  menu_title?: string
  menu_icon?: string
  menu_category?: string
  menu_order?: number
  menu_permissions?: {
    action: string
    subject: string
  }
  menu_badge?: {
    content: string
    class: string
  }
}

interface Props {
  modelValue: MenuConfig
  reportName?: string
}

interface Emits {
  (e: 'update:modelValue', value: MenuConfig): void
  (e: 'validate', value: boolean): void
}

const props = defineProps<Props>()
const emit = defineEmits<Emits>()

// Iconos disponibles para menús
const availableIcons = [
  { value: 'tabler-chart-bar', label: 'Gráfico de barras' },
  { value: 'tabler-chart-pie', label: 'Gráfico circular' },
  { value: 'tabler-chart-line', label: 'Gráfico de líneas' },
  { value: 'tabler-chart-donut', label: 'Gráfico de dona' },
  { value: 'tabler-table', label: 'Tabla' },
  { value: 'tabler-file-text', label: 'Documento' },
  { value: 'tabler-database', label: 'Base de datos' },
  { value: 'tabler-analytics', label: 'Analytics' },
  { value: 'tabler-trending-up', label: 'Tendencia ascendente' },
  { value: 'tabler-trending-down', label: 'Tendencia descendente' },
  { value: 'tabler-users', label: 'Usuarios' },
  { value: 'tabler-building', label: 'Empresa' },
  { value: 'tabler-shopping-cart', label: 'Ventas' },
  { value: 'tabler-coin', label: 'Finanzas' },
  { value: 'tabler-calendar', label: 'Calendario' },
]

// Categorías predefinidas
const availableCategories = [
  'Reportes',
  'Ventas',
  'Finanzas',
  'Usuarios',
  'Analytics',
  'Operaciones',
  'Marketing',
  'Recursos Humanos',
]

const menuConfig = computed({
  get: () => props.modelValue,
  set: value => emit('update:modelValue', value),
})

const updatePermissions = (key: string, value: string) => {
  menuConfig.value = {
    ...menuConfig.value,
    menu_permissions: {
      action: '',
      subject: '',
      ...menuConfig.value.menu_permissions,
      [key]: value,
    },
  }
}

const updateBadge = (key: string, value: string) => {
  menuConfig.value = {
    ...menuConfig.value,
    menu_badge: {
      content: '',
      class: '',
      ...menuConfig.value.menu_badge,
      [key]: value,
    },
  }
}

// Validación del componente
const validateMenuConfig = () => {
  // Si no está habilitado para mostrar en menú, siempre es válido
  if (!menuConfig.value.show_in_menu) {
    emit('validate', true)

    return
  }

  // Si está habilitado, validar campos requeridos
  const isValid = !!(
    menuConfig.value.menu_title?.trim()
    && menuConfig.value.menu_icon
    && menuConfig.value.menu_category
    && menuConfig.value.menu_permissions?.action
    && menuConfig.value.menu_permissions?.subject
  )

  emit('validate', isValid)
}

// Watcher para validar automáticamente cuando cambian los datos
watch(menuConfig, () => {
  validateMenuConfig()
}, { deep: true, immediate: true })
</script>

<template>
  <VCard variant="outlined">
    <VCardTitle class="d-flex align-center justify-space-between pa-4">
      <div class="d-flex align-center">
        <VIcon
          icon="tabler-menu-2"
          class="me-2"
        />
        <span>Configuración de Menú</span>
      </div>
    </VCardTitle>

    <VCardText class="pa-4">
      <VRow>
        <!-- Mostrar en menú -->
        <VCol cols="12">
          <VSwitch
            v-model="menuConfig.show_in_menu"
            label="Mostrar en menú principal"
            color="primary"
            hide-details
          />
        </VCol>

        <!-- Configuración básica -->
        <VCol
          v-if="menuConfig.show_in_menu"
          cols="12"
          md="6"
        >
          <VTextField
            v-model="menuConfig.menu_title"
            label="Título del menú"
            :placeholder="reportName || 'Nombre del reporte'"
            variant="outlined"
            density="compact"
            hide-details
          />
        </VCol>

        <VCol
          v-if="menuConfig.show_in_menu"
          cols="12"
          md="6"
        >
          <VSelect
            v-model="menuConfig.menu_icon"
            label="Icono"
            :items="availableIcons"
            item-title="label"
            item-value="value"
            variant="outlined"
            density="compact"
            hide-details
          >
            <template #item="{ item }">
              <div class="d-flex align-center">
                <VIcon
                  :icon="item.raw.value"
                  class="me-2"
                />
                {{ item.raw.label }}
              </div>
            </template>
            <template #selection="{ item }">
              <div class="d-flex align-center">
                <VIcon
                  :icon="item.raw.value"
                  class="me-2"
                />
                {{ item.raw.label }}
              </div>
            </template>
          </VSelect>
        </VCol>

        <!-- Categoría y orden -->
        <VCol
          v-if="menuConfig.show_in_menu"
          cols="12"
          md="6"
        >
          <VSelect
            v-model="menuConfig.menu_category"
            label="Categoría"
            :items="availableCategories"
            variant="outlined"
            density="compact"
            hide-details
          />
        </VCol>

        <VCol
          v-if="menuConfig.show_in_menu"
          cols="12"
          md="6"
        >
          <VTextField
            v-model.number="menuConfig.menu_order"
            label="Orden en menú"
            type="number"
            variant="outlined"
            density="compact"
            hide-details
          />
        </VCol>

        <!-- Permisos -->
        <VCol
          v-if="menuConfig.show_in_menu"
          cols="12"
        >
          <VCard
            variant="outlined"
            class="pa-4 mb-4"
          >
            <VCardTitle class="text-subtitle-2 pa-0 mb-3 font-weight-medium">
              Permisos de Acceso
            </VCardTitle>

            <VRow>
              <VCol
                cols="12"
                md="6"
              >
                <VSelect
                  :model-value="menuConfig.menu_permissions?.action"
                  label="Acción"
                  :items="['read', 'manage', 'create', 'update', 'delete']"
                  variant="outlined"
                  density="compact"
                  @update:model-value="val => updatePermissions('action', val)"
                />
              </VCol>

              <VCol
                cols="12"
                md="6"
              >
                <VSelect
                  :model-value="menuConfig.menu_permissions?.subject"
                  label="Sujeto"
                  :items="['Report', 'Analytics', 'Dashboard', 'Data']"
                  variant="outlined"
                  density="compact"
                  @update:model-value="val => updatePermissions('subject', val)"
                />
              </VCol>
            </VRow>
          </VCard>
        </VCol>

        <!-- Badge opcional -->
        <VCol
          v-if="menuConfig.show_in_menu"
          cols="12"
        >
          <VCard
            variant="outlined"
            class="pa-4"
          >
            <VCardTitle class="text-subtitle-2 pa-0 mb-3 font-weight-medium">
              Badge (Opcional)
            </VCardTitle>

            <VRow>
              <VCol
                cols="12"
                md="6"
              >
                <VTextField
                  :model-value="menuConfig.menu_badge?.content"
                  label="Contenido del badge"
                  placeholder="Ej: Nuevo, 5, etc."
                  variant="outlined"
                  density="compact"
                  @update:model-value="val => updateBadge('content', val)"
                />
              </VCol>

              <VCol
                cols="12"
                md="6"
              >
                <VSelect
                  :model-value="menuConfig.menu_badge?.class"
                  label="Clase CSS del badge"
                  :items="[
                    { value: 'bg-error', label: 'Rojo' },
                    { value: 'bg-success', label: 'Verde' },
                    { value: 'bg-warning', label: 'Amarillo' },
                    { value: 'bg-info', label: 'Azul' },
                    { value: 'bg-primary', label: 'Primario' },
                  ]"
                  item-title="label"
                  item-value="value"
                  variant="outlined"
                  density="compact"
                  @update:model-value="val => updateBadge('class', val)"
                />
              </VCol>
            </VRow>
          </VCard>
        </VCol>
      </VRow>
    </VCardText>
  </VCard>
</template>

<style scoped>
/* Eliminado el borde custom para usar solo el outlined de Vuetify */
</style>
