// Generated by DDD Module Generator on 2025-07-04

import { AggregateRoot } from '../../../shared/domain/base/AggregateRoot'
import type { UniqueEntityID } from '../../../shared/domain/base/UniqueEntityID'
import { Result } from '../../../shared/domain/base/Result'
import { Guard } from '../../../shared/domain/base/Guard'
import { ExecutionId } from '../valueObjects/ExecutionId'
import { ExecutionCreated } from '../events/ExecutionCreated'
import { ExecutionUpdated } from '../events/ExecutionUpdated'
import { ExecutionDeleted } from '../events/ExecutionDeleted'

export interface ExecutionProps {
  id?: string
  report_id: string
  export_format: 'table' | 'excel' | 'pdf' | 'csv' | 'json'
  filters?: Record<string, any>
  status?: 'pending' | 'running' | 'completed' | 'failed'
  result_count?: number
  execution_time?: number
  error_message?: string
  download_url?: string
  created_at?: Date
}

export class Execution extends AggregateRoot<ExecutionProps> {
  private constructor(props: ExecutionProps, id?: UniqueEntityID) {
    super(props, id)
  }

  get executionId(): ExecutionId {
    return ExecutionId.create(this.id)
  }

  public static create(props: ExecutionProps, id?: UniqueEntityID): Result<Execution> {
    const guardResult = Guard.againstNullOrUndefinedBulk([
      { argument: props.report_id, argumentName: 'report_id' },
      { argument: props.export_format, argumentName: 'export_format' },
    ])

    if (!guardResult.succeeded)
      return Result.fail<Execution>(guardResult.message)

    const execution = new Execution({
      ...props,
      createdAt: props.createdAt || new Date(),
      updatedAt: props.updatedAt || new Date(),
    }, id)

    const isNew = !id
    if (isNew)
      execution.addDomainEvent(new ExecutionCreated(execution))

    return Result.ok<Execution>(execution)
  }

  public update(props: Partial<ExecutionProps>): Result<void> {
    const guardResult = Guard.againstNullOrUndefined(props, 'props')

    if (!guardResult.succeeded)
      return Result.fail<void>(guardResult.message)

    this.props.updatedAt = new Date()
    Object.assign(this.props, props)

    this.addDomainEvent(new ExecutionUpdated(this))

    return Result.ok<void>()
  }

  public delete(): Result<void> {
    this.addDomainEvent(new ExecutionDeleted(this))

    return Result.ok<void>()
  }

  // Getters
  get id(): string {
    return this.props.id
  }

  get report_id(): string {
    return this.props.report_id
  }

  get export_format(): 'table' | 'excel' | 'pdf' | 'csv' | 'json' {
    return this.props.export_format
  }

  get filters(): Record<string, any> {
    return this.props.filters
  }

  get status(): 'pending' | 'running' | 'completed' | 'failed' {
    return this.props.status
  }

  get result_count(): number {
    return this.props.result_count
  }

  get execution_time(): number {
    return this.props.execution_time
  }

  get error_message(): string {
    return this.props.error_message
  }

  get download_url(): string {
    return this.props.download_url
  }

  get created_at(): Date {
    return this.props.created_at
  }

  // Business Methods
  // Add business methods here
}
