/**
 * Fine Mapper - Application Layer
 *
 * Maps between domain entities and DTOs
 */

import type { FineEntity } from '../../domain/entities/FineEntity'
import type {
  FineCreateDto,
  FineDetailDto,
  FineListDto,
  FineUpdateDto,
} from '../dtos/FineDtos'

export class FineMapper {
  static toListDto(entity: FineEntity): FineListDto {
    return {
      id: entity.id,
      fine_number: entity.fineNumber,
      violation_type: entity.violationType,
      violation_description: entity.violationDescription,
      amount: entity.amount,
      penalty_points: entity.penaltyPoints,
      status: entity.status,
      issue_date: entity.issueDate,
      due_date: entity.dueDate,
      payment_date: entity.paymentDate,
      issuing_officer: entity.issuingOfficer,
      issuing_authority: entity.issuingAuthority,
      vehicle_plate: entity.vehiclePlate,
      driver_license: entity.driverLicense,
      driver_name: entity.driverName,
      location: entity.location,
      evidence_photos: entity.evidencePhotos,
      created_at: entity.createdAt,
      updated_at: entity.updatedAt,
    }
  }

  static toDetailDto(entity: FineEntity): FineDetailDto {
    return {
      ...this.toListDto(entity),
      notes: entity.notes,
      payment_method: entity.paymentMethod,
      payment_reference: entity.paymentReference,
      contest_reason: entity.contestReason,
      contest_date: entity.contestDate,
      contest_status: entity.contestStatus,
      resolution_notes: entity.resolutionNotes,
      resolved_by: entity.resolvedBy,
      resolved_at: entity.resolvedAt,
      metadata: entity.metadata,
    }
  }

  static fromCreateDto(dto: FineCreateDto): Omit<FineEntity, 'id' | 'createdAt' | 'updatedAt'> {
    return {
      fineNumber: '', // Generated by backend
      violationType: dto.violation_type,
      violationDescription: dto.violation_description,
      amount: dto.amount,
      penaltyPoints: dto.penalty_points,
      status: 'PENDING',
      issueDate: dto.issue_date,
      dueDate: dto.due_date,
      issuingOfficer: dto.issuing_officer,
      issuingAuthority: dto.issuing_authority,
      vehiclePlate: dto.vehicle_plate,
      driverLicense: dto.driver_license,
      location: dto.location,
      evidencePhotos: [],
      notes: dto.notes,
    }
  }

  static fromUpdateDto(dto: FineUpdateDto): Partial<FineEntity> {
    const updates: Partial<FineEntity> = {}

    if (dto.violation_type !== undefined)
      updates.violationType = dto.violation_type
    if (dto.violation_description !== undefined)
      updates.violationDescription = dto.violation_description
    if (dto.amount !== undefined)
      updates.amount = dto.amount
    if (dto.penalty_points !== undefined)
      updates.penaltyPoints = dto.penalty_points
    if (dto.status !== undefined)
      updates.status = dto.status
    if (dto.due_date !== undefined)
      updates.dueDate = dto.due_date
    if (dto.payment_date !== undefined)
      updates.paymentDate = dto.payment_date
    if (dto.issuing_officer !== undefined)
      updates.issuingOfficer = dto.issuing_officer
    if (dto.issuing_authority !== undefined)
      updates.issuingAuthority = dto.issuing_authority
    if (dto.location !== undefined)
      updates.location = dto.location
    if (dto.notes !== undefined)
      updates.notes = dto.notes

    return updates
  }

  static fromApiResponse(response: any): FineEntity {
    return {
      id: response.id,
      fineNumber: response.fine_number,
      violationType: response.violation_type,
      violationDescription: response.violation_description,
      amount: response.amount,
      penaltyPoints: response.penalty_points,
      status: response.status,
      issueDate: response.issue_date,
      dueDate: response.due_date,
      paymentDate: response.payment_date,
      issuingOfficer: response.issuing_officer,
      issuingAuthority: response.issuing_authority,
      vehiclePlate: response.vehicle_plate,
      driverLicense: response.driver_license,
      driverName: response.driver_name,
      location: response.location,
      evidencePhotos: response.evidence_photos || [],
      notes: response.notes,
      paymentMethod: response.payment_method,
      paymentReference: response.payment_reference,
      contestReason: response.contest_reason,
      contestDate: response.contest_date,
      contestStatus: response.contest_status,
      resolutionNotes: response.resolution_notes,
      resolvedBy: response.resolved_by,
      resolvedAt: response.resolved_at,
      metadata: response.metadata,
      createdAt: response.created_at,
      updatedAt: response.updated_at,
    }
  }

  static toApiRequest(entity: Partial<FineEntity>): Record<string, any> {
    const request: Record<string, any> = {}

    if (entity.violationType !== undefined)
      request.violation_type = entity.violationType
    if (entity.violationDescription !== undefined)
      request.violation_description = entity.violationDescription
    if (entity.amount !== undefined)
      request.amount = entity.amount
    if (entity.penaltyPoints !== undefined)
      request.penalty_points = entity.penaltyPoints
    if (entity.status !== undefined)
      request.status = entity.status
    if (entity.issueDate !== undefined)
      request.issue_date = entity.issueDate
    if (entity.dueDate !== undefined)
      request.due_date = entity.dueDate
    if (entity.paymentDate !== undefined)
      request.payment_date = entity.paymentDate
    if (entity.issuingOfficer !== undefined)
      request.issuing_officer = entity.issuingOfficer
    if (entity.issuingAuthority !== undefined)
      request.issuing_authority = entity.issuingAuthority
    if (entity.vehiclePlate !== undefined)
      request.vehicle_plate = entity.vehiclePlate
    if (entity.driverLicense !== undefined)
      request.driver_license = entity.driverLicense
    if (entity.location !== undefined)
      request.location = entity.location
    if (entity.notes !== undefined)
      request.notes = entity.notes

    return request
  }
}
