// Generated by DDD Module Generator on 2025-07-04

import type { Report } from '../entities/Report'
import type { ReportId } from '../valueObjects/ReportId'

export interface ReportRepository {
  exists(reportId: ReportId): Promise<boolean>
  getReportById(reportId: ReportId): Promise<Report>
  save(report: Report): Promise<void>
  delete(reportId: ReportId): Promise<void>
  getAll(): Promise<Report[]>
  getAllPaginated(page: number, limit: number): Promise<{
    reports: Report[]
    totalPages: number
    total: number
  }>
}
