// Generated by DDD Module Generator on 2025-07-04

import type { CreateReportCommand } from '../commands/CreateReportCommand'
import type { ReportRepository } from '../../domain/contracts/repositories/ReportRepository'
import { Report } from '../../domain/entities/Report'
import type { ReportMapper } from '../mappers/ReportMapper'
import { Result } from '../../../shared/domain/base/Result'
import type { ReportResponseDto } from '../dtos/ReportDtos'

export class CreateReportHandler {
  private reportRepository: ReportRepository
  private mapper: ReportMapper

  constructor(
    reportRepository: ReportRepository,
    mapper: ReportMapper,
  ) {
    this.reportRepository = reportRepository
    this.mapper = mapper
  }

  async execute(command: CreateReportCommand): Promise<Result<ReportResponseDto>> {
    try {
      const reportOrError = Report.create({
        ...command,
        createdAt: new Date(),
        updatedAt: new Date(),
      })

      if (reportOrError.isFailure)
        return Result.fail<ReportResponseDto>(reportOrError.error)

      const report = reportOrError.getValue()

      await this.reportRepository.save(report)

      return Result.ok<ReportResponseDto>(
        this.mapper.toDto(report),
      )
    }
    catch (err) {
      return Result.fail<ReportResponseDto>(`Unexpected error creating Report: ${err}`)
    }
  }
}
