// Generated by DDD Module Generator on 2025-07-04

import type { GetReportByIdQuery } from '../queries/GetReportByIdQuery'
import type { ReportRepository } from '../../domain/contracts/repositories/ReportRepository'
import { ReportId } from '../../domain/valueObjects/ReportId'
import type { ReportMapper } from '../mappers/ReportMapper'
import { Result } from '../../../shared/domain/base/Result'
import type { ReportResponseDto } from '../dtos/ReportDtos'
import { ReportNotFound } from '../../domain/exceptions/ReportNotFound'

export class GetReportByIdHandler {
  private reportRepository: ReportRepository
  private mapper: ReportMapper

  constructor(
    reportRepository: ReportRepository,
    mapper: ReportMapper,
  ) {
    this.reportRepository = reportRepository
    this.mapper = mapper
  }

  async execute(query: GetReportByIdQuery): Promise<Result<ReportResponseDto>> {
    try {
      const reportId = ReportId.create(query.id)
      const report = await this.reportRepository.getReportById(reportId)

      if (!report)
        return Result.fail<ReportResponseDto>(new ReportNotFound().message)

      return Result.ok<ReportResponseDto>(
        this.mapper.toDto(report),
      )
    }
    catch (err) {
      return Result.fail<ReportResponseDto>(`Unexpected error getting Report: ${err}`)
    }
  }
}
