// Generated by DDD Module Generator on 2025-07-04

import type { GetReportListQuery } from '../queries/GetReportListQuery'
import type { ReportRepository } from '../../domain/contracts/repositories/ReportRepository'
import type { ReportMapper } from '../mappers/ReportMapper'
import { Result } from '../../../shared/domain/base/Result'
import type { ReportResponseDto } from '../dtos/ReportDtos'

export class GetReportListHandler {
  private reportRepository: ReportRepository
  private mapper: ReportMapper

  constructor(
    reportRepository: ReportRepository,
    mapper: ReportMapper,
  ) {
    this.reportRepository = reportRepository
    this.mapper = mapper
  }

  async execute(query: GetReportListQuery): Promise<Result<{
    items: ReportResponseDto[]
    total: number
    totalPages: number
    page: number
    limit: number
  }>> {
    try {
      const page = query.page || 1
      const limit = query.limit || 20

      const result = await this.reportRepository.getAllPaginated(page, limit)

      return Result.ok({
        items: result.reports.map(report => this.mapper.toDto(report)),
        total: result.total,
        totalPages: result.totalPages,
        page,
        limit,
      })
    }
    catch (err) {
      return Result.fail(`Unexpected error getting Report list: ${err}`)
    }
  }
}
