// Generated by DDD Module Generator on 2025-07-04

export interface GetConnectionListQuery {
  page?: number
  limit?: number
  search?: string
  sortBy?: string
  sortOrder?: 'asc' | 'desc'
  filters?: Record<string, any>
}
