// Generated by DDD Module Generator on 2025-07-04

import type { Connection } from '../../../domain/entities/Connection'
import { ConnectionMapper } from '../../../application/mappers/ConnectionMapper'

export class ConnectionTransformer {
  static fromApi(apiData: any): Connection | null {
    return ConnectionMapper.toDomain(apiData)
  }

  static toApi(connection: Connection): any {
    return ConnectionMapper.toPersistence(connection)
  }

  static manyFromApi(apiDataArray: any[]): Connection[] {
    return apiDataArray
      .map(apiData => this.fromApi(apiData))
      .filter(Boolean) as Connection[]
  }
}
