// Generated by DDD Module Generator on 2025-07-04

import { CreateExecutionHandler } from '../handlers/CreateExecutionHandler'
import type { CreateExecutionCommand } from '../commands/CreateExecutionCommand'
import type { ExecutionRepository } from '../../domain/contracts/repositories/ExecutionRepository'
import { ExecutionMapper } from '../mappers/ExecutionMapper'

export class CreateExecutionUseCase {
  private handler: CreateExecutionHandler

  constructor(
    executionRepository: ExecutionRepository,
  ) {
    this.handler = new CreateExecutionHandler(
      executionRepository,
      ExecutionMapper,
    )
  }

  async execute(request: CreateExecutionCommand) {
    return this.handler.execute(request)
  }
}
