// Generated by DDD Module Generator on 2025-07-04

import { DeleteExecutionHandler } from '../handlers/DeleteExecutionHandler'
import type { DeleteExecutionCommand } from '../commands/DeleteExecutionCommand'
import type { ExecutionRepository } from '../../domain/contracts/repositories/ExecutionRepository'
import { ExecutionMapper } from '../mappers/ExecutionMapper'

export class DeleteExecutionUseCase {
  private handler: DeleteExecutionHandler

  constructor(
    executionRepository: ExecutionRepository,
  ) {
    this.handler = new DeleteExecutionHandler(
      executionRepository,
      ExecutionMapper,
    )
  }

  async execute(request: DeleteExecutionCommand) {
    return this.handler.execute(request)
  }
}
