// Generated by DDD Module Generator on 2025-07-04

import { GetByIdExecutionHandler } from '../handlers/GetByIdExecutionHandler'
import type { GetByIdExecutionQuery } from '../querys/GetByIdExecutionQuery'
import type { ExecutionRepository } from '../../domain/contracts/repositories/ExecutionRepository'
import { ExecutionMapper } from '../mappers/ExecutionMapper'

export class GetByIdExecutionUseCase {
  private handler: GetByIdExecutionHandler

  constructor(
    executionRepository: ExecutionRepository,
  ) {
    this.handler = new GetByIdExecutionHandler(
      executionRepository,
      ExecutionMapper,
    )
  }

  async execute(request: GetByIdExecutionQuery) {
    return this.handler.execute(request)
  }
}
