// Generated by DDD Module Generator on 2025-07-04

import { GetListExecutionHandler } from '../handlers/GetListExecutionHandler'
import type { GetListExecutionQuery } from '../querys/GetListExecutionQuery'
import type { ExecutionRepository } from '../../domain/contracts/repositories/ExecutionRepository'
import { ExecutionMapper } from '../mappers/ExecutionMapper'

export class GetListExecutionUseCase {
  private handler: GetListExecutionHandler

  constructor(
    executionRepository: ExecutionRepository,
  ) {
    this.handler = new GetListExecutionHandler(
      executionRepository,
      ExecutionMapper,
    )
  }

  async execute(request: GetListExecutionQuery) {
    return this.handler.execute(request)
  }
}
