// Generated by DDD Module Generator on 2025-07-04

import { UpdateExecutionHandler } from '../handlers/UpdateExecutionHandler'
import type { UpdateExecutionCommand } from '../commands/UpdateExecutionCommand'
import type { ExecutionRepository } from '../../domain/contracts/repositories/ExecutionRepository'
import { ExecutionMapper } from '../mappers/ExecutionMapper'

export class UpdateExecutionUseCase {
  private handler: UpdateExecutionHandler

  constructor(
    executionRepository: ExecutionRepository,
  ) {
    this.handler = new UpdateExecutionHandler(
      executionRepository,
      ExecutionMapper,
    )
  }

  async execute(request: UpdateExecutionCommand) {
    return this.handler.execute(request)
  }
}
