// Generated by DDD Module Generator on 2025-09-11

import type { Concession } from '../../../domain/entities/Concession'
import { ConcessionMapper } from '../../../application/mappers/ConcessionMapper'

export class ConcessionTransformer {
  static fromApi(apiData: any): Concession | null {
    return ConcessionMapper.toDomain(apiData)
  }

  static toApi(concession: Concession): any {
    return ConcessionMapper.toPersistence(concession)
  }

  static manyFromApi(apiDataArray: any[]): Concession[] {
    return apiDataArray
      .map(apiData => this.fromApi(apiData))
      .filter(Boolean) as Concession[]
  }
}
