#!/usr/bin/env node

import fs from 'fs'
import path from 'path'
import chalk from 'chalk'

// Modern Vue 3 Plugin Installer Template
const createModernInstaller = (moduleName, entities) => {
  const moduleNameLower = moduleName.toLowerCase()
  
  return `/**
 * ${moduleName} Module Installer
 * Modern Vue 3 Plugin with Enterprise features
 * Generated by Enterprise Module Generator
 */

import type { App } from 'vue'
import { createPinia } from 'pinia'
import type { Router } from 'vue-router'

// Module imports
import { ${moduleNameLower}Routes } from './presentation/router/routes'
import { ${moduleNameLower}Menu } from './shared/constants/menu'
import { ${moduleNameLower}Config } from './module.config'

// Services
import { logger } from './shared/services/Logger'
import { securityService } from './shared/services/SecurityService'
import { accessibilityService } from './shared/services/AccessibilityService'
import { realtimeManager } from './shared/services/WebSocketManager'

// i18n
import { initializeI18n } from './shared/i18n/config'

// Types
export interface ModuleInstallOptions {
  router?: Router
  enableLogging?: boolean
  enableSecurity?: boolean
  enableA11y?: boolean
  enableRealtime?: boolean
  permissions?: string[]
}

export interface ModuleContext {
  app: App
  router?: Router
  pinia?: any
  i18n?: any
}

export class ${moduleName}Installer {
  private context: ModuleContext
  private options: ModuleInstallOptions
  private installed = false

  constructor(app: App, options: ModuleInstallOptions = {}) {
    this.context = { app }
    this.options = {
      enableLogging: true,
      enableSecurity: true,
      enableA11y: true,
      enableRealtime: false,
      ...options
    }
  }

  /**
   * Install the module as a Vue 3 plugin
   */
  async install(): Promise<boolean> {
    if (this.installed) {
      logger.warn('${moduleName} module is already installed')
      return true
    }

    try {
      logger.info('🚀 Installing ${moduleName} module...')

      // 1. Initialize core services
      await this.initializeServices()

      // 2. Setup stores
      this.setupStores()

      // 3. Register routes
      this.registerRoutes()

      // 4. Setup i18n
      await this.setupI18n()

      // 5. Register components
      this.registerComponents()

      // 6. Setup permissions
      this.setupPermissions()

      // 7. Initialize real-time features
      if (this.options.enableRealtime) {
        await this.initializeRealtime()
      }

      this.installed = true
      logger.info('✅ ${moduleName} module installed successfully!')

      return true
    } catch (error) {
      logger.error('❌ Error installing ${moduleName} module:', error)
      return false
    }
  }

  /**
   * Uninstall the module
   */
  async uninstall(): Promise<boolean> {
    if (!this.installed) {
      logger.warn('${moduleName} module is not installed')
      return true
    }

    try {
      logger.info('🗑️ Uninstalling ${moduleName} module...')

      // Cleanup in reverse order
      if (this.options.enableRealtime) {
        realtimeManager.disconnect()
      }

      this.unregisterRoutes()
      this.unregisterComponents()

      this.installed = false
      logger.info('✅ ${moduleName} module uninstalled successfully!')

      return true
    } catch (error) {
      logger.error('❌ Error uninstalling ${moduleName} module:', error)
      return false
    }
  }

  /**
   * Initialize core services
   */
  private async initializeServices(): Promise<void> {
    if (this.options.enableSecurity) {
      // Initialize security service
      logger.info('🛡️ Initializing security service...')
    }

    if (this.options.enableA11y) {
      // Initialize accessibility service
      logger.info('♿ Initializing accessibility service...')
    }

    if (this.options.enableLogging) {
      logger.info('📊 Logging service initialized')
    }
  }

  /**
   * Setup Pinia stores
   */
  private setupStores(): void {
    logger.info('🏪 Setting up stores...')
    
    const pinia = createPinia()
    this.context.app.use(pinia)
    this.context.pinia = pinia

    // Register module stores
    ${entities.map(entity => `
    // ${entity} store will be auto-registered when imported`).join('')}
  }

  /**
   * Register Vue Router routes
   */
  private registerRoutes(): void {
    logger.info('🛣️ Registering routes...')

    const router = this.options.router || this.context.app.config.globalProperties.$router
    
    if (!router) {
      logger.warn('Router not available, routes will be registered when router is available')
      return
    }

    this.context.router = router

    // Register all module routes
    ${moduleNameLower}Routes.forEach(route => {
      router.addRoute(route)
    })

    logger.info(\`✅ Registered \${${moduleNameLower}Routes.length} routes\`)
  }

  /**
   * Setup i18n translations
   */
  private async setupI18n(): Promise<void> {
    logger.info('🌍 Setting up i18n...')

    try {
      const i18n = await initializeI18n()
      this.context.i18n = i18n
      
      // Register with app if using global i18n
      if (this.context.app.config.globalProperties.$i18n) {
        // Merge translations with global i18n
        logger.info('✅ i18n translations loaded')
      }
    } catch (error) {
      logger.warn('Failed to initialize i18n:', error)
    }
  }

  /**
   * Register Vue components globally
   */
  private registerComponents(): void {
    logger.info('🧩 Registering components...')

    // Register atomic design components globally (optional)
    // this.context.app.component('${moduleName}Button', Button)
    // this.context.app.component('${moduleName}DataTable', DataTable)

    logger.info('✅ Components registered')
  }

  /**
   * Setup permissions and abilities
   */
  private setupPermissions(): void {
    logger.info('🔐 Setting up permissions...')

    const permissions = [
      ${entities.map(entity => `
      // ${entity} permissions
      { action: 'read', subject: '${entity.toLowerCase()}' },
      { action: 'create', subject: '${entity.toLowerCase()}' },
      { action: 'update', subject: '${entity.toLowerCase()}' },
      { action: 'delete', subject: '${entity.toLowerCase()}' },`).join('')}
    ]

    // Use modern dependency injection instead of window globals
    const abilityManager = this.context.app.config.globalProperties.$ability
    if (abilityManager) {
      permissions.forEach(permission => {
        abilityManager.can(permission.action, permission.subject)
      })
    }

    logger.info(\`✅ Configured \${permissions.length} permissions\`)
  }

  /**
   * Initialize real-time features
   */
  private async initializeRealtime(): Promise<void> {
    logger.info('🔄 Initializing real-time features...')

    try {
      await realtimeManager.connect()
      logger.info('✅ Real-time connection established')
    } catch (error) {
      logger.warn('Failed to initialize real-time features:', error)
    }
  }

  /**
   * Unregister routes
   */
  private unregisterRoutes(): void {
    if (!this.context.router) return

    ${moduleNameLower}Routes.forEach(route => {
      if (route.name) {
        this.context.router!.removeRoute(route.name)
      }
    })
  }

  /**
   * Unregister components
   */
  private unregisterComponents(): void {
    // Components are automatically cleaned up by Vue
  }

  /**
   * Get module status
   */
  isInstalled(): boolean {
    return this.installed
  }

  /**
   * Get module configuration
   */
  getConfig() {
    return ${moduleNameLower}Config
  }
}

/**
 * Vue 3 Plugin factory
 */
export function create${moduleName}Plugin(options: ModuleInstallOptions = {}) {
  return {
    install(app: App) {
      const installer = new ${moduleName}Installer(app, options)
      return installer.install()
    }
  }
}

/**
 * Direct installation function
 */
export async function install${moduleName}(app: App, options: ModuleInstallOptions = {}): Promise<boolean> {
  const installer = new ${moduleName}Installer(app, options)
  return installer.install()
}

/**
 * Default export as Vue 3 plugin
 */
export default create${moduleName}Plugin()`
}

// Update module index.ts to use modern installer
const updateModuleIndex = (moduleName, entities) => {
  const moduleNameLower = moduleName.toLowerCase()
  
  return `// ${moduleName} Module
// Generated with Enterprise Architecture Generator

import type { App } from 'vue'

// Modern installer
import { install${moduleName}, create${moduleName}Plugin } from './installer'

// Module configuration
import { ${moduleNameLower}Config } from './module.config'

// Export everything from the module
export * from './domain/entities'
export * from './application/dtos'
export * from './infrastructure/api/services'
export * from './presentation/stores'
export * from './presentation/router/routes'

// Module metadata
export const moduleInfo = {
  name: '${moduleNameLower}',
  version: ${moduleNameLower}Config.version,
  description: ${moduleNameLower}Config.description,
  entities: ${JSON.stringify(entities)},
  
  // Installation methods
  install: install${moduleName},
  createPlugin: create${moduleName}Plugin,
  
  // Configuration
  config: ${moduleNameLower}Config
}

// Default export as Vue 3 plugin
export default create${moduleName}Plugin()`
}

// Main generator function
export async function generateModuleInstaller(moduleName, entities) {
  const modulePath = path.join('src/modules', moduleName)
  
  console.log(chalk.blue(`🔧 Generating Modern Installer for: ${moduleName}`))
  
  // Create installer
  const installerPath = path.join(modulePath, 'installer.ts')
  const installerContent = createModernInstaller(moduleName, entities)
  
  fs.writeFileSync(installerPath, installerContent, 'utf8')
  console.log(chalk.green('✅ Modern installer generated'))
  
  // Update index.ts
  const indexPath = path.join(modulePath, 'index.ts')
  const indexContent = updateModuleIndex(moduleName, entities)
  
  fs.writeFileSync(indexPath, indexContent, 'utf8')
  console.log(chalk.green('✅ Module index updated'))
  
  return { installerPath, indexPath }
}

// Run if called directly
if (import.meta.url === `file://${process.argv[1]}`) {
  const moduleName = process.argv[2] || 'DashboardMonitor'
  const entities = ['Reader', 'Route', 'Reading', 'Meter']
  
  generateModuleInstaller(moduleName, entities)
    .then(() => {
      console.log(chalk.green.bold('\n🎉 Modern installer generated successfully!'))
    })
    .catch(error => {
      console.error(chalk.red(`Error: ${error.message}`))
    })
} 
