// Generated by DDD Module Generator on 2025-07-04

import { ValueObject } from '../../../shared/domain/base/ValueObject'
import { UniqueEntityID } from '../../../shared/domain/base/UniqueEntityID'

interface ExecutionIdProps {
  value: string
}

export class ExecutionId extends ValueObject<ExecutionIdProps> {
  get value(): string {
    return this.props.value
  }

  private constructor(props: ExecutionIdProps) {
    super(props)
  }

  public static create(id: UniqueEntityID | string): ExecutionId {
    const idValue = id instanceof UniqueEntityID ? id.toString() : id

    return new ExecutionId({ value: idValue })
  }

  public static createUnique(): ExecutionId {
    return new ExecutionId({ value: new UniqueEntityID().toString() })
  }
}
