// Generated by DDD Module Generator on 2025-07-04

import * as yup from 'yup'

export const connectionCreateValidation = yup.object({
  name: yup.string().required('name is required'),
  driver: yup.string().oneOf(['mysql', 'pgsql', 'sqlsrv', 'oracle', 'sqlite']).required('driver is required'),
  host: yup.string().required('host is required'),
  port: yup.number().required('port is required'),
  database_name: yup.string().required('database_name is required'),
  username: yup.string().required('username is required'),
  password: yup.string().required('password is required'),
  status: yup.string().oneOf(['active', 'inactive', 'testing', 'error']),
})

export const connectionUpdateValidation = yup.object({
  name: yup.string(),
  driver: yup.string().oneOf(['mysql', 'pgsql', 'sqlsrv', 'oracle', 'sqlite']),
  host: yup.string(),
  port: yup.number(),
  database_name: yup.string(),
  username: yup.string(),
  password: yup.string(),
  status: yup.string().oneOf(['active', 'inactive', 'testing', 'error']),
})
