// Generated by DDD Module Generator on 2025-07-04

export interface UpdateReportCommand {
  id: string
  data_source_id: string
  name: string
  description?: string
  selected_fields: Record<string, any>
  export_formats: Record<string, any>
  default_filters?: Record<string, any>
  is_public?: boolean
}
