// Generated by DDD Module Generator on 2025-07-04

import { Connection } from '../../domain/entities/Connection'
import type { ConnectionResponseDto } from '../dtos/ConnectionDtos'
import { UniqueEntityID } from '../../../shared/domain/base/UniqueEntityID'

export class ConnectionMapper {
  public static toDto(connection: Connection): ConnectionResponseDto {
    return {
      id: connection.id.toString(),
      name: connection.props.name,
      driver: connection.props.driver,
      host: connection.props.host,
      port: connection.props.port,
      database_name: connection.props.database_name,
      username: connection.props.username,
      password: connection.props.password,
      status: connection.props.status,
      created_at: connection.props.created_at,
      updated_at: connection.props.updated_at,
      createdAt: connection.props.created_at,
      updatedAt: connection.props.updated_at,
      company_id: connection.props.company_id,
      description: connection.props.description,
      is_active: connection.props.is_active,
      options: connection.props.options,
      created_by: connection.props.created_by,
      connection_string: connection.props.connection_string,
    }
  }

  public static toDomain(raw: any): Connection {
    const connectionOrError = Connection.create(
      {
        name: raw.name,
        driver: raw.driver,
        host: raw.host,
        port: raw.port,
        database_name: raw.database_name,
        username: raw.username,
        password: raw.password || '',
        status: raw.status || (raw.is_active ? 'active' : 'inactive'),
        created_at: raw.created_at ? new Date(raw.created_at) : new Date(),
        updated_at: raw.updated_at ? new Date(raw.updated_at) : new Date(),
        company_id: raw.company_id,
        description: raw.description,
        is_active: raw.is_active,
        options: raw.options || [],
        created_by: raw.created_by,
        connection_string: raw.connection_string,
      },
      new UniqueEntityID(raw.id),
    )

    return connectionOrError.isSuccess
      ? connectionOrError.getValue()
      : null
  }

  public static toPersistence(connection: Connection): any {
    return {
      id: connection.id.toString(),
      name: connection.props.name,
      driver: connection.props.driver,
      host: connection.props.host,
      port: connection.props.port,
      database_name: connection.props.database_name,
      username: connection.props.username,
      password: connection.props.password,
      status: connection.props.status,
      created_at: connection.props.created_at,
      updated_at: connection.props.updated_at,
      createdAt: connection.props.created_at,
      updatedAt: connection.props.updated_at,
      company_id: connection.props.company_id,
      description: connection.props.description,
      is_active: connection.props.is_active,
      options: connection.props.options,
      created_by: connection.props.created_by,
      connection_string: connection.props.connection_string,
    }
  }
}
