<!-- Generated by DDD Module Generator on 2025-07-04 -->
<script setup lang="ts">
import { useForm } from 'vee-validate'
import { toTypedSchema } from '@vee-validate/zod'
import * as z from 'zod'
import { useExecutionStore } from '../../stores/executionStore'

interface Props {
  mode: 'create' | 'edit'
  initialData?: any
  title?: string
  loading?: boolean
}

interface Emits {
  (e: 'submit', data: any): void
  (e: 'cancel'): void
  (e: 'close'): void
}

const props = withDefaults(defineProps<Props>(), {
  title: 'Execution Form',
  loading: false,
})

const emit = defineEmits<Emits>()
const executionStore = useExecutionStore()
const { closeDialog } = useAppManager()

// Form validation schema
const schema = toTypedSchema(z.object({
  report_id: z.any().min(1, 'This field is required'),
  export_format: z.enum(['table', 'excel', 'pdf', 'csv', 'json']),
  filters: z.any(),
  status: z.enum(['pending', 'running', 'completed', 'failed']),
  result_count: z.number(),
  execution_time: z.number(),
  error_message: z.string(),
  download_url: z.string(),
}))

const { handleSubmit, errors, values, setFieldValue } = useForm({
  validationSchema: schema,
  initialValues: props.initialData || {},
})

const onSubmit = handleSubmit(async values => {
  try {
    if (props.mode === 'create')
      await executionStore.createItem(values)
    else if (props.mode === 'edit')
      await executionStore.updateItem(values.id, values)

    close('submit', values)
  }
  catch (error) {
    // Opcional: mostrar error
    console.error(error)
  }
})

function close(result: 'close' | 'submit' | 'cancel' = 'close') {
  closeDialog(result)
}
</script>

<template>
  <VForm @submit.prevent="handleSubmit">
    <DialogCloseBtn @click="close('cancel')" />
    <VCard>
      <VCardTitle>{{ title }}</VCardTitle>
      <VCardText>
        <VRow>
          <VCol cols="12">
            <VTextField
              :model-value="values.report_id"
              label="Report Id"
              :error-messages="errors.report_id"
              @update:model-value="val => setFieldValue('report_id', val)"
            />
          </VCol>
          <VCol cols="12">
            <VSelect
              :model-value="values.export_format"
              label="Export Format"
              :error-messages="errors.export_format"
              :items="[
                { title: 'table', value: 'table' },
                { title: 'excel', value: 'excel' },
                { title: 'pdf', value: 'pdf' },
                { title: 'csv', value: 'csv' },
                { title: 'json', value: 'json' },
              ]"
              @update:model-value="val => setFieldValue('export_format', val)"
            />
          </VCol>
          <VCol cols="12">
            <VTextField
              :model-value="values.filters"
              label="Filters"
              :error-messages="errors.filters"
              @update:model-value="val => setFieldValue('filters', val)"
            />
          </VCol>
          <VCol cols="12">
            <VSelect
              :model-value="values.status"
              label="Status"
              :error-messages="errors.status"
              :items="[
                { title: 'pending', value: 'pending' },
                { title: 'running', value: 'running' },
                { title: 'completed', value: 'completed' },
                { title: 'failed', value: 'failed' },
              ]"
              @update:model-value="val => setFieldValue('status', val)"
            />
          </VCol>
          <VCol cols="12">
            <VTextField
              :model-value="values.result_count"
              label="Result Count"
              :error-messages="errors.result_count"
              @update:model-value="val => setFieldValue('result_count', val === '' ? undefined : Number(val))"
            />
          </VCol>
          <VCol cols="12">
            <VTextField
              :model-value="values.execution_time"
              label="Execution Time"
              :error-messages="errors.execution_time"
              @update:model-value="val => setFieldValue('execution_time', val === '' ? undefined : Number(val))"
            />
          </VCol>
          <VCol cols="12">
            <VTextField
              :model-value="values.error_message"
              label="Error Message"
              :error-messages="errors.error_message"
              @update:model-value="val => setFieldValue('error_message', val)"
            />
          </VCol>
          <VCol cols="12">
            <VTextField
              :model-value="values.download_url"
              label="Download Url"
              :error-messages="errors.download_url"
              @update:model-value="val => setFieldValue('download_url', val)"
            />
          </VCol>
        </VRow>
      </VCardText>
      <VCardActions>
        <VBtn
          type="submit"
          color="primary"
          :loading="loading"
        >
          {{ mode === 'create' ? 'Create' : 'Update' }}
        </VBtn>
        <VBtn
          color="secondary"
          variant="tonal"
          @click="close('cancel')"
        >
          Cancel
        </VBtn>
      </VCardActions>
    </VCard>
  </VForm>
</template>
