<!-- Generated by DDD Module Generator on 2025-07-04 -->
<script setup lang="ts">
interface Props {
  execution: any
}

const props = defineProps<Props>()
</script>

<template>
  <div class="execution-detail">
    <VList>
      <VListItem>
        <VListItemTitle>{ t('Report Id') }</VListItemTitle>
        <VListItemSubtitle>{{ execution.report_id }}</VListItemSubtitle>
      </VListItem>
      <VListItem>
        <VListItemTitle>{ t('Export Format') }</VListItemTitle>
        <VListItemSubtitle>{{ execution.export_format }}</VListItemSubtitle>
      </VListItem>
      <VListItem>
        <VListItemTitle>{ t('Filters') }</VListItemTitle>
        <VListItemSubtitle>{{ execution.filters }}</VListItemSubtitle>
      </VListItem>
      <VListItem>
        <VListItemTitle>{ t('Status') }</VListItemTitle>
        <VListItemSubtitle>{{ execution.status }}</VListItemSubtitle>
      </VListItem>
      <VListItem>
        <VListItemTitle>{ t('Result Count') }</VListItemTitle>
        <VListItemSubtitle>{{ execution.result_count }}</VListItemSubtitle>
      </VListItem>
      <VListItem>
        <VListItemTitle>{ t('Execution Time') }</VListItemTitle>
        <VListItemSubtitle>{{ execution.execution_time }}</VListItemSubtitle>
      </VListItem>
      <VListItem>
        <VListItemTitle>{ t('Error Message') }</VListItemTitle>
        <VListItemSubtitle>{{ execution.error_message }}</VListItemSubtitle>
      </VListItem>
      <VListItem>
        <VListItemTitle>{ t('Download URL') }</VListItemTitle>
        <VListItemSubtitle>{{ execution.download_url }}</VListItemSubtitle>
      </VListItem>
    </VList>
  </div>
</template>
