// Generated by DDD Module Generator on 2025-07-04

import type { CreateConnectionCommand } from '../commands/CreateConnectionCommand'
import type { ConnectionRepository } from '../../domain/contracts/repositories/ConnectionRepository'
import { Connection } from '../../domain/entities/Connection'
import type { ConnectionMapper } from '../mappers/ConnectionMapper'
import { Result } from '../../../shared/domain/base/Result'
import type { ConnectionResponseDto } from '../dtos/ConnectionDtos'

export class CreateConnectionHandler {
  private connectionRepository: ConnectionRepository
  private mapper: ConnectionMapper

  constructor(
    connectionRepository: ConnectionRepository,
    mapper: ConnectionMapper,
  ) {
    this.connectionRepository = connectionRepository
    this.mapper = mapper
  }

  async execute(command: CreateConnectionCommand): Promise<Result<ConnectionResponseDto>> {
    try {
      const connectionOrError = Connection.create({
        ...command,
        createdAt: new Date(),
        updatedAt: new Date(),
      })

      if (connectionOrError.isFailure)
        return Result.fail<ConnectionResponseDto>(connectionOrError.error)

      const connection = connectionOrError.getValue()

      await this.connectionRepository.save(connection)

      return Result.ok<ConnectionResponseDto>(
        this.mapper.toDto(connection),
      )
    }
    catch (err) {
      return Result.fail<ConnectionResponseDto>(`Unexpected error creating Connection: ${err}`)
    }
  }
}
