// Generated by DDD Module Generator on 2025-07-04

import type { DeleteConnectionCommand } from '../commands/DeleteConnectionCommand'
import type { ConnectionRepository } from '../../domain/contracts/repositories/ConnectionRepository'
import { ConnectionId } from '../../domain/valueObjects/ConnectionId'
import { Result } from '../../../shared/domain/base/Result'
import { ConnectionNotFound } from '../../domain/exceptions/ConnectionNotFound'

export class DeleteConnectionHandler {
  private connectionRepository: ConnectionRepository

  constructor(connectionRepository: ConnectionRepository) {
    this.connectionRepository = connectionRepository
  }

  async execute(command: DeleteConnectionCommand): Promise<Result<void>> {
    try {
      const connectionId = ConnectionId.create(command.id)
      const exists = await this.connectionRepository.exists(connectionId)

      if (!exists)
        return Result.fail<void>(new ConnectionNotFound().message)

      await this.connectionRepository.delete(connectionId)

      return Result.ok<void>()
    }
    catch (err) {
      return Result.fail<void>(`Unexpected error deleting Connection: ${err}`)
    }
  }
}
