// Generated by DDD Module Generator on 2025-07-04

import type { GetConnectionByIdQuery } from '../queries/GetConnectionByIdQuery'
import type { ConnectionRepository } from '../../domain/contracts/repositories/ConnectionRepository'
import { ConnectionId } from '../../domain/valueObjects/ConnectionId'
import type { ConnectionMapper } from '../mappers/ConnectionMapper'
import { Result } from '../../../shared/domain/base/Result'
import type { ConnectionResponseDto } from '../dtos/ConnectionDtos'
import { ConnectionNotFound } from '../../domain/exceptions/ConnectionNotFound'

export class GetConnectionByIdHandler {
  private connectionRepository: ConnectionRepository
  private mapper: ConnectionMapper

  constructor(
    connectionRepository: ConnectionRepository,
    mapper: ConnectionMapper,
  ) {
    this.connectionRepository = connectionRepository
    this.mapper = mapper
  }

  async execute(query: GetConnectionByIdQuery): Promise<Result<ConnectionResponseDto>> {
    try {
      const connectionId = ConnectionId.create(query.id)
      const connection = await this.connectionRepository.getConnectionById(connectionId)

      if (!connection)
        return Result.fail<ConnectionResponseDto>(new ConnectionNotFound().message)

      return Result.ok<ConnectionResponseDto>(
        this.mapper.toDto(connection),
      )
    }
    catch (err) {
      return Result.fail<ConnectionResponseDto>(`Unexpected error getting Connection: ${err}`)
    }
  }
}
