// Generated by DDD Module Generator on 2025-07-04

import type { GetConnectionListQuery } from '../queries/GetConnectionListQuery'
import type { ConnectionRepository } from '../../domain/contracts/repositories/ConnectionRepository'
import type { ConnectionMapper } from '../mappers/ConnectionMapper'
import { Result } from '../../../shared/domain/base/Result'
import type { ConnectionResponseDto } from '../dtos/ConnectionDtos'

export class GetConnectionListHandler {
  private connectionRepository: ConnectionRepository
  private mapper: ConnectionMapper

  constructor(
    connectionRepository: ConnectionRepository,
    mapper: ConnectionMapper,
  ) {
    this.connectionRepository = connectionRepository
    this.mapper = mapper
  }

  async execute(query: GetConnectionListQuery): Promise<Result<{
    items: ConnectionResponseDto[]
    total: number
    totalPages: number
    page: number
    limit: number
  }>> {
    try {
      const page = query.page || 1
      const limit = query.limit || 20

      const result = await this.connectionRepository.getAllPaginated(page, limit)

      return Result.ok({
        items: result.connections.map(connection => this.mapper.toDto(connection)),
        total: result.total,
        totalPages: result.totalPages,
        page,
        limit,
      })
    }
    catch (err) {
      return Result.fail(`Unexpected error getting Connection list: ${err}`)
    }
  }
}
