// Generated by DDD Module Generator on 2025-07-04

import type { UpdateConnectionCommand } from '../commands/UpdateConnectionCommand'
import type { ConnectionRepository } from '../../domain/contracts/repositories/ConnectionRepository'
import { ConnectionId } from '../../domain/valueObjects/ConnectionId'
import type { ConnectionMapper } from '../mappers/ConnectionMapper'
import { Result } from '../../../shared/domain/base/Result'
import type { ConnectionResponseDto } from '../dtos/ConnectionDtos'
import { ConnectionNotFound } from '../../domain/exceptions/ConnectionNotFound'

export class UpdateConnectionHandler {
  private connectionRepository: ConnectionRepository
  private mapper: ConnectionMapper

  constructor(
    connectionRepository: ConnectionRepository,
    mapper: ConnectionMapper,
  ) {
    this.connectionRepository = connectionRepository
    this.mapper = mapper
  }

  async execute(command: UpdateConnectionCommand): Promise<Result<ConnectionResponseDto>> {
    try {
      const connectionId = ConnectionId.create(command.id)
      const connection = await this.connectionRepository.getConnectionById(connectionId)

      if (!connection)
        return Result.fail<ConnectionResponseDto>(new ConnectionNotFound().message)

      const { id, ...updateData } = command
      const updateResult = connection.update(updateData)

      if (updateResult.isFailure)
        return Result.fail<ConnectionResponseDto>(updateResult.error)

      await this.connectionRepository.save(connection)

      return Result.ok<ConnectionResponseDto>(
        this.mapper.toDto(connection),
      )
    }
    catch (err) {
      return Result.fail<ConnectionResponseDto>(`Unexpected error updating Connection: ${err}`)
    }
  }
}
