// Generated by DDD Module Generator

import { rawApi } from '@/services/api'

export class VehicleApiService {
  private readonly baseUrl = '/transport/vehicles'

  async create(data: any) {
    return await rawApi(this.baseUrl, { method: 'POST', body: data })
  }

  async update(id: string, data: any) {
    return await rawApi(`${this.baseUrl}/${id}`, { method: 'PUT', body: data })
  }

  async delete(id: string) {
    return await rawApi(`${this.baseUrl}/${id}`, { method: 'DELETE' })
  }

  async getById(id: string) {
    return await rawApi(`${this.baseUrl}/${id}`, { method: 'GET' })
  }

  async getAll() {
    return await rawApi(this.baseUrl, { method: 'GET' })
  }

  async getList(params: any) {
    return await rawApi(this.baseUrl, { method: 'GET', params })
  }

  // Vehicle specific methods
  async assignToConcession(vehicleId: string, concessionId: string) {
    return await rawApi(`${this.baseUrl}/${vehicleId}/assign`, {
      method: 'POST',
      body: { concession_id: concessionId },
    })
  }

  async unassignFromConcession(vehicleId: string) {
    return await rawApi(`${this.baseUrl}/${vehicleId}/unassign`, { method: 'POST' })
  }

  async getVehicleHistory(id: string) {
    return await rawApi(`${this.baseUrl}/${id}/history`, { method: 'GET' })
  }

  async exportVehicles(params: any) {
    return await rawApi(`${this.baseUrl}/export`, { method: 'GET', params })
  }
}
