// Generated by DDD Module Generator on 2025-07-04

import type { NavLink, VerticalNavItems } from '@/@layouts/types'
import { can } from '@/@layouts/plugins/casl'
import { useReportStore } from '../stores/reportStore'

export class DynamicMenuService {
  private static instance: DynamicMenuService
  private reportStore = useReportStore()

  public static getInstance(): DynamicMenuService {
    if (!DynamicMenuService.instance)
      DynamicMenuService.instance = new DynamicMenuService()

    return DynamicMenuService.instance
  }

  /**
   * Genera menús dinámicos basados en los reportes configurados
   * Ahora los agrega como hijos del nodo 'Reports' si existe, o crea uno nuevo si no existe.
   */
  async generateDynamicMenus(): Promise<VerticalNavItems> {
    try {
      // Obtener todos los reportes del store
      await this.reportStore.fetchList()

      const reports = this.reportStore.list

      // Filtrar reportes que deben aparecer en el menú
      const menuReports = reports.filter(report =>
        report.menu_config?.show_in_menu
        && can(report.menu_config?.menu_permissions?.action, report.menu_config?.menu_permissions?.subject),
      )

      // Generar items de menú para los reportes
      const dynamicReportMenus: NavLink[] = menuReports.map(report => this.createMenuItemFromReport(report)).filter(Boolean) as NavLink[]

      // Obtener el store de menú y el menú base
      const { useMenuStore } = await import('@/stores/menu')
      const menuStore = useMenuStore()
      const baseMenus = menuStore.baseNavItems ? [...menuStore.baseNavItems] : []

      // Buscar el nodo 'Reports'
      let reportsNode = baseMenus.find(item => item.title === 'Reports') as any

      if (reportsNode) {
        // Si ya tiene hijos, combinarlos (sin duplicar los dinámicos)
        const staticChildren = (reportsNode.children || []).filter((child: any) => !child.isDynamic)

        reportsNode.children = [
          ...staticChildren,
          ...dynamicReportMenus.map(menu => ({ ...menu, isDynamic: true })),
        ]
      }
      else {
        // Si no existe, crear el nodo 'Reports' al mismo nivel
        reportsNode = {
          title: 'Reports',
          icon: { icon: 'tabler-report' },
          children: dynamicReportMenus.map(menu => ({ ...menu, isDynamic: true })),
        }
        baseMenus.unshift(reportsNode)
      }

      // Eliminar posibles duplicados de nodos 'Reports'
      return baseMenus.filter((item, idx, arr) =>
        arr.findIndex(i => i.title === item.title) === idx,
      )
    }
    catch (error) {
      console.error('Error generando menús dinámicos:', error)

      return []
    }
  }

  /**
   * Crea un item de menú a partir de un reporte
   */
  private createMenuItemFromReport(report: any): NavLink | null {
    if (!report.menu_config?.show_in_menu)
      return null

    return {
      title: report.menu_config.menu_title || report.name,
      icon: { icon: report.menu_config.menu_icon || 'tabler-chart-bar' },
      to: { name: 'reports-viewer-id', params: { id: report.id } },
      action: report.menu_config.menu_permissions?.action || 'read',
      subject: report.menu_config.menu_permissions?.subject || 'Report',
      badge: report.menu_config.menu_badge,
      isDynamic: true,
    }
  }

  /**
   * Actualiza los menús dinámicos en el store de navegación
   */
  async updateDynamicMenus(): Promise<void> {
    const { useMenuStore } = await import('@/stores/menu')
    const menuStore = useMenuStore()

    const dynamicMenus = await this.generateDynamicMenus()

    // Actualizar el store
    menuStore.setNavItems(dynamicMenus)
  }

  /**
   * Registra un reporte en el menú
   */
  async registerReportInMenu(reportId: string): Promise<void> {
    try {
      // Recargar el reporte específico
      await this.reportStore.fetchById(reportId)

      // Actualizar menús
      await this.updateDynamicMenus()
    }
    catch (error) {
      console.error('Error registrando reporte en menú:', error)
    }
  }

  /**
   * Desregistra un reporte del menú
   */
  async unregisterReportFromMenu(reportId: string): Promise<void> {
    try {
      // Actualizar menús (automáticamente excluirá el reporte si no tiene show_in_menu)
      await this.updateDynamicMenus()
    }
    catch (error) {
      console.error('Error desregistrando reporte del menú:', error)
    }
  }
}
