// Generated by DDD Module Generator on 2025-07-04

import { DynamicMenuService } from '../application/services/DynamicMenuService'
import { useReportStore } from '../stores/reportStore'

export class DynamicMenuPlugin {
  private static instance: DynamicMenuPlugin
  private menuService: DynamicMenuService
  private reportStore = useReportStore()

  private constructor() {
    this.menuService = DynamicMenuService.getInstance()
  }

  public static getInstance(): DynamicMenuPlugin {
    if (!DynamicMenuPlugin.instance)
      DynamicMenuPlugin.instance = new DynamicMenuPlugin()

    return DynamicMenuPlugin.instance
  }

  /**
   * Inicializa el plugin de menús dinámicos
   */
  async initialize(): Promise<void> {
    try {
      // Actualizar menús al inicializar
      await this.menuService.updateDynamicMenus()

      // Escuchar cambios en el store de reportes
      this.setupStoreWatchers()

      console.log('✅ Plugin de menús dinámicos inicializado')
    }
    catch (error) {
      console.error('❌ Error inicializando plugin de menús dinámicos:', error)
    }
  }

  /**
   * Configura watchers para el store de reportes
   */
  private setupStoreWatchers(): void {
    // Observar cambios en la lista de reportes
    watch(
      () => this.reportStore.list,
      async () => {
        await this.menuService.updateDynamicMenus()
      },
      { deep: true },
    )

    // Observar cambios en reportes individuales
    watch(
      () => this.reportStore.item,
      async newReport => {
        if (newReport?.id)
          await this.menuService.registerReportInMenu(newReport.id)
      },
      { deep: true },
    )
  }

  /**
   * Registra un reporte en el menú
   */
  async registerReport(reportId: string): Promise<void> {
    try {
      await this.menuService.registerReportInMenu(reportId)
      console.log(`✅ Reporte ${reportId} registrado en menú`)
    }
    catch (error) {
      console.error(`❌ Error registrando reporte ${reportId} en menú:`, error)
    }
  }

  /**
   * Desregistra un reporte del menú
   */
  async unregisterReport(reportId: string): Promise<void> {
    try {
      await this.menuService.unregisterReportFromMenu(reportId)
      console.log(`✅ Reporte ${reportId} desregistrado del menú`)
    }
    catch (error) {
      console.error(`❌ Error desregistrando reporte ${reportId} del menú:`, error)
    }
  }

  /**
   * Actualiza los menús dinámicos
   */
  async refreshMenus(): Promise<void> {
    try {
      await this.menuService.updateDynamicMenus()
      console.log('✅ Menús dinámicos actualizados')
    }
    catch (error) {
      console.error('❌ Error actualizando menús dinámicos:', error)
    }
  }

  /**
   * Obtiene la configuración de menú de un reporte
   */
  getReportMenuConfig(reportId: string): any {
    const report = this.reportStore.list.find(r => r.id === reportId)

    return report?.menu_config || null
  }

  /**
   * Verifica si un reporte está visible en el menú
   */
  isReportVisibleInMenu(reportId: string): boolean {
    const report = this.reportStore.list.find(r => r.id === reportId)

    return report?.menu_config?.show_in_menu || false
  }
}

// Exportar instancia singleton
export const dynamicMenuPlugin = DynamicMenuPlugin.getInstance()
