// Generated by DDD Module Generator on 2025-07-04

import type { Connection } from '../entities/Connection'
import type { ConnectionId } from '../valueObjects/ConnectionId'

export interface ConnectionRepository {
  exists(connectionId: ConnectionId): Promise<boolean>
  getConnectionById(connectionId: ConnectionId): Promise<Connection>
  save(connection: Connection): Promise<void>
  delete(connectionId: ConnectionId): Promise<void>
  getAll(): Promise<Connection[]>
  getAllPaginated(page: number, limit: number): Promise<{
    connections: Connection[]
    totalPages: number
    total: number
  }>
}
