// Generated by DDD Module Generator on 2025-07-04

import { CreateDataSourceHandler } from '../handlers/CreateDataSourceHandler'
import type { CreateDataSourceCommand } from '../commands/CreateDataSourceCommand'
import type { DataSourceRepository } from '../../domain/contracts/repositories/DataSourceRepository'
import { DataSourceMapper } from '../mappers/DataSourceMapper'

export class CreateDataSourceUseCase {
  private handler: CreateDataSourceHandler

  constructor(
    dataSourceRepository: DataSourceRepository,
  ) {
    this.handler = new CreateDataSourceHandler(
      dataSourceRepository,
      DataSourceMapper,
    )
  }

  async execute(request: CreateDataSourceCommand) {
    return this.handler.execute(request)
  }
}
