// Generated by DDD Module Generator on 2025-07-04

import { DeleteDataSourceHandler } from '../handlers/DeleteDataSourceHandler'
import type { DeleteDataSourceCommand } from '../commands/DeleteDataSourceCommand'
import type { DataSourceRepository } from '../../domain/contracts/repositories/DataSourceRepository'
import { DataSourceMapper } from '../mappers/DataSourceMapper'

export class DeleteDataSourceUseCase {
  private handler: DeleteDataSourceHandler

  constructor(
    dataSourceRepository: DataSourceRepository,
  ) {
    this.handler = new DeleteDataSourceHandler(
      dataSourceRepository,
      DataSourceMapper,
    )
  }

  async execute(request: DeleteDataSourceCommand) {
    return this.handler.execute(request)
  }
}
