// Generated by DDD Module Generator on 2025-07-04

import { GetByIdDataSourceHandler } from '../handlers/GetByIdDataSourceHandler'
import type { GetByIdDataSourceQuery } from '../querys/GetByIdDataSourceQuery'
import type { DataSourceRepository } from '../../domain/contracts/repositories/DataSourceRepository'
import { DataSourceMapper } from '../mappers/DataSourceMapper'

export class GetByIdDataSourceUseCase {
  private handler: GetByIdDataSourceHandler

  constructor(
    dataSourceRepository: DataSourceRepository,
  ) {
    this.handler = new GetByIdDataSourceHandler(
      dataSourceRepository,
      DataSourceMapper,
    )
  }

  async execute(request: GetByIdDataSourceQuery) {
    return this.handler.execute(request)
  }
}
