// Generated by DDD Module Generator on 2025-07-04

import { GetListDataSourceHandler } from '../handlers/GetListDataSourceHandler'
import type { GetListDataSourceQuery } from '../querys/GetListDataSourceQuery'
import type { DataSourceRepository } from '../../domain/contracts/repositories/DataSourceRepository'
import { DataSourceMapper } from '../mappers/DataSourceMapper'

export class GetListDataSourceUseCase {
  private handler: GetListDataSourceHandler

  constructor(
    dataSourceRepository: DataSourceRepository,
  ) {
    this.handler = new GetListDataSourceHandler(
      dataSourceRepository,
      DataSourceMapper,
    )
  }

  async execute(request: GetListDataSourceQuery) {
    return this.handler.execute(request)
  }
}
