// Generated by DDD Module Generator on 2025-07-04

import { UpdateDataSourceHandler } from '../handlers/UpdateDataSourceHandler'
import type { UpdateDataSourceCommand } from '../commands/UpdateDataSourceCommand'
import type { DataSourceRepository } from '../../domain/contracts/repositories/DataSourceRepository'
import { DataSourceMapper } from '../mappers/DataSourceMapper'

export class UpdateDataSourceUseCase {
  private handler: UpdateDataSourceHandler

  constructor(
    dataSourceRepository: DataSourceRepository,
  ) {
    this.handler = new UpdateDataSourceHandler(
      dataSourceRepository,
      DataSourceMapper,
    )
  }

  async execute(request: UpdateDataSourceCommand) {
    return this.handler.execute(request)
  }
}
