// Generated by DDD Module Generator on 2025-07-04

import * as yup from 'yup'

export const dataSourceCreateValidation = yup.object({
  connection_id: yup.mixed().required('connection_id is required'),
  name: yup.string().required('name is required'),
  type: yup.string().oneOf(['custom_sql', 'visual_builder', 'hybrid']).required('type is required'),
  custom_sql: yup.string(),
  available_fields: yup.mixed().required('available_fields is required'),
})

export const dataSourceUpdateValidation = yup.object({
  connection_id: yup.mixed(),
  name: yup.string(),
  type: yup.string().oneOf(['custom_sql', 'visual_builder', 'hybrid']),
  custom_sql: yup.string(),
  available_fields: yup.mixed(),
})
