<!-- Generated by DDD Module Generator on 2025-07-04 -->
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { useI18n } from 'vue-i18n'
import { useConnectionStore } from '../stores/connectionStore'

const route = useRoute()
const store = useConnectionStore()
const currentItem = computed(() => store.currentItem)
const { t } = useI18n()
const copied = ref(false)

function copyConnectionString(str: string) {
  navigator.clipboard.writeText(str)
  copied.value = true
  setTimeout(() => (copied.value = false), 1500)
}

onMounted(async () => {
  await store.fetchById(route.params.id as string)
})
</script>

<template>
  <VCard>
    <VCardTitle>
      <h4 class="text-h4 mb-1">
        {{ t('connection.details_title', 'Connection Details') }}
      </h4>
      <p class="text-body-1 mb-4">
        {{ t('connection.details_subtitle', 'View connection information') }}
      </p>
    </VCardTitle>
    <VCardText>
      <div
        v-if="currentItem && Object.keys(currentItem || {}).length > 0"
        class="connection-detail"
      >
        <VCard flat>
          <VCardText>
            <VRow dense>
              <VCol
                v-if="currentItem?.name"
                cols="12"
                md="6"
              >
                <strong>{{ t('connection.name', 'Name') }}:</strong> {{ currentItem.name }}
              </VCol>
              <VCol
                v-if="currentItem?.driver"
                cols="12"
                md="6"
              >
                <strong>{{ t('connection.driver', 'Driver') }}:</strong>
                <VChip
                  size="small"
                  color="primary"
                  variant="tonal"
                >
                  {{ currentItem.driver }}
                </VChip>
              </VCol>
              <VCol
                v-if="currentItem?.host"
                cols="12"
                md="6"
              >
                <strong>{{ t('connection.host', 'Host') }}:</strong> {{ currentItem.host }}
              </VCol>
              <VCol
                v-if="currentItem?.port"
                cols="12"
                md="6"
              >
                <strong>{{ t('connection.port', 'Port') }}:</strong> {{ currentItem.port }}
              </VCol>
              <VCol
                v-if="currentItem?.database_name"
                cols="12"
                md="6"
              >
                <strong>{{ t('connection.database_name', 'Database') }}:</strong> {{ currentItem.database_name }}
              </VCol>
              <VCol
                v-if="currentItem?.username"
                cols="12"
                md="6"
              >
                <strong>{{ t('connection.username', 'Username') }}:</strong> {{ currentItem.username }}
              </VCol>
              <VCol
                v-if="currentItem?.is_active !== undefined"
                cols="12"
                md="6"
              >
                <strong>{{ t('connection.status', 'Status') }}:</strong>
                <VChip
                  size="small"
                  :color="currentItem.is_active ? 'success' : 'grey'"
                  variant="tonal"
                >
                  {{ currentItem.is_active ? t('connection.active', 'Active') : t('connection.inactive', 'Inactive') }}
                </VChip>
              </VCol>
              <VCol
                v-if="currentItem?.created_at"
                cols="12"
                md="6"
              >
                <strong>{{ t('connection.created_at', 'Created At') }}:</strong>
                {{ new Date(currentItem.created_at).toLocaleDateString() }}
              </VCol>
              <VCol
                v-if="currentItem?.creator"
                cols="12"
                md="6"
              >
                <strong>{{ t('connection.created_by', 'Created By') }}:</strong>
                {{ currentItem.creator.name }} <span v-if="currentItem.creator.email">({{ currentItem.creator.email }})</span>
              </VCol>
              <VCol
                v-if="currentItem?.connection_string"
                cols="12"
              >
                <strong>{{ t('connection.connection_string', 'Connection String') }}:</strong>
                <VTextField
                  :model-value="currentItem.connection_string"
                  readonly
                  density="compact"
                  hide-details
                  append-inner-icon="tabler-copy"
                  :append-inner-icon-color="copied ? 'success' : 'grey'"
                  @click:append-inner="copyConnectionString(currentItem.connection_string)"
                />
                <span
                  v-if="copied"
                  class="text-success text-caption"
                >{{ t('connection.copied', 'Copied!') }}</span>
              </VCol>
            </VRow>
          </VCardText>
        </VCard>
      </div>
      <div v-else>
        Loading...
      </div>
    </VCardText>
  </VCard>
</template>

<style scoped>
.connection-detail {
  margin-block: 0;
  margin-inline: auto;
  max-inline-size: 700px;
}
</style>
