<!-- Generated by DDD Module Generator on 2025-07-04 -->
<script setup lang="ts">
import debounce from 'lodash/debounce'
import { useI18n } from 'vue-i18n'
import { useConnectionStore } from '../stores/connectionStore'

// Componentes internos
import ConnectionTable from '../components/organisms/ConnectionTable.vue'
import ConnectionAdd from './ConnectionAdd.vue'
import ConnectionDelete from './ConnectionDelete.vue'
import ConnectionEdit from './ConnectionEdit.vue'

// Composable para manejar diálogos
const { openDialog, navigateTo } = useAppManager()
const { t } = useI18n()

// Store
const connectionStore = useConnectionStore()

// Headers para la tabla
const headers = [
  { title: t('connection.name', 'Name'), key: 'name' },
  { title: t('connection.description', 'Description'), key: 'description' },
  { title: t('connection.driver', 'Driver'), key: 'driver' },
  { title: t('connection.status', 'Status'), key: 'is_active' },
  { title: t('connection.created_at', 'Created At'), key: 'created_at' },
  { title: t('actions', 'Actions'), key: 'actions', sortable: false },
]

// Opciones del menú de exportación
const menuOptions = [
  {
    text: 'Export to Excel',
    icon: 'tabler-file-spreadsheet',
    action: () => exportItems('excel'),
  },
  {
    text: 'Export to PDF',
    icon: 'tabler-file-type-pdf',
    action: () => exportItems('pdf'),
  },
]

// Métodos
const debouncedFetchList = debounce(() => {
  connectionStore.fetchList()
}, 500)

function applyFilters() {
  debouncedFetchList()
}

function onPageChange(newPage: number) {
  connectionStore.page = newPage
  connectionStore.fetchList()
}

function onItemsPerPageChange(newItemsPerPage: number) {
  connectionStore.itemsPerPage = newItemsPerPage
  connectionStore.fetchList()
}

function deleteSelected() {
  openDialog(ConnectionDelete, {}, { width: '900px', persistent: true }).then(result => {
    if (result === 'submit')
      connectionStore.fetchList()
  })
}

function openAddDialog() {
  openDialog(ConnectionAdd, { title: 'Add Connection' }, { width: '900px', persistent: true }).then(result => {
    if (result === 'submit')
      connectionStore.fetchList()
  })
}

function openEditDialog(item: any) {
  openDialog(ConnectionEdit, { item, title: 'Edit Connection' }, { width: '800px', persistent: true }).then(result => {
    if (result === 'submit')
      connectionStore.fetchList()
  })
}

function openViewDialog(item: any) {
  navigateTo(`/connections/${item.id}`)
}

function openDeleteDialog(item: any) {
  openDialog(ConnectionDelete, { item, title: 'Delete Connection' }, { width: '900px', persistent: true }).then(result => {
    if (result === 'submit')
      connectionStore.fetchList()
  })
}

function exportItems(type: string) {
  connectionStore.exportItems(type)
}

// onMounted
onMounted(() => {
  connectionStore.fetchList()
})
</script>

<template>
  <VCard>
    <VCardTitle>
      <h4 class="text-h4 mb-1">
        Connections
      </h4>
      <p class="text-body-1 mb-4">
        Manage your database connections
      </p>
    </VCardTitle>

    <VCardText>
      <div class="d-flex align-center flex-wrap gap-4 justify-end">
        <!-- Campo de búsqueda -->
        <VTextField
          v-model="connectionStore.filters.search"
          label="Search connections"
          variant="outlined"
          dense
          class="filter-field"
          @input="applyFilters"
        />

        <!-- Botón para exportar -->
        <GlobalMenu
          label="Export"
          :options="menuOptions"
          color="secondary"
          variant="tonal"
          icon="tabler-chevron-down"
        />

        <!-- Botón para agregar -->
        <VBtn
          prepend-icon="tabler-plus"
          color="primary"
          @click="openAddDialog"
        >
          Add Connection
        </VBtn>

        <!-- Botones para acciones con seleccionados -->
        <VBtn
          v-if="connectionStore.selectedItems.length > 1"
          color="error"
          @click="deleteSelected"
        >
          Delete Selected
        </VBtn>
      </div>
    </VCardText>

    <VDivider />

    <!-- Tabla de elementos -->
    <ConnectionTable
      :headers="headers"
      :items="connectionStore.items"
      :total="connectionStore.total"
      :page="connectionStore.page"
      :items-per-page="connectionStore.itemsPerPage"
      :loading="connectionStore.loading"
      :selection="connectionStore.selectedItems"
      @update:selection="val => connectionStore.selectedItems = val"
      @update:page="onPageChange"
      @update:items-per-page="onItemsPerPageChange"
      @view="openViewDialog"
      @edit="openEditDialog"
      @delete="openDeleteDialog"
    />
  </VCard>
</template>

<style scoped>
.filter-field {
  flex: 1;
  max-inline-size: 300px;
}
</style>
