<!-- Generated by DDD Module Generator on 2025-07-04 -->
<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import { useAppManager } from '@/composables/useAppManager'
import { useConnectionStore } from '../stores/connectionStore'

interface Props {
  item?: any
}

const props = defineProps<Props>()
const { t } = useI18n()
const { closeDialog } = useAppManager()
const store = useConnectionStore()

function close(result: 'close' | 'submit' | 'cancel' = 'close') {
  closeDialog(result)
}

async function confirmDelete() {
  try {
    if (props.item)
      await store.deleteItem(props.item.id)

    close('submit')
  }
  catch (error) {
    console.error('Error al eliminar:', error)
  }
}
</script>

<template>
  <VCard class="pa-sm-10 pa-2">
    <VCardText>
      <h4 class="text-h4 text-center mb-2">
        {{ t('connection.delete_confirm', { name: props.item?.name }) }}
      </h4>
      <div class="text-center">
        <VBtn
          color="error"
          @click="confirmDelete"
        >
          {{ t('confirmDelete') }}
        </VBtn>
        <VBtn
          color="secondary"
          variant="tonal"
          class="ml-2"
          @click="close"
        >
          {{ t('cancel') }}
        </VBtn>
      </div>
    </VCardText>
  </VCard>
</template>
