<!-- Generated by DDD Module Generator on 2025-07-04 -->
<script setup lang="ts">
import { computed, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import { useConnectionStore } from '../stores/connectionStore'
import ConnectionForm from '../components/organisms/ConnectionForm.vue'

const route = useRoute()
const store = useConnectionStore()
const currentItem = computed(() => store.currentItem)

onMounted(async () => {
  await store.fetchById(route.params.id as string)
})
</script>

<template>
  <ConnectionForm
    mode="edit"
    :initial-data="currentItem"
  />
</template>
