<!-- Generated by DDD Module Generator on 2025-07-04 -->
<script setup lang="ts">
import ConnectionForm from '../components/organisms/ConnectionForm.vue'
</script>

<template>
  <ConnectionForm mode="create" />
</template>
