// Generated by DDD Module Generator on 2025-09-11

import type { Document } from '../../../domain/entities/Document'
import { DocumentMapper } from '../../../application/mappers/DocumentMapper'

export class DocumentTransformer {
  static fromApi(apiData: any): Document | null {
    return DocumentMapper.toDomain(apiData)
  }

  static toApi(document: Document): any {
    return DocumentMapper.toPersistence(document)
  }

  static manyFromApi(apiDataArray: any[]): Document[] {
    return apiDataArray
      .map(apiData => this.fromApi(apiData))
      .filter(Boolean) as Document[]
  }
}
