// Generated by DDD Module Generator on 2025-07-04

import type { ApiAuthType, ConnectionDriver, FileFormat } from '../../domain/entities/Connection'

// Tipos de drivers soportados
export type DatabaseDriver = 'mysql' | 'postgresql' | 'sqlserver' | 'oracle' | 'sqlite'
export type ConnectionDriverType = DatabaseDriver | 'api' | 'file'

// Configuraciones específicas por tipo
export interface DatabaseConnectionConfig {
  host: string
  port: number
  database_name: string
  username: string
  password: string
  options?: Record<string, any>
}

export interface ApiConnectionConfig {
  api_base_url: string
  api_auth_type: ApiAuthType
  api_auth_config?: {
    token?: string
    username?: string
    password?: string
    api_key?: string
    headers?: Record<string, string>
  }
}

export interface FileConnectionConfig {
  file_path: string
  file_config: {
    format: FileFormat
    delimiter?: string
    has_header?: boolean
    encoding?: string
    date_format?: string
  }
}

export interface CreateConnectionDto {
  name: string
  description?: string
  driver: ConnectionDriver

  // Configuraciones específicas por tipo
  host?: string
  port?: number
  database_name?: string
  username?: string
  password?: string
  file_path?: string
  file_config?: Record<string, any>
  api_base_url?: string
  api_auth_type?: ApiAuthType
  api_auth_config?: Record<string, any>
  options?: Record<string, any>

  // Campos comunes
  status?: 'active' | 'inactive' | 'testing' | 'error'
  metadata?: Record<string, any>
}

export interface UpdateConnectionDto {
  id: string
  name: string
  description?: string
  driver: ConnectionDriver

  // Configuraciones específicas por tipo
  host?: string
  port?: number
  database_name?: string
  username?: string
  password?: string
  file_path?: string
  file_config?: Record<string, any>
  api_base_url?: string
  api_auth_type?: ApiAuthType
  api_auth_config?: Record<string, any>
  options?: Record<string, any>

  // Campos comunes
  status?: 'active' | 'inactive' | 'testing' | 'error'
  metadata?: Record<string, any>
}

export interface ConnectionResponseDto {
  id: string
  name: string
  description?: string
  driver: ConnectionDriver

  // Configuraciones específicas por tipo
  host?: string
  port?: number
  database_name?: string
  username?: string
  password_encrypted?: string
  file_path?: string
  file_config?: Record<string, any>
  api_base_url?: string
  api_auth_type?: ApiAuthType
  api_auth_config?: Record<string, any>
  options?: Record<string, any>

  // Campos comunes
  status: 'active' | 'inactive' | 'testing' | 'error'
  created_at: Date
  updated_at: Date
  createdAt: Date
  updatedAt: Date
  company_id?: string
  is_active?: boolean
  created_by?: string
  metadata?: Record<string, any>
}

// DTOs específicos para testing
export interface TestConnectionDto {
  name: string
  driver: ConnectionDriver

  // Configuraciones específicas por tipo
  host?: string
  port?: number
  database_name?: string
  username?: string
  password?: string
  file_path?: string
  file_config?: Record<string, any>
  api_base_url?: string
  api_auth_type?: ApiAuthType
  api_auth_config?: Record<string, any>
  options?: Record<string, any>
}

export interface TestConnectionResponseDto {
  success: boolean
  message: string
  data?: {
    connected: boolean
    details?: {
      driver?: string
      host?: string
      database?: string
      message?: string
    }
  }
}

// DTOs para exploración de esquemas
export interface TableInfoDto {
  name: string
  type: 'table' | 'view'
}

export interface ProcedureInfoDto {
  name: string
  params?: Array<{
    name: string
    type: string
  }>
}

export interface ColumnInfoDto {
  name: string
  type: string
}

export interface ProcedurePreviewDto {
  procedure_name: string
  parameters: string[]
}

export interface TestQueryDto {
  type: 'custom_sql' | 'query_builder'
  sql?: string
  parameters?: string[]
  query?: Record<string, any>
}

export interface TestQueryResponseDto {
  success: boolean
  data?: {
    columns: string[]
    rows: Record<string, any>[]
    total_rows: number
    execution_time_ms: number
  }
}
