// Generated by DDD Module Generator on 2025-07-04

import { DomainEvent } from '../../../shared/domain/base/DomainEvent'
import type { DataSource } from '../entities/DataSource'

export class DataSourceDeleted extends DomainEvent {
  public dataSource: DataSource

  constructor(dataSource: DataSource) {
    super(dataSource.id.toString())
    this.dataSource = dataSource
  }
}
