// Generated by DDD Module Generator on 2025-07-04

import { Execution } from '../../domain/entities/Execution'
import type { ExecutionResponseDto } from '../dtos/ExecutionDtos'
import { UniqueEntityID } from '../../../shared/domain/base/UniqueEntityID'

export class ExecutionMapper {
  public static toDto(execution: Execution): ExecutionResponseDto {
    return {
      id: execution.id.toString(),
      report_id: execution.props.report_id,
      export_format: execution.props.export_format,
      filters: execution.props.filters,
      status: execution.props.status,
      result_count: execution.props.result_count,
      execution_time: execution.props.execution_time,
      error_message: execution.props.error_message,
      download_url: execution.props.download_url,
      created_at: execution.props.created_at,
      createdAt: execution.props.createdAt,
      updatedAt: execution.props.updatedAt,
    }
  }

  public static toDomain(raw: any): Execution {
    const executionOrError = Execution.create(
      {
        report_id: raw.report_id,
        export_format: raw.export_format,
        filters: raw.filters,
        status: raw.status,
        result_count: raw.result_count,
        execution_time: raw.execution_time,
        error_message: raw.error_message,
        download_url: raw.download_url,
        created_at: raw.created_at,
        createdAt: raw.created_at ? new Date(raw.created_at) : new Date(),
        updatedAt: raw.updated_at ? new Date(raw.updated_at) : new Date(),
      },
      new UniqueEntityID(raw.id),
    )

    return executionOrError.isSuccess
      ? executionOrError.getValue()
      : null
  }

  public static toPersistence(execution: Execution): any {
    return {
      id: execution.id.toString(),
      report_id: execution.props.report_id,
      export_format: execution.props.export_format,
      filters: execution.props.filters,
      status: execution.props.status,
      result_count: execution.props.result_count,
      execution_time: execution.props.execution_time,
      error_message: execution.props.error_message,
      download_url: execution.props.download_url,
      created_at: execution.props.created_at,
      created_at: execution.props.createdAt,
      updated_at: execution.props.updatedAt,
    }
  }
}
