// Generated by DDD Module Generator on 2025-07-04

export interface CreateReportDto {
  data_source_id: string
  name: string
  description?: string
  selected_fields: Record<string, any>
  export_formats: Record<string, any>
  default_filters?: Record<string, any>
  is_public?: boolean
}

export interface UpdateReportDto {
  id: string
  data_source_id: string
  name: string
  description?: string
  selected_fields: Record<string, any>
  export_formats: Record<string, any>
  default_filters?: Record<string, any>
  is_public?: boolean
}

export interface ReportResponseDto {
  id: string
  data_source_id: string
  name: string
  description: string
  selected_fields: Record<string, any>
  export_formats: Record<string, any>
  default_filters: Record<string, any>
  is_public: boolean
  created_at: Date
  updated_at: Date
  createdAt: Date
  updatedAt: Date
}
