// Generated by DDD Module Generator on 2025-07-04

export class ExecutionValidationError extends Error {
  constructor(message: string = 'Execution validation failed') {
    super(message)
    this.name = 'ExecutionValidationError'
  }
}
