// Generated by DDD Module Generator on 2025-07-04

export class ExecutionNotFound extends Error {
  constructor(message: string = 'Execution not found') {
    super(message)
    this.name = 'ExecutionNotFound'
  }
}
