// Generated by DDD Module Generator on 2025-07-04

export interface UpdateExecutionCommand {
  id: string
  report_id: string
  export_format: 'table' | 'excel' | 'pdf' | 'csv' | 'json'
  filters?: Record<string, any>
  status?: 'pending' | 'running' | 'completed' | 'failed'
  result_count?: number
  execution_time?: number
  error_message?: string
  download_url?: string
}
